package trnpbulkvhclreqapp.model.views.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 24 12:20:19 IST 2023
// ---------------------------------------------------------------------
public interface SlsTrnpBulkVrSummVORow
  extends Row
{

  String getOrgId();

  String getHoOrgId();

  void setHoOrgId(String value);

  String getDocId();

  void setDocId(String value);

  String getBtoDocId();

  void setBtoDocId(String value);

  String getWhId();

  void setWhId(String value);

  String getTransCageName();

  void setTransCageName(String value);

  String getTransBTONo();

  void setTransBTONo(String value);
}

