package trnpbulkvhclreqapp.model.services.common;

import java.util.ArrayList;

import java.util.List;

import oracle.jbo.ApplicationModule;

import trnpbulkvhclreqapp.model.classes.BulkSoList;
import trnpbulkvhclreqapp.model.classes.BulkTrfList;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jul 07 15:52:21 IST 2018
// ---------------------------------------------------------------------
public interface TrnpBulkVhclReqAM extends ApplicationModule
{
    void searchBulkSo();

    void resetBulkSo();


    void addListOfOrders();

    List<BulkSoList> getSoList();


    void populateItemDetail();

    void setSelectDocIdOnViewPage();

    void resetBulkLR();

    void searchBulkLR();

    void setnullOnAddPage();

    void createInsertSoBulkHdr();

    Integer validateReqValue();

    void generateBulkRequest();

    String validateItemDetails();

    String deleteSalesOrderSrc(String SrcDocId);

    String getFreezeVal();

    Integer validateHdrBulkVr();

    oracle.jbo.domain.Number getTotalGrossWtVal();

    String showShipAddFeature();


    void cancelOldBulkRequest();

    void refreshMainView(String docId);

    void executeBulkLr();

    oracle.jbo.domain.Number getTotalBalanceWtVal();


  String getWfNo();

    void wfReturnAction(String mode);


    void revertWfChanges(String DocTxnId);

    String insertIntoWF(String wfId, Integer lvlFrm, Integer lvlTo, String action, String remark,
                        oracle.jbo.domain.Number amount);

    Integer currUsrLvl(String WfNum);

    Integer chkPendingUsr();

    String getUsrNm(Integer usrId);

    void selectAllDoc(String action);

    void selectAllItem(String action);

    void updateSchlDt();

    oracle.jbo.domain.Number getTotalBundleVal();

    oracle.jbo.domain.Number getTotalAmount();

    String checkVehicle();

    String checkStockDetails();

    String checkSrcVo();

    Integer amendVhclSchdl();

    String saveBulkLrAction();

    void refrshStk();

    Integer chkVhclNoSchdlStat(String vhclNo);

    String chkCageStatus();

    void rollback();

    Integer popVehicle();

    Integer catgIdFrmEoId();

    String validateBulkVr();

    String populateRptData(String linkId);

  void selectAllDocTrf(String action);

  List<BulkTrfList> getTrfList();

  void setTrfList(List<BulkTrfList> TrfList);

  String removeItemFromVr(String type);

  void selectAllVRItem(String action);

  String getLoadingStatus();
}

