package trnpbulkvhclreqapp.model.entities;

import java.math.BigDecimal;
import java.math.BigInteger;

import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jul 12 19:14:04 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SlsSoDlvSchdlEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        CldId,
        SlocId,
        OrgId,
        HoOrgId,
        DocId,
        ItmSrNo,
        ItmId,
        DlvDt,
        TotQty,
        DlvMode,
        DlvQty,
        TlrncQtyType,
        TlrncQtyVal,
        WhId,
        DlvAddsId,
        UsrIdCreate,
        UsrIdCreateDt,
        UsrIdMod,
        UsrIdModDt,
        DlvSchdlNo,
        AvlQty,
        ItmUomBs,
        UomConvFctr,
        DlvQtyBs,
        BalQty,
        ItmUom,
        Remarks,
        PlnQty,
        PrjId,
        TmpBalQty,
        RsrvQty,
        CntQty,
        DlvType,
        GtcId,
        ShipFlg,
        AtcId,
        PoDocId,
        ReturnQty,
        PiBalQty,
        OldBalQty,
        CnslFlg,
        DlvTime,
        LrTempBalQty,
        LrBalQty;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CLDID = AttributesEnum.CldId.index();
    public static final int SLOCID = AttributesEnum.SlocId.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int HOORGID = AttributesEnum.HoOrgId.index();
    public static final int DOCID = AttributesEnum.DocId.index();
    public static final int ITMSRNO = AttributesEnum.ItmSrNo.index();
    public static final int ITMID = AttributesEnum.ItmId.index();
    public static final int DLVDT = AttributesEnum.DlvDt.index();
    public static final int TOTQTY = AttributesEnum.TotQty.index();
    public static final int DLVMODE = AttributesEnum.DlvMode.index();
    public static final int DLVQTY = AttributesEnum.DlvQty.index();
    public static final int TLRNCQTYTYPE = AttributesEnum.TlrncQtyType.index();
    public static final int TLRNCQTYVAL = AttributesEnum.TlrncQtyVal.index();
    public static final int WHID = AttributesEnum.WhId.index();
    public static final int DLVADDSID = AttributesEnum.DlvAddsId.index();
    public static final int USRIDCREATE = AttributesEnum.UsrIdCreate.index();
    public static final int USRIDCREATEDT = AttributesEnum.UsrIdCreateDt.index();
    public static final int USRIDMOD = AttributesEnum.UsrIdMod.index();
    public static final int USRIDMODDT = AttributesEnum.UsrIdModDt.index();
    public static final int DLVSCHDLNO = AttributesEnum.DlvSchdlNo.index();
    public static final int AVLQTY = AttributesEnum.AvlQty.index();
    public static final int ITMUOMBS = AttributesEnum.ItmUomBs.index();
    public static final int UOMCONVFCTR = AttributesEnum.UomConvFctr.index();
    public static final int DLVQTYBS = AttributesEnum.DlvQtyBs.index();
    public static final int BALQTY = AttributesEnum.BalQty.index();
    public static final int ITMUOM = AttributesEnum.ItmUom.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int PLNQTY = AttributesEnum.PlnQty.index();
    public static final int PRJID = AttributesEnum.PrjId.index();
    public static final int TMPBALQTY = AttributesEnum.TmpBalQty.index();
    public static final int RSRVQTY = AttributesEnum.RsrvQty.index();
    public static final int CNTQTY = AttributesEnum.CntQty.index();
    public static final int DLVTYPE = AttributesEnum.DlvType.index();
    public static final int GTCID = AttributesEnum.GtcId.index();
    public static final int SHIPFLG = AttributesEnum.ShipFlg.index();
    public static final int ATCID = AttributesEnum.AtcId.index();
    public static final int PODOCID = AttributesEnum.PoDocId.index();
    public static final int RETURNQTY = AttributesEnum.ReturnQty.index();
    public static final int PIBALQTY = AttributesEnum.PiBalQty.index();
    public static final int OLDBALQTY = AttributesEnum.OldBalQty.index();
    public static final int CNSLFLG = AttributesEnum.CnslFlg.index();
    public static final int DLVTIME = AttributesEnum.DlvTime.index();
    public static final int LRTEMPBALQTY = AttributesEnum.LrTempBalQty.index();
    public static final int LRBALQTY = AttributesEnum.LrBalQty.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SlsSoDlvSchdlEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("trnpbulkvhclreqapp.model.entities.SlsSoDlvSchdlEO");
    }


    /**
     * Gets the attribute value for CldId, using the alias name CldId.
     * @return the value of CldId
     */
    public String getCldId() {
        return (String) getAttributeInternal(CLDID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CldId.
     * @param value value to set the CldId
     */
    public void setCldId(String value) {
        setAttributeInternal(CLDID, value);
    }

    /**
     * Gets the attribute value for SlocId, using the alias name SlocId.
     * @return the value of SlocId
     */
    public Integer getSlocId() {
        return (Integer) getAttributeInternal(SLOCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SlocId.
     * @param value value to set the SlocId
     */
    public void setSlocId(Integer value) {
        setAttributeInternal(SLOCID, value);
    }

    /**
     * Gets the attribute value for OrgId, using the alias name OrgId.
     * @return the value of OrgId
     */
    public String getOrgId() {
        return (String) getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgId.
     * @param value value to set the OrgId
     */
    public void setOrgId(String value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for HoOrgId, using the alias name HoOrgId.
     * @return the value of HoOrgId
     */
    public String getHoOrgId() {
        return (String) getAttributeInternal(HOORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for HoOrgId.
     * @param value value to set the HoOrgId
     */
    public void setHoOrgId(String value) {
        setAttributeInternal(HOORGID, value);
    }

    /**
     * Gets the attribute value for DocId, using the alias name DocId.
     * @return the value of DocId
     */
    public String getDocId() {
        return (String) getAttributeInternal(DOCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DocId.
     * @param value value to set the DocId
     */
    public void setDocId(String value) {
        setAttributeInternal(DOCID, value);
    }

    /**
     * Gets the attribute value for ItmSrNo, using the alias name ItmSrNo.
     * @return the value of ItmSrNo
     */
    public Long getItmSrNo() {
        return (Long) getAttributeInternal(ITMSRNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItmSrNo.
     * @param value value to set the ItmSrNo
     */
    public void setItmSrNo(Long value) {
        setAttributeInternal(ITMSRNO, value);
    }

    /**
     * Gets the attribute value for ItmId, using the alias name ItmId.
     * @return the value of ItmId
     */
    public String getItmId() {
        return (String) getAttributeInternal(ITMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItmId.
     * @param value value to set the ItmId
     */
    public void setItmId(String value) {
        setAttributeInternal(ITMID, value);
    }

    /**
     * Gets the attribute value for DlvDt, using the alias name DlvDt.
     * @return the value of DlvDt
     */
    public Timestamp getDlvDt() {
        return (Timestamp) getAttributeInternal(DLVDT);
    }

    /**
     * Sets <code>value</code> as the attribute value for DlvDt.
     * @param value value to set the DlvDt
     */
    public void setDlvDt(Timestamp value) {
        setAttributeInternal(DLVDT, value);
    }

    /**
     * Gets the attribute value for TotQty, using the alias name TotQty.
     * @return the value of TotQty
     */
    public oracle.jbo.domain.Number getTotQty() {
        return (oracle.jbo.domain.Number) getAttributeInternal(TOTQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotQty.
     * @param value value to set the TotQty
     */
    public void setTotQty(oracle.jbo.domain.Number value) {
        setAttributeInternal(TOTQTY, value);
    }

    /**
     * Gets the attribute value for DlvMode, using the alias name DlvMode.
     * @return the value of DlvMode
     */
    public Integer getDlvMode() {
        return (Integer) getAttributeInternal(DLVMODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DlvMode.
     * @param value value to set the DlvMode
     */
    public void setDlvMode(Integer value) {
        setAttributeInternal(DLVMODE, value);
    }

    /**
     * Gets the attribute value for DlvQty, using the alias name DlvQty.
     * @return the value of DlvQty
     */
    public Number getDlvQty() {
        return (Number) getAttributeInternal(DLVQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for DlvQty.
     * @param value value to set the DlvQty
     */
    public void setDlvQty(Number value) {
        setAttributeInternal(DLVQTY, value);
    }

    /**
     * Gets the attribute value for TlrncQtyType, using the alias name TlrncQtyType.
     * @return the value of TlrncQtyType
     */
    public String getTlrncQtyType() {
        return (String) getAttributeInternal(TLRNCQTYTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TlrncQtyType.
     * @param value value to set the TlrncQtyType
     */
    public void setTlrncQtyType(String value) {
        setAttributeInternal(TLRNCQTYTYPE, value);
    }

    /**
     * Gets the attribute value for TlrncQtyVal, using the alias name TlrncQtyVal.
     * @return the value of TlrncQtyVal
     */
    public Number getTlrncQtyVal() {
        return (Number) getAttributeInternal(TLRNCQTYVAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for TlrncQtyVal.
     * @param value value to set the TlrncQtyVal
     */
    public void setTlrncQtyVal(Number value) {
        setAttributeInternal(TLRNCQTYVAL, value);
    }

    /**
     * Gets the attribute value for WhId, using the alias name WhId.
     * @return the value of WhId
     */
    public String getWhId() {
        return (String) getAttributeInternal(WHID);
    }

    /**
     * Sets <code>value</code> as the attribute value for WhId.
     * @param value value to set the WhId
     */
    public void setWhId(String value) {
        setAttributeInternal(WHID, value);
    }

    /**
     * Gets the attribute value for DlvAddsId, using the alias name DlvAddsId.
     * @return the value of DlvAddsId
     */
    public String getDlvAddsId() {
        return (String) getAttributeInternal(DLVADDSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DlvAddsId.
     * @param value value to set the DlvAddsId
     */
    public void setDlvAddsId(String value) {
        setAttributeInternal(DLVADDSID, value);
    }

    /**
     * Gets the attribute value for UsrIdCreate, using the alias name UsrIdCreate.
     * @return the value of UsrIdCreate
     */
    public Integer getUsrIdCreate() {
        return (Integer) getAttributeInternal(USRIDCREATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UsrIdCreate.
     * @param value value to set the UsrIdCreate
     */
    public void setUsrIdCreate(Integer value) {
        setAttributeInternal(USRIDCREATE, value);
    }

    /**
     * Gets the attribute value for UsrIdCreateDt, using the alias name UsrIdCreateDt.
     * @return the value of UsrIdCreateDt
     */
    public Timestamp getUsrIdCreateDt() {
        return (Timestamp) getAttributeInternal(USRIDCREATEDT);
    }

    /**
     * Sets <code>value</code> as the attribute value for UsrIdCreateDt.
     * @param value value to set the UsrIdCreateDt
     */
    public void setUsrIdCreateDt(Timestamp value) {
        setAttributeInternal(USRIDCREATEDT, value);
    }

    /**
     * Gets the attribute value for UsrIdMod, using the alias name UsrIdMod.
     * @return the value of UsrIdMod
     */
    public Integer getUsrIdMod() {
        return (Integer) getAttributeInternal(USRIDMOD);
    }

    /**
     * Sets <code>value</code> as the attribute value for UsrIdMod.
     * @param value value to set the UsrIdMod
     */
    public void setUsrIdMod(Integer value) {
        setAttributeInternal(USRIDMOD, value);
    }

    /**
     * Gets the attribute value for UsrIdModDt, using the alias name UsrIdModDt.
     * @return the value of UsrIdModDt
     */
    public Timestamp getUsrIdModDt() {
        return (Timestamp) getAttributeInternal(USRIDMODDT);
    }

    /**
     * Sets <code>value</code> as the attribute value for UsrIdModDt.
     * @param value value to set the UsrIdModDt
     */
    public void setUsrIdModDt(Timestamp value) {
        setAttributeInternal(USRIDMODDT, value);
    }

    /**
     * Gets the attribute value for DlvSchdlNo, using the alias name DlvSchdlNo.
     * @return the value of DlvSchdlNo
     */
    public Integer getDlvSchdlNo() {
        return (Integer) getAttributeInternal(DLVSCHDLNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for DlvSchdlNo.
     * @param value value to set the DlvSchdlNo
     */
    public void setDlvSchdlNo(Integer value) {
        setAttributeInternal(DLVSCHDLNO, value);
    }

    /**
     * Gets the attribute value for AvlQty, using the alias name AvlQty.
     * @return the value of AvlQty
     */
    public Number getAvlQty() {
        return (Number) getAttributeInternal(AVLQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for AvlQty.
     * @param value value to set the AvlQty
     */
    public void setAvlQty(Number value) {
        setAttributeInternal(AVLQTY, value);
    }

    /**
     * Gets the attribute value for ItmUomBs, using the alias name ItmUomBs.
     * @return the value of ItmUomBs
     */
    public String getItmUomBs() {
        return (String) getAttributeInternal(ITMUOMBS);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItmUomBs.
     * @param value value to set the ItmUomBs
     */
    public void setItmUomBs(String value) {
        setAttributeInternal(ITMUOMBS, value);
    }

    /**
     * Gets the attribute value for UomConvFctr, using the alias name UomConvFctr.
     * @return the value of UomConvFctr
     */
    public Number getUomConvFctr() {
        return (Number) getAttributeInternal(UOMCONVFCTR);
    }

    /**
     * Sets <code>value</code> as the attribute value for UomConvFctr.
     * @param value value to set the UomConvFctr
     */
    public void setUomConvFctr(Number value) {
        setAttributeInternal(UOMCONVFCTR, value);
    }

    /**
     * Gets the attribute value for DlvQtyBs, using the alias name DlvQtyBs.
     * @return the value of DlvQtyBs
     */
    public Number getDlvQtyBs() {
        return (Number) getAttributeInternal(DLVQTYBS);
    }

    /**
     * Sets <code>value</code> as the attribute value for DlvQtyBs.
     * @param value value to set the DlvQtyBs
     */
    public void setDlvQtyBs(Number value) {
        setAttributeInternal(DLVQTYBS, value);
    }

    /**
     * Gets the attribute value for BalQty, using the alias name BalQty.
     * @return the value of BalQty
     */
    public Number getBalQty() {
        return (Number) getAttributeInternal(BALQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for BalQty.
     * @param value value to set the BalQty
     */
    public void setBalQty(Number value) {
        setAttributeInternal(BALQTY, value);
    }

    /**
     * Gets the attribute value for ItmUom, using the alias name ItmUom.
     * @return the value of ItmUom
     */
    public String getItmUom() {
        return (String) getAttributeInternal(ITMUOM);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItmUom.
     * @param value value to set the ItmUom
     */
    public void setItmUom(String value) {
        setAttributeInternal(ITMUOM, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the value of Remarks
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for PlnQty, using the alias name PlnQty.
     * @return the value of PlnQty
     */
    public Number getPlnQty() {
        return (Number) getAttributeInternal(PLNQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for PlnQty.
     * @param value value to set the PlnQty
     */
    public void setPlnQty(Number value) {
        setAttributeInternal(PLNQTY, value);
    }

    /**
     * Gets the attribute value for PrjId, using the alias name PrjId.
     * @return the value of PrjId
     */
    public String getPrjId() {
        return (String) getAttributeInternal(PRJID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PrjId.
     * @param value value to set the PrjId
     */
    public void setPrjId(String value) {
        setAttributeInternal(PRJID, value);
    }

    /**
     * Gets the attribute value for TmpBalQty, using the alias name TmpBalQty.
     * @return the value of TmpBalQty
     */
    public Number getTmpBalQty() {
        return (Number) getAttributeInternal(TMPBALQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for TmpBalQty.
     * @param value value to set the TmpBalQty
     */
    public void setTmpBalQty(Number value) {
        setAttributeInternal(TMPBALQTY, value);
    }

    /**
     * Gets the attribute value for RsrvQty, using the alias name RsrvQty.
     * @return the value of RsrvQty
     */
    public Number getRsrvQty() {
        return (Number) getAttributeInternal(RSRVQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for RsrvQty.
     * @param value value to set the RsrvQty
     */
    public void setRsrvQty(Number value) {
        setAttributeInternal(RSRVQTY, value);
    }

    /**
     * Gets the attribute value for CntQty, using the alias name CntQty.
     * @return the value of CntQty
     */
    public Number getCntQty() {
        return (Number) getAttributeInternal(CNTQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CntQty.
     * @param value value to set the CntQty
     */
    public void setCntQty(Number value) {
        setAttributeInternal(CNTQTY, value);
    }

    /**
     * Gets the attribute value for DlvType, using the alias name DlvType.
     * @return the value of DlvType
     */
    public Integer getDlvType() {
        return (Integer) getAttributeInternal(DLVTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DlvType.
     * @param value value to set the DlvType
     */
    public void setDlvType(Integer value) {
        setAttributeInternal(DLVTYPE, value);
    }

    /**
     * Gets the attribute value for GtcId, using the alias name GtcId.
     * @return the value of GtcId
     */
    public String getGtcId() {
        return (String) getAttributeInternal(GTCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for GtcId.
     * @param value value to set the GtcId
     */
    public void setGtcId(String value) {
        setAttributeInternal(GTCID, value);
    }

    /**
     * Gets the attribute value for ShipFlg, using the alias name ShipFlg.
     * @return the value of ShipFlg
     */
    public String getShipFlg() {
        return (String) getAttributeInternal(SHIPFLG);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipFlg.
     * @param value value to set the ShipFlg
     */
    public void setShipFlg(String value) {
        setAttributeInternal(SHIPFLG, value);
    }

    /**
     * Gets the attribute value for AtcId, using the alias name AtcId.
     * @return the value of AtcId
     */
    public String getAtcId() {
        return (String) getAttributeInternal(ATCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for AtcId.
     * @param value value to set the AtcId
     */
    public void setAtcId(String value) {
        setAttributeInternal(ATCID, value);
    }

    /**
     * Gets the attribute value for PoDocId, using the alias name PoDocId.
     * @return the value of PoDocId
     */
    public String getPoDocId() {
        return (String) getAttributeInternal(PODOCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PoDocId.
     * @param value value to set the PoDocId
     */
    public void setPoDocId(String value) {
        setAttributeInternal(PODOCID, value);
    }

    /**
     * Gets the attribute value for ReturnQty, using the alias name ReturnQty.
     * @return the value of ReturnQty
     */
    public Number getReturnQty() {
        return (Number) getAttributeInternal(RETURNQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReturnQty.
     * @param value value to set the ReturnQty
     */
    public void setReturnQty(Number value) {
        setAttributeInternal(RETURNQTY, value);
    }

    /**
     * Gets the attribute value for PiBalQty, using the alias name PiBalQty.
     * @return the value of PiBalQty
     */
    public Number getPiBalQty() {
        return (Number) getAttributeInternal(PIBALQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for PiBalQty.
     * @param value value to set the PiBalQty
     */
    public void setPiBalQty(Number value) {
        setAttributeInternal(PIBALQTY, value);
    }

    /**
     * Gets the attribute value for OldBalQty, using the alias name OldBalQty.
     * @return the value of OldBalQty
     */
    public Number getOldBalQty() {
        return (Number) getAttributeInternal(OLDBALQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for OldBalQty.
     * @param value value to set the OldBalQty
     */
    public void setOldBalQty(Number value) {
        setAttributeInternal(OLDBALQTY, value);
    }

    /**
     * Gets the attribute value for CnslFlg, using the alias name CnslFlg.
     * @return the value of CnslFlg
     */
    public String getCnslFlg() {
        return (String) getAttributeInternal(CNSLFLG);
    }

    /**
     * Sets <code>value</code> as the attribute value for CnslFlg.
     * @param value value to set the CnslFlg
     */
    public void setCnslFlg(String value) {
        setAttributeInternal(CNSLFLG, value);
    }

    /**
     * Gets the attribute value for DlvTime, using the alias name DlvTime.
     * @return the value of DlvTime
     */
    public String getDlvTime() {
        return (String) getAttributeInternal(DLVTIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for DlvTime.
     * @param value value to set the DlvTime
     */
    public void setDlvTime(String value) {
        setAttributeInternal(DLVTIME, value);
    }

    /**
     * Gets the attribute value for LrTempBalQty, using the alias name LrTempBalQty.
     * @return the value of LrTempBalQty
     */
    public Number getLrTempBalQty() {
        return (Number) getAttributeInternal(LRTEMPBALQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LrTempBalQty.
     * @param value value to set the LrTempBalQty
     */
    public void setLrTempBalQty(Number value) {
        setAttributeInternal(LRTEMPBALQTY, value);
    }

    /**
     * Gets the attribute value for LrBalQty, using the alias name LrBalQty.
     * @return the value of LrBalQty
     */
    public Number getLrBalQty() {
        return (Number) getAttributeInternal(LRBALQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LrBalQty.
     * @param value value to set the LrBalQty
     */
    public void setLrBalQty(Number value) {
        setAttributeInternal(LRBALQTY, value);
    }


    /**
     * @param cldId key constituent
     * @param slocId key constituent
     * @param orgId key constituent
     * @param hoOrgId key constituent
     * @param docId key constituent
     * @param itmSrNo key constituent
     * @param itmId key constituent
     * @param dlvDt key constituent
     * @param whId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String cldId, Integer slocId, String orgId, String hoOrgId, String docId,
                                       Long itmSrNo, String itmId, Timestamp dlvDt, String whId) {
        return new Key(new Object[] { cldId, slocId, orgId, hoOrgId, docId, itmSrNo, itmId, dlvDt, whId });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
       // super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}

