package trnpbulkvhclreqapp.model.entities;

import adf.utils.bean.StaticValue;
import adf.utils.ebiz.EbizParams;

import java.math.BigDecimal;
import java.math.BigInteger;

import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.NClobDomain;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jul 06 12:54:46 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SlsTrnpBulkVrSrcEOImpl extends EntityImpl
{
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
    CldId,
    SlocId,
    OrgId,
    HoOrgId,
    DocId,
    SrcDocId,
    SrcDocDt,
    EoId,
    VehicleTyp,
    LocId,
    RouteDocId,
    GrossWt,
    ReqTyp,
    UsrIdCreate,
    UsrIdCreateDt,
    UsrIdMod,
    UsrIdModDt,
    DlvDt,
    WhId,
    DlvSchdlNo,
    DeparturePnt,
    ArrivalPnt,
    BlncWt,
    TotBndl,
    TotAmt,
    VhclNo,
    OldVhclNo,
    BtoDocId;
    private static AttributesEnum[] vals = null;
    private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


  public static final int CLDID = AttributesEnum.CldId.index();
  public static final int SLOCID = AttributesEnum.SlocId.index();
  public static final int ORGID = AttributesEnum.OrgId.index();
  public static final int HOORGID = AttributesEnum.HoOrgId.index();
  public static final int DOCID = AttributesEnum.DocId.index();
  public static final int SRCDOCID = AttributesEnum.SrcDocId.index();
  public static final int SRCDOCDT = AttributesEnum.SrcDocDt.index();
  public static final int EOID = AttributesEnum.EoId.index();
  public static final int VEHICLETYP = AttributesEnum.VehicleTyp.index();
  public static final int LOCID = AttributesEnum.LocId.index();
  public static final int ROUTEDOCID = AttributesEnum.RouteDocId.index();
  public static final int GROSSWT = AttributesEnum.GrossWt.index();
  public static final int REQTYP = AttributesEnum.ReqTyp.index();
  public static final int USRIDCREATE = AttributesEnum.UsrIdCreate.index();
  public static final int USRIDCREATEDT = AttributesEnum.UsrIdCreateDt.index();
  public static final int USRIDMOD = AttributesEnum.UsrIdMod.index();
  public static final int USRIDMODDT = AttributesEnum.UsrIdModDt.index();
  public static final int DLVDT = AttributesEnum.DlvDt.index();
  public static final int WHID = AttributesEnum.WhId.index();
  public static final int DLVSCHDLNO = AttributesEnum.DlvSchdlNo.index();
  public static final int DEPARTUREPNT = AttributesEnum.DeparturePnt.index();
  public static final int ARRIVALPNT = AttributesEnum.ArrivalPnt.index();
  public static final int BLNCWT = AttributesEnum.BlncWt.index();
  public static final int TOTBNDL = AttributesEnum.TotBndl.index();
  public static final int TOTAMT = AttributesEnum.TotAmt.index();
  public static final int VHCLNO = AttributesEnum.VhclNo.index();
  public static final int OLDVHCLNO = AttributesEnum.OldVhclNo.index();
  public static final int BTODOCID = AttributesEnum.BtoDocId.index();

  /**
   * This is the default constructor (do not remove).
   */
    public SlsTrnpBulkVrSrcEOImpl() {
    }

  /**
   * @return the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    return EntityDefImpl.findDefObject("trnpbulkvhclreqapp.model.entities.SlsTrnpBulkVrSrcEO");
  }


  /**
   * Gets the attribute value for CldId, using the alias name CldId.
   * @return the value of CldId
   */
    public String getCldId() {
        return (String) getAttributeInternal(CLDID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CldId.
     * @param value value to set the CldId
     */
    public void setCldId(String value) {
        setAttributeInternal(CLDID, value);
    }

    /**
     * Gets the attribute value for SlocId, using the alias name SlocId.
     * @return the value of SlocId
     */
    public Integer getSlocId() {
        return (Integer) getAttributeInternal(SLOCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SlocId.
     * @param value value to set the SlocId
     */
    public void setSlocId(Integer value) {
        setAttributeInternal(SLOCID, value);
    }

    /**
     * Gets the attribute value for OrgId, using the alias name OrgId.
     * @return the value of OrgId
     */
    public String getOrgId() {
        return (String) getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgId.
     * @param value value to set the OrgId
     */
    public void setOrgId(String value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for HoOrgId, using the alias name HoOrgId.
     * @return the value of HoOrgId
     */
    public String getHoOrgId() {
        return (String) getAttributeInternal(HOORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for HoOrgId.
     * @param value value to set the HoOrgId
     */
    public void setHoOrgId(String value) {
        setAttributeInternal(HOORGID, value);
    }

    /**
     * Gets the attribute value for DocId, using the alias name DocId.
     * @return the value of DocId
     */
    public String getDocId() {
        return (String) getAttributeInternal(DOCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DocId.
     * @param value value to set the DocId
     */
    public void setDocId(String value) {
        setAttributeInternal(DOCID, value);
    }

    /**
     * Gets the attribute value for SrcDocId, using the alias name SrcDocId.
     * @return the value of SrcDocId
     */
    public String getSrcDocId() {
        return (String) getAttributeInternal(SRCDOCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SrcDocId.
     * @param value value to set the SrcDocId
     */
    public void setSrcDocId(String value) {
        setAttributeInternal(SRCDOCID, value);
    }

    /**
     * Gets the attribute value for SrcDocDt, using the alias name SrcDocDt.
     * @return the value of SrcDocDt
     */
    public Timestamp getSrcDocDt() {
        return (Timestamp) getAttributeInternal(SRCDOCDT);
    }

    /**
     * Sets <code>value</code> as the attribute value for SrcDocDt.
     * @param value value to set the SrcDocDt
     */
    public void setSrcDocDt(Timestamp value) {
        setAttributeInternal(SRCDOCDT, value);
    }

    /**
     * Gets the attribute value for EoId, using the alias name EoId.
     * @return the value of EoId
     */
    public Integer getEoId() {
        return (Integer) getAttributeInternal(EOID);
    }

    /**
     * Sets <code>value</code> as the attribute value for EoId.
     * @param value value to set the EoId
     */
    public void setEoId(Integer value) {
        setAttributeInternal(EOID, value);
    }

    /**
     * Gets the attribute value for VehicleTyp, using the alias name VehicleTyp.
     * @return the value of VehicleTyp
     */
    public Integer getVehicleTyp() {
        return (Integer) getAttributeInternal(VEHICLETYP);
    }

    /**
     * Sets <code>value</code> as the attribute value for VehicleTyp.
     * @param value value to set the VehicleTyp
     */
    public void setVehicleTyp(Integer value) {
        setAttributeInternal(VEHICLETYP, value);
    }

    /**
     * Gets the attribute value for LocId, using the alias name LocId.
     * @return the value of LocId
     */
    public String getLocId() {
        return (String) getAttributeInternal(LOCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LocId.
     * @param value value to set the LocId
     */
    public void setLocId(String value) {
        setAttributeInternal(LOCID, value);
    }

    /**
     * Gets the attribute value for RouteDocId, using the alias name RouteDocId.
     * @return the value of RouteDocId
     */
    public String getRouteDocId() {
        return (String) getAttributeInternal(ROUTEDOCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RouteDocId.
     * @param value value to set the RouteDocId
     */
    public void setRouteDocId(String value) {
        setAttributeInternal(ROUTEDOCID, value);
    }

    /**
     * Gets the attribute value for GrossWt, using the alias name GrossWt.
     * @return the value of GrossWt
     */
    public oracle.jbo.domain.Number getGrossWt() {
        return (oracle.jbo.domain.Number) getAttributeInternal(GROSSWT);
    }

    /**
     * Sets <code>value</code> as the attribute value for GrossWt.
     * @param value value to set the GrossWt
     */
    public void setGrossWt(oracle.jbo.domain.Number value) {
        setAttributeInternal(GROSSWT, value);
    }

    /**
     * Gets the attribute value for ReqTyp, using the alias name ReqTyp.
     * @return the value of ReqTyp
     */
    public String getReqTyp() {
        return (String) getAttributeInternal(REQTYP);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReqTyp.
     * @param value value to set the ReqTyp
     */
    public void setReqTyp(String value) {
        setAttributeInternal(REQTYP, value);
    }

    /**
     * Gets the attribute value for UsrIdCreate, using the alias name UsrIdCreate.
     * @return the value of UsrIdCreate
     */
    public Integer getUsrIdCreate() {
        return (Integer) getAttributeInternal(USRIDCREATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UsrIdCreate.
     * @param value value to set the UsrIdCreate
     */
    public void setUsrIdCreate(Integer value) {
        setAttributeInternal(USRIDCREATE, value);
    }

    /**
     * Gets the attribute value for UsrIdCreateDt, using the alias name UsrIdCreateDt.
     * @return the value of UsrIdCreateDt
     */
    public oracle.jbo.domain.Timestamp getUsrIdCreateDt() {
        return (oracle.jbo.domain.Timestamp) getAttributeInternal(USRIDCREATEDT);
    }

    /**
     * Sets <code>value</code> as the attribute value for UsrIdCreateDt.
     * @param value value to set the UsrIdCreateDt
     */
    public void setUsrIdCreateDt(oracle.jbo.domain.Timestamp value) {
        setAttributeInternal(USRIDCREATEDT, value);
    }

    /**
     * Gets the attribute value for UsrIdMod, using the alias name UsrIdMod.
     * @return the value of UsrIdMod
     */
    public Integer getUsrIdMod() {
        return (Integer) getAttributeInternal(USRIDMOD);
    }

    /**
     * Sets <code>value</code> as the attribute value for UsrIdMod.
     * @param value value to set the UsrIdMod
     */
    public void setUsrIdMod(Integer value) {
        setAttributeInternal(USRIDMOD, value);
    }

    /**
     * Gets the attribute value for UsrIdModDt, using the alias name UsrIdModDt.
     * @return the value of UsrIdModDt
     */
    public oracle.jbo.domain.Timestamp getUsrIdModDt() {
        return (oracle.jbo.domain.Timestamp) getAttributeInternal(USRIDMODDT);
    }

    /**
     * Sets <code>value</code> as the attribute value for UsrIdModDt.
     * @param value value to set the UsrIdModDt
     */
    public void setUsrIdModDt(oracle.jbo.domain.Timestamp value) {
        setAttributeInternal(USRIDMODDT, value);
    }


    /**
     * Gets the attribute value for DlvDt, using the alias name DlvDt.
     * @return the value of DlvDt
     */
    public oracle.jbo.domain.Timestamp getDlvDt() {
        return (oracle.jbo.domain.Timestamp) getAttributeInternal(DLVDT);
    }

    /**
     * Sets <code>value</code> as the attribute value for DlvDt.
     * @param value value to set the DlvDt
     */
    public void setDlvDt(oracle.jbo.domain.Timestamp value) {
        setAttributeInternal(DLVDT, value);
    }

    /**
     * Gets the attribute value for WhId, using the alias name WhId.
     * @return the value of WhId
     */
    public String getWhId() {
        return (String) getAttributeInternal(WHID);
    }

    /**
     * Sets <code>value</code> as the attribute value for WhId.
     * @param value value to set the WhId
     */
    public void setWhId(String value) {
        setAttributeInternal(WHID, value);
    }

    /**
     * Gets the attribute value for DlvSchdlNo, using the alias name DlvSchdlNo.
     * @return the value of DlvSchdlNo
     */
    public Integer getDlvSchdlNo() {
        return (Integer) getAttributeInternal(DLVSCHDLNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for DlvSchdlNo.
     * @param value value to set the DlvSchdlNo
     */
    public void setDlvSchdlNo(Integer value) {
        setAttributeInternal(DLVSCHDLNO, value);
    }


    /**
     * Gets the attribute value for DeparturePnt, using the alias name DeparturePnt.
     * @return the value of DeparturePnt
     */
    public String getDeparturePnt() {
        return (String) getAttributeInternal(DEPARTUREPNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for DeparturePnt.
     * @param value value to set the DeparturePnt
     */
    public void setDeparturePnt(String value) {
        setAttributeInternal(DEPARTUREPNT, value);
    }

    /**
     * Gets the attribute value for ArrivalPnt, using the alias name ArrivalPnt.
     * @return the value of ArrivalPnt
     */
    public String getArrivalPnt() {
        return (String) getAttributeInternal(ARRIVALPNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ArrivalPnt.
     * @param value value to set the ArrivalPnt
     */
    public void setArrivalPnt(String value) {
        setAttributeInternal(ARRIVALPNT, value);
    }

    /**
     * Gets the attribute value for BlncWt, using the alias name BlncWt.
     * @return the value of BlncWt
     */
    public Number getBlncWt() {
        return (Number) getAttributeInternal(BLNCWT);
    }

    /**
     * Sets <code>value</code> as the attribute value for BlncWt.
     * @param value value to set the BlncWt
     */
    public void setBlncWt(Number value) {
        setAttributeInternal(BLNCWT, value);
    }


    /**
     * Gets the attribute value for TotBndl, using the alias name TotBndl.
     * @return the value of TotBndl
     */
    public Number getTotBndl() {
        return (Number) getAttributeInternal(TOTBNDL);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotBndl.
     * @param value value to set the TotBndl
     */
    public void setTotBndl(Number value) {
        setAttributeInternal(TOTBNDL, value);
    }

    /**
     * Gets the attribute value for TotAmt, using the alias name TotAmt.
     * @return the value of TotAmt
     */
    public Number getTotAmt() {
        return (Number) getAttributeInternal(TOTAMT);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotAmt.
     * @param value value to set the TotAmt
     */
    public void setTotAmt(Number value) {
        setAttributeInternal(TOTAMT, value);
    }


    /**
     * Gets the attribute value for VhclNo, using the alias name VhclNo.
     * @return the value of VhclNo
     */
    public String getVhclNo() {
        return (String) getAttributeInternal(VHCLNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for VhclNo.
     * @param value value to set the VhclNo
     */
    public void setVhclNo(String value) {
        setAttributeInternal(VHCLNO, value);
    }

    /**
     * Gets the attribute value for OldVhclNo, using the alias name OldVhclNo.
     * @return the value of OldVhclNo
     */
    public String getOldVhclNo() {
        return (String) getAttributeInternal(OLDVHCLNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for OldVhclNo.
     * @param value value to set the OldVhclNo
     */
    public void setOldVhclNo(String value) {
        setAttributeInternal(OLDVHCLNO, value);
    }

  /**
   * Gets the attribute value for BtoDocId, using the alias name BtoDocId.
   * @return the value of BtoDocId
   */
  public String getBtoDocId()
  {
    return (String) getAttributeInternal(BTODOCID);
  }

  /**
   * Sets <code>value</code> as the attribute value for BtoDocId.
   * @param value value to set the BtoDocId
   */
  public void setBtoDocId(String value)
  {
    setAttributeInternal(BTODOCID, value);
  }

  /**
   * @param cldId key constituent
   * @param slocId key constituent
   * @param orgId key constituent
   * @param hoOrgId key constituent
   * @param docId key constituent
   * @param srcDocId key constituent
   * @param whId key constituent

   * @return a Key object based on given key constituents.
   */
  public static Key createPrimaryKey(String cldId, Integer slocId, String orgId, String hoOrgId, String docId,
                                     String srcDocId, String whId)
  {
    return new Key(new Object[]
    {
      cldId, slocId, orgId, hoOrgId, docId, srcDocId, whId
    });
  }

  /**
   * Add attribute defaulting logic in this method.
   * @param attributeList list of attribute names/values to initialize the row
   */
    protected void create(AttributeList attributeList) {
        this.setUsrIdCreate(EbizParams.GLBL_APP_USR());
        this.setUsrIdCreateDt(StaticValue.getTruncatedCurrDt());
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
      //  super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation == DML_UPDATE) {
                    this.setUsrIdMod(EbizParams.GLBL_APP_USR());
                    this.setUsrIdModDt(StaticValue.getTruncatedCurrDt());
                }
        super.doDML(operation, e);
    }
}

