package trnpbulkvhclreqapp.model.entities;

import adf.utils.bean.StaticValue;
import adf.utils.ebiz.EbizParams;

import adf.utils.ebiz.EbizParamsAPPUtils;

import java.math.BigDecimal;
import java.math.BigInteger;

import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;

import trnpbulkvhclreqapp.model.services.TrnpBulkVhclReqAMImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jul 06 12:49:04 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SlsTrnpBulkVrEOImpl extends EntityImpl
{
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
    CldId,
    SlocId,
    OrgId,
    HoOrgId,
    DocId,
    DocDt,
    DispId,
    DrftDispId,
    UsrIdCreate,
    UsrIdCreateDt,
    UsrIdMod,
    UsrIdModDt,
    FyId,
    LrStatus,
    Freeze,
    CurrIdSp,
    CurrConvFctr,
    DocTypId,
    VhclNo,
    VrMode,
    CageId,
    AmdDt,
    AmdNo,
    TrfType;
    private static AttributesEnum[] vals = null;
    private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


  public static final int CLDID = AttributesEnum.CldId.index();
  public static final int SLOCID = AttributesEnum.SlocId.index();
  public static final int ORGID = AttributesEnum.OrgId.index();
  public static final int HOORGID = AttributesEnum.HoOrgId.index();
  public static final int DOCID = AttributesEnum.DocId.index();
  public static final int DOCDT = AttributesEnum.DocDt.index();
  public static final int DISPID = AttributesEnum.DispId.index();
  public static final int DRFTDISPID = AttributesEnum.DrftDispId.index();
  public static final int USRIDCREATE = AttributesEnum.UsrIdCreate.index();
  public static final int USRIDCREATEDT = AttributesEnum.UsrIdCreateDt.index();
  public static final int USRIDMOD = AttributesEnum.UsrIdMod.index();
  public static final int USRIDMODDT = AttributesEnum.UsrIdModDt.index();
  public static final int FYID = AttributesEnum.FyId.index();
  public static final int LRSTATUS = AttributesEnum.LrStatus.index();
  public static final int FREEZE = AttributesEnum.Freeze.index();
  public static final int CURRIDSP = AttributesEnum.CurrIdSp.index();
  public static final int CURRCONVFCTR = AttributesEnum.CurrConvFctr.index();
  public static final int DOCTYPID = AttributesEnum.DocTypId.index();
  public static final int VHCLNO = AttributesEnum.VhclNo.index();
  public static final int VRMODE = AttributesEnum.VrMode.index();
  public static final int CAGEID = AttributesEnum.CageId.index();
  public static final int AMDDT = AttributesEnum.AmdDt.index();
  public static final int AMDNO = AttributesEnum.AmdNo.index();
  public static final int TRFTYPE = AttributesEnum.TrfType.index();

  /**
   * This is the default constructor (do not remove).
   */
    public SlsTrnpBulkVrEOImpl() {
    }

  /**
   * @return the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    return EntityDefImpl.findDefObject("trnpbulkvhclreqapp.model.entities.SlsTrnpBulkVrEO");
  }


  /**
   * Gets the attribute value for CldId, using the alias name CldId.
   * @return the value of CldId
   */
    public String getCldId() {
        return (String) getAttributeInternal(CLDID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CldId.
     * @param value value to set the CldId
     */
    public void setCldId(String value) {
        setAttributeInternal(CLDID, value);
    }

    /**
     * Gets the attribute value for SlocId, using the alias name SlocId.
     * @return the value of SlocId
     */
    public Integer getSlocId() {
        return (Integer) getAttributeInternal(SLOCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SlocId.
     * @param value value to set the SlocId
     */
    public void setSlocId(Integer value) {
        setAttributeInternal(SLOCID, value);
    }

    /**
     * Gets the attribute value for OrgId, using the alias name OrgId.
     * @return the value of OrgId
     */
    public String getOrgId() {
        return (String) getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgId.
     * @param value value to set the OrgId
     */
    public void setOrgId(String value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for HoOrgId, using the alias name HoOrgId.
     * @return the value of HoOrgId
     */
    public String getHoOrgId() {
        return (String) getAttributeInternal(HOORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for HoOrgId.
     * @param value value to set the HoOrgId
     */
    public void setHoOrgId(String value) {
        setAttributeInternal(HOORGID, value);
    }

    /**
     * Gets the attribute value for DocId, using the alias name DocId.
     * @return the value of DocId
     */
    public String getDocId() {
        return (String) getAttributeInternal(DOCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DocId.
     * @param value value to set the DocId
     */
    public void setDocId(String value) {
        setAttributeInternal(DOCID, value);
    }

    /**
     * Gets the attribute value for DocDt, using the alias name DocDt.
     * @return the value of DocDt
     */
    public oracle.jbo.domain.Timestamp getDocDt() {
        return (oracle.jbo.domain.Timestamp) getAttributeInternal(DOCDT);
    }

    /**
     * Sets <code>value</code> as the attribute value for DocDt.
     * @param value value to set the DocDt
     */
    public void setDocDt(oracle.jbo.domain.Timestamp value) {
        setAttributeInternal(DOCDT, value);
    }

    /**
     * Gets the attribute value for DispId, using the alias name DispId.
     * @return the value of DispId
     */
    public String getDispId() {
        return (String) getAttributeInternal(DISPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DispId.
     * @param value value to set the DispId
     */
    public void setDispId(String value) {
        setAttributeInternal(DISPID, value);
    }

    /**
     * Gets the attribute value for DrftDispId, using the alias name DrftDispId.
     * @return the value of DrftDispId
     */
    public String getDrftDispId() {
        return (String) getAttributeInternal(DRFTDISPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DrftDispId.
     * @param value value to set the DrftDispId
     */
    public void setDrftDispId(String value) {
        setAttributeInternal(DRFTDISPID, value);
    }

    /**
     * Gets the attribute value for UsrIdCreate, using the alias name UsrIdCreate.
     * @return the value of UsrIdCreate
     */
    public Integer getUsrIdCreate() {
        return (Integer) getAttributeInternal(USRIDCREATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UsrIdCreate.
     * @param value value to set the UsrIdCreate
     */
    public void setUsrIdCreate(Integer value) {
        setAttributeInternal(USRIDCREATE, value);
    }

    /**
     * Gets the attribute value for UsrIdCreateDt, using the alias name UsrIdCreateDt.
     * @return the value of UsrIdCreateDt
     */
    public oracle.jbo.domain.Timestamp getUsrIdCreateDt() {
        return (oracle.jbo.domain.Timestamp) getAttributeInternal(USRIDCREATEDT);
    }

    /**
     * Sets <code>value</code> as the attribute value for UsrIdCreateDt.
     * @param value value to set the UsrIdCreateDt
     */
    public void setUsrIdCreateDt(oracle.jbo.domain.Timestamp value) {
        setAttributeInternal(USRIDCREATEDT, value);
    }

    /**
     * Gets the attribute value for UsrIdMod, using the alias name UsrIdMod.
     * @return the value of UsrIdMod
     */
    public Integer getUsrIdMod() {
        return (Integer) getAttributeInternal(USRIDMOD);
    }

    /**
     * Sets <code>value</code> as the attribute value for UsrIdMod.
     * @param value value to set the UsrIdMod
     */
    public void setUsrIdMod(Integer value) {
        setAttributeInternal(USRIDMOD, value);
    }

    /**
     * Gets the attribute value for UsrIdModDt, using the alias name UsrIdModDt.
     * @return the value of UsrIdModDt
     */
    public oracle.jbo.domain.Timestamp getUsrIdModDt() {
        return (oracle.jbo.domain.Timestamp) getAttributeInternal(USRIDMODDT);
    }

    /**
     * Sets <code>value</code> as the attribute value for UsrIdModDt.
     * @param value value to set the UsrIdModDt
     */
    public void setUsrIdModDt(oracle.jbo.domain.Timestamp value) {
        setAttributeInternal(USRIDMODDT, value);
    }


    /**
     * Gets the attribute value for FyId, using the alias name FyId.
     * @return the value of FyId
     */
    public Integer getFyId() {
        return (Integer) getAttributeInternal(FYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for FyId.
     * @param value value to set the FyId
     */
    public void setFyId(Integer value) {
        setAttributeInternal(FYID, value);
    }

    /**
     * Gets the attribute value for LrStatus, using the alias name LrStatus.
     * @return the value of LrStatus
     */
    public Integer getLrStatus() {
        return (Integer) getAttributeInternal(LRSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for LrStatus.
     * @param value value to set the LrStatus
     */
    public void setLrStatus(Integer value) {
        setAttributeInternal(LRSTATUS, value);
    }


    /**
     * Gets the attribute value for Freeze, using the alias name Freeze.
     * @return the value of Freeze
     */
    public String getFreeze() {
        return (String) getAttributeInternal(FREEZE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Freeze.
     * @param value value to set the Freeze
     */
    public void setFreeze(String value) {
        setAttributeInternal(FREEZE, value);
    }

    /**
     * Gets the attribute value for CurrIdSp, using the alias name CurrIdSp.
     * @return the value of CurrIdSp
     */
    public Integer getCurrIdSp() {
        return (Integer) getAttributeInternal(CURRIDSP);
    }

    /**
     * Sets <code>value</code> as the attribute value for CurrIdSp.
     * @param value value to set the CurrIdSp
     */
    public void setCurrIdSp(Integer value) {
        setAttributeInternal(CURRIDSP, value);
    }

    /**
     * Gets the attribute value for CurrConvFctr, using the alias name CurrConvFctr.
     * @return the value of CurrConvFctr
     */
    public oracle.jbo.domain.Number getCurrConvFctr() {
        return (oracle.jbo.domain.Number) getAttributeInternal(CURRCONVFCTR);
    }

    /**
     * Sets <code>value</code> as the attribute value for CurrConvFctr.
     * @param value value to set the CurrConvFctr
     */
    public void setCurrConvFctr(oracle.jbo.domain.Number value) {
        setAttributeInternal(CURRCONVFCTR, value);
    }


    /**
     * Gets the attribute value for DocTypId, using the alias name DocTypId.
     * @return the value of DocTypId
     */
    public Integer getDocTypId() {
        return (Integer) getAttributeInternal(DOCTYPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DocTypId.
     * @param value value to set the DocTypId
     */
    public void setDocTypId(Integer value) {
        setAttributeInternal(DOCTYPID, value);
    }


    /**
     * Gets the attribute value for VhclNo, using the alias name VhclNo.
     * @return the value of VhclNo
     */
    public String getVhclNo() {
        return (String) getAttributeInternal(VHCLNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for VhclNo.
     * @param value value to set the VhclNo
     */
    public void setVhclNo(String value) {
        setAttributeInternal(VHCLNO, value);
    }

    /**
     * Gets the attribute value for VrMode, using the alias name VrMode.
     * @return the value of VrMode
     */
    public Integer getVrMode() {
        return (Integer) getAttributeInternal(VRMODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for VrMode.
     * @param value value to set the VrMode
     */
    public void setVrMode(Integer value) {
        setAttributeInternal(VRMODE, value);
    }


    /**
     * Gets the attribute value for CageId, using the alias name CageId.
     * @return the value of CageId
     */
    public String getCageId() {
        return (String) getAttributeInternal(CAGEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CageId.
     * @param value value to set the CageId
     */
    public void setCageId(String value) {
        setAttributeInternal(CAGEID, value);
    }


    /**
     * Gets the attribute value for AmdDt, using the alias name AmdDt.
     * @return the value of AmdDt
     */
    public Timestamp getAmdDt() {
        return (Timestamp) getAttributeInternal(AMDDT);
    }

    /**
     * Sets <code>value</code> as the attribute value for AmdDt.
     * @param value value to set the AmdDt
     */
    public void setAmdDt(Timestamp value) {
        setAttributeInternal(AMDDT, value);
    }

    /**
     * Gets the attribute value for AmdNo, using the alias name AmdNo.
     * @return the value of AmdNo
     */
    public String getAmdNo() {
        return (String) getAttributeInternal(AMDNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for AmdNo.
     * @param value value to set the AmdNo
     */
    public void setAmdNo(String value) {
        setAttributeInternal(AMDNO, value);
    }

  /**
   * Gets the attribute value for TrfType, using the alias name TrfType.
   * @return the value of TrfType
   */
  public Integer getTrfType()
  {
    return (Integer) getAttributeInternal(TRFTYPE);
  }

  /**
   * Sets <code>value</code> as the attribute value for TrfType.
   * @param value value to set the TrfType
   */
  public void setTrfType(Integer value)
  {
    setAttributeInternal(TRFTYPE, value);
  }

  /**
   * @param cldId key constituent
   * @param slocId key constituent
   * @param orgId key constituent
   * @param hoOrgId key constituent
   * @param docId key constituent

   * @return a Key object based on given key constituents.
   */
  public static Key createPrimaryKey(String cldId, Integer slocId, String orgId, String hoOrgId, String docId)
  {
    return new Key(new Object[]
    {
      cldId, slocId, orgId, hoOrgId, docId
    });
  }

  /**
   * @return the Application Module
   */ 
    protected TrnpBulkVhclReqAMImpl getAm() {
           return (TrnpBulkVhclReqAMImpl) this.getDBTransaction().getRootApplicationModule();
       }
    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        this.setCldId(EbizParams.GLBL_APP_CLD_ID());
        this.setSlocId(EbizParams.GLBL_APP_SERV_LOC());
        this.setOrgId(EbizParams.GLBL_APP_USR_ORG());
        this.setHoOrgId(EbizParams.GLBL_HO_ORG_ID());
        this.setUsrIdCreate(EbizParams.GLBL_APP_USR());
        this.setDocDt(StaticValue.getCurrDtWidTimestamp());
        this.setUsrIdCreateDt(StaticValue.getTruncatedCurrDt());
        this.setDocId((String)EbizParamsAPPUtils.generateDocTxnId(this.getAm(), 24266));
      /**
              * Added by : Manjeet Singh
              * Modified on : 10-01-2023
              * Remarks : Default Transfer Type will be 'Transfer to Mombasa' i.e 5238'.
              * TMS ID : 129923
              **/
        this.setTrfType(5238);
//        this.setDispId("01XXXBLR");
    /**
       * Modified by : Atul Gusain 
       * Modified on : 08-08-2018
       * Remarks : This method is changed as Draft Id will be generated at the time of Create document. We are getting null in display id before this change.
       * TMS ID : 63982
       **/
        this.setAmdNo("0");
        this.setDrftDispId(getAm().genBulkLrDispId());
        this.setLrStatus(2353);
        this.setFreeze("N");
        this.setFyId(EbizParamsAPPUtils.getFyIdOnCurrDtAndCurrOrg(this.getAm()));
        this.setCurrIdSp(EbizParamsAPPUtils.getCurrIdBsForCurrOrg(this.getAm()));
        this.setDocTypId(2341);
        this.setVrMode(2463);
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        //super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation == DML_UPDATE) {
                    this.setUsrIdMod(EbizParams.GLBL_APP_USR());
                    this.setUsrIdModDt(StaticValue.getTruncatedCurrDt());
                }
        super.doDML(operation, e);
    }
}

