package trnpbulkvhclreqapp.model.views;

import adf.utils.ebiz.EbizParams;

import java.sql.Timestamp;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;

import trnpbulkvhclreqapp.model.services.TrnpBulkVhclReqAMImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jun 14 11:38:07 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DualForDateVORowImpl extends ViewRowImpl
{
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
    Dummy,
    TransSlocId,
    TransCldId,
    TransHoOrgId,
    TransOrgId,
    TransSchlDt,
    TransCurDt,
    TransVhclNo,
    TransRoute,
    TransOwnershipTyp,
    TransCustVhclNo,
    TransDocType,
    LovVhclName1;
    private static AttributesEnum[] vals = null;
    private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


  public static final int DUMMY = AttributesEnum.Dummy.index();
  public static final int TRANSSLOCID = AttributesEnum.TransSlocId.index();
  public static final int TRANSCLDID = AttributesEnum.TransCldId.index();
  public static final int TRANSHOORGID = AttributesEnum.TransHoOrgId.index();
  public static final int TRANSORGID = AttributesEnum.TransOrgId.index();
  public static final int TRANSSCHLDT = AttributesEnum.TransSchlDt.index();
  public static final int TRANSCURDT = AttributesEnum.TransCurDt.index();
  public static final int TRANSVHCLNO = AttributesEnum.TransVhclNo.index();
  public static final int TRANSROUTE = AttributesEnum.TransRoute.index();
  public static final int TRANSOWNERSHIPTYP = AttributesEnum.TransOwnershipTyp.index();
  public static final int TRANSCUSTVHCLNO = AttributesEnum.TransCustVhclNo.index();
  public static final int TRANSDOCTYPE = AttributesEnum.TransDocType.index();
  public static final int LOVVHCLNAME1 = AttributesEnum.LovVhclName1.index();

  /**
   * This is the default constructor (do not remove).
   */
    public DualForDateVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute Dummy.
     * @return the Dummy
     */
    public String getDummy() {
        return (String) getAttributeInternal(DUMMY);
    }

    /**
     * Gets the attribute value for the calculated attribute TransSlocId.
     * @return the TransSlocId
     */
    public Integer getTransSlocId() {
        return EbizParams.GLBL_APP_SERV_LOC();
//        return (Integer) getAttributeInternal(TRANSSLOCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransSlocId.
     * @param value value to set the  TransSlocId
     */
    public void setTransSlocId(Integer value) {
        setAttributeInternal(TRANSSLOCID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransCldId.
     * @return the TransCldId
     */
    public String getTransCldId() {
        return EbizParams.GLBL_APP_CLD_ID();
//        return (String) getAttributeInternal(TRANSCLDID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransCldId.
     * @param value value to set the  TransCldId
     */
    public void setTransCldId(String value) {
        setAttributeInternal(TRANSCLDID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransHoOrgId.
     * @return the TransHoOrgId
     */
    public String getTransHoOrgId() {
        return EbizParams.GLBL_HO_ORG_ID();
//        return (String) getAttributeInternal(TRANSHOORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransHoOrgId.
     * @param value value to set the  TransHoOrgId
     */
    public void setTransHoOrgId(String value) {
        setAttributeInternal(TRANSHOORGID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransOrgId.
     * @return the TransOrgId
     */
    public String getTransOrgId() {
        return EbizParams.GLBL_APP_USR_ORG();
//        return (String) getAttributeInternal(TRANSORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransOrgId.
     * @param value value to set the  TransOrgId
     */
    public void setTransOrgId(String value) {
        setAttributeInternal(TRANSORGID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransSchlDt.
     * @return the TransSchlDt
     */
    public Timestamp getTransSchlDt() {
        return (Timestamp) getAttributeInternal(TRANSSCHLDT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransSchlDt.
     * @param value value to set the  TransSchlDt
     */
    public void setTransSchlDt(Timestamp value) {
        setAttributeInternal(TRANSSCHLDT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransCurDt.
     * @return the TransCurDt
     */
    public Timestamp getTransCurDt() {
        if(getAttributeInternal(TRANSCURDT)==null){
            //System.out.println("================ getAm().getDlvDt() "+getAm().getDlvDt());
            return getAm().getDlvDt();
        }
        return (Timestamp) getAttributeInternal(TRANSCURDT);
    }
    
    protected TrnpBulkVhclReqAMImpl getAm() {
        return (TrnpBulkVhclReqAMImpl) this.getDBTransaction().getRootApplicationModule();
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransCurDt.
     * @param value value to set the  TransCurDt
     */
    public void setTransCurDt(Timestamp value) {
        setAttributeInternal(TRANSCURDT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransVhclNo.
     * @return the TransVhclNo
     */
    public String getTransVhclNo() {
        return (String) getAttributeInternal(TRANSVHCLNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransVhclNo.
     * @param value value to set the  TransVhclNo
     */
    public void setTransVhclNo(String value) {
        setAttributeInternal(TRANSVHCLNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransRoute.
     * @return the TransRoute
     */
    public String getTransRoute() {
        if( getAttributeInternal(TRANSROUTE)== null){
            ViewObjectImpl vo = getAm().getSlsTrnpBulkVrSrc1();
            Row r[] = vo.getAllRowsInRange();
            if(r.length>0){
                String route = (String)r[0].getAttribute("RouteDocId");
                setTransRoute(route);
//                String reqTyp = (String)r[0].getAttribute("ReqTyp");
//                setTransOwnershipTyp(reqTyp);
                }
            }
        return (String) getAttributeInternal(TRANSROUTE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransRoute.
     * @param value value to set the  TransRoute
     */
    public void setTransRoute(String value) {
        setAttributeInternal(TRANSROUTE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransOwnershipTyp.
     * @return the TransOwnershipTyp
     */
    public String getTransOwnershipTyp() {
        if( getAttributeInternal(TRANSOWNERSHIPTYP)== null){
            ViewObjectImpl vo = getAm().getSlsTrnpBulkVrSrc1();
            Row r[] = vo.getAllRowsInRange();
            if(r.length>0){
                String reqTyp = (String)r[0].getAttribute("ReqTyp");
                setTransOwnershipTyp(reqTyp);
                }
            }
        return (String) getAttributeInternal(TRANSOWNERSHIPTYP);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransOwnershipTyp.
     * @param value value to set the  TransOwnershipTyp
     */
    public void setTransOwnershipTyp(String value) {
        setAttributeInternal(TRANSOWNERSHIPTYP, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransCustVhclNo.
     * @return the TransCustVhclNo
     */
    public String getTransCustVhclNo() {
        return (String) getAttributeInternal(TRANSCUSTVHCLNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransCustVhclNo.
     * @param value value to set the  TransCustVhclNo
     */
    public void setTransCustVhclNo(String value) {
        setAttributeInternal(TRANSCUSTVHCLNO, value);
    }

  /**
   * Gets the attribute value for the calculated attribute TransDocType.
   * @return the TransDocType
   */
  /**
   * @return the Application Module
   */

  /**
                     * Modified by : Manjeet Singh
                     * Modified on : 13-10-2023
                     * TMS ID : 128922
                  **/
  public Integer getTransDocType()
  {
//    if(getAttributeInternal(TRANSDOCTYPE)==null)
//    {
//      ViewObject hdrVo = getAm().getSlsTrnpBulkVr1();
//      Row cR = hdrVo.getCurrentRow();
//      Integer typeId = (Integer) cR.getAttribute("DocTypId");
//      System.err.println("______________inside___getTransDocType_____"+typeId);
//      
//      setTransDocType(typeId);
//    }
    return (Integer) getAttributeInternal(TRANSDOCTYPE);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute TransDocType.
   * @param value value to set the  TransDocType
   */
  public void setTransDocType(Integer value)
  {
    setAttributeInternal(TRANSDOCTYPE, value);
  }

  /**
   * Gets the view accessor <code>RowSet</code> LovVhclName1.
   */
    public RowSet getLovVhclName1() {
        return (RowSet) getAttributeInternal(LOVVHCLNAME1);
    }
}

