package trnpbulkvhclreqapp.model.views;

import java.util.List;

import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaItem;
import oracle.jbo.ViewCriteriaRow;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jul 12 17:37:24 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LOVCustNameVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public LOVCustNameVOImpl() {
    }

    /**
     * Returns the bind variable value for bindCldId.
     * @return bind variable value for bindCldId
     */
    public String getbindCldId() {
        return (String) getNamedWhereClauseParam("bindCldId");
    }

    /**
     * Sets <code>value</code> for bind variable bindCldId.
     * @param value value to bind as bindCldId
     */
    public void setbindCldId(String value) {
        setNamedWhereClauseParam("bindCldId", value);
    }

    /**
     * Returns the bind variable value for bindSlocId.
     * @return bind variable value for bindSlocId
     */
    public Integer getbindSlocId() {
        return (Integer) getNamedWhereClauseParam("bindSlocId");
    }

    /**
     * Sets <code>value</code> for bind variable bindSlocId.
     * @param value value to bind as bindSlocId
     */
    public void setbindSlocId(Integer value) {
        setNamedWhereClauseParam("bindSlocId", value);
    }

    /**
     * Returns the bind variable value for bindOrgId.
     * @return bind variable value for bindOrgId
     */
    public String getbindOrgId() {
        return (String) getNamedWhereClauseParam("bindOrgId");
    }

    /**
     * Sets <code>value</code> for bind variable bindOrgId.
     * @param value value to bind as bindOrgId
     */
    public void setbindOrgId(String value) {
        setNamedWhereClauseParam("bindOrgId", value);
    }

    /**
     * Returns the bind variable value for bindHoOrgId.
     * @return bind variable value for bindHoOrgId
     */
    public String getbindHoOrgId() {
        return (String) getNamedWhereClauseParam("bindHoOrgId");
    }

    /**
     * Sets <code>value</code> for bind variable bindHoOrgId.
     * @param value value to bind as bindHoOrgId
     */
    public void setbindHoOrgId(String value) {
        setNamedWhereClauseParam("bindHoOrgId", value);
    }

    /**
     * Returns the bind variable value for bindDocId.
     * @return bind variable value for bindDocId
     */
    public String getbindDocId() {
        return (String) getNamedWhereClauseParam("bindDocId");
    }

    /**
     * Sets <code>value</code> for bind variable bindDocId.
     * @param value value to bind as bindDocId
     */
    public void setbindDocId(String value) {
        setNamedWhereClauseParam("bindDocId", value);
    }
    @Override
    public void applyViewCriteria(ViewCriteria viewCriteria, boolean b) {
        super.applyViewCriteria(supressStartsWithClauseForLov(viewCriteria), b);
    }


    public ViewCriteria supressStartsWithClauseForLov(ViewCriteria vc) {
        if (vc != null && vc.getName().contains("__lov__filterlist__vcr__")) {
            ViewCriteriaRow currentRow = (ViewCriteriaRow) vc.getCurrentRow();
            if (currentRow != null) {
                List criteriaItems = currentRow.getCriteriaItems();
                for (int i = 0; i < criteriaItems.size(); i++) {
                    ViewCriteriaItem object = (ViewCriteriaItem) criteriaItems.get(i);
                    if (object != null) {
                       
                        if ("STARTSWITH".equals(object.getOperator())) {
                            object.setOperator("CONTAINS");
                        }
                    }
                }
            }
        }
        return vc;
    }
}

