package trnpbulkvhclreqapp.model.views;

import java.util.List;

import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaItem;
import oracle.jbo.ViewCriteriaRow;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jul 12 17:40:17 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LOVRouteVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public LOVRouteVOImpl() {
    }

    /**
     * Returns the bind variable value for cldIdbind.
     * @return bind variable value for cldIdbind
     */
    public String getcldIdbind() {
        return (String) getNamedWhereClauseParam("cldIdbind");
    }

    /**
     * Sets <code>value</code> for bind variable cldIdbind.
     * @param value value to bind as cldIdbind
     */
    public void setcldIdbind(String value) {
        setNamedWhereClauseParam("cldIdbind", value);
    }

    /**
     * Returns the bind variable value for slocIdBind.
     * @return bind variable value for slocIdBind
     */
    public Integer getslocIdBind() {
        return (Integer) getNamedWhereClauseParam("slocIdBind");
    }

    /**
     * Sets <code>value</code> for bind variable slocIdBind.
     * @param value value to bind as slocIdBind
     */
    public void setslocIdBind(Integer value) {
        setNamedWhereClauseParam("slocIdBind", value);
    }

    /**
     * Returns the bind variable value for orgIdBind.
     * @return bind variable value for orgIdBind
     */
    public String getorgIdBind() {
        return (String) getNamedWhereClauseParam("orgIdBind");
    }

    /**
     * Sets <code>value</code> for bind variable orgIdBind.
     * @param value value to bind as orgIdBind
     */
    public void setorgIdBind(String value) {
        setNamedWhereClauseParam("orgIdBind", value);
    }

    /**
     * Returns the bind variable value for HoOrgIdBind.
     * @return bind variable value for HoOrgIdBind
     */
    public String getHoOrgIdBind() {
        return (String) getNamedWhereClauseParam("HoOrgIdBind");
    }

    /**
     * Sets <code>value</code> for bind variable HoOrgIdBind.
     * @param value value to bind as HoOrgIdBind
     */
    public void setHoOrgIdBind(String value) {
        setNamedWhereClauseParam("HoOrgIdBind", value);
    }

    /**
     * Returns the bind variable value for RouteDocIdBind.
     * @return bind variable value for RouteDocIdBind
     */
    public String getRouteDocIdBind() {
        return (String) getNamedWhereClauseParam("RouteDocIdBind");
    }

    /**
     * Sets <code>value</code> for bind variable RouteDocIdBind.
     * @param value value to bind as RouteDocIdBind
     */
    public void setRouteDocIdBind(String value) {
        setNamedWhereClauseParam("RouteDocIdBind", value);
    }

    /**
     * Returns the bind variable value for deptPointBind.
     * @return bind variable value for deptPointBind
     */
    public String getdeptPointBind() {
        return (String) getNamedWhereClauseParam("deptPointBind");
    }

    /**
     * Sets <code>value</code> for bind variable deptPointBind.
     * @param value value to bind as deptPointBind
     */
    public void setdeptPointBind(String value) {
        setNamedWhereClauseParam("deptPointBind", value);
    }

    /**
     * Returns the bind variable value for arrPointBind.
     * @return bind variable value for arrPointBind
     */
    public String getarrPointBind() {
        return (String) getNamedWhereClauseParam("arrPointBind");
    }

    /**
     * Sets <code>value</code> for bind variable arrPointBind.
     * @param value value to bind as arrPointBind
     */
    public void setarrPointBind(String value) {
        setNamedWhereClauseParam("arrPointBind", value);
    }
    @Override
    public void applyViewCriteria(ViewCriteria viewCriteria, boolean b) {
        super.applyViewCriteria(supressStartsWithClauseForLov(viewCriteria), b);
    }


    public ViewCriteria supressStartsWithClauseForLov(ViewCriteria vc) {
        if (vc != null && vc.getName().contains("__lov__filterlist__vcr__")) {
            ViewCriteriaRow currentRow = (ViewCriteriaRow) vc.getCurrentRow();
            if (currentRow != null) {
                List criteriaItems = currentRow.getCriteriaItems();
                for (int i = 0; i < criteriaItems.size(); i++) {
                    ViewCriteriaItem object = (ViewCriteriaItem) criteriaItems.get(i);
                    if (object != null) {
                        
                        if ("STARTSWITH".equals(object.getOperator())) {
                            object.setOperator("CONTAINS");
                        }
                    }
                }
            }
        }
        return vc;
    }
}

