package trnpbulkvhclreqapp.model.views;

import java.util.List;

import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaItem;
import oracle.jbo.ViewCriteriaRow;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 02 17:42:13 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SearchParamDualVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SearchParamDualVOImpl() {
    }
    

}

