package trnpbulkvhclreqapp.model.views;

import java.math.BigDecimal;
import java.math.BigInteger;

import java.sql.Timestamp;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewRowImpl;

import trnpbulkvhclreqapp.model.entities.SlsSoDlvSchdlEOImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jul 12 19:15:21 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SlsSoDlvSchdlVORowImpl extends ViewRowImpl {

    public static final int ENTITY_SLSSODLVSCHDLEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        AtcId,
        AvlQty,
        BalQty,
        CldId,
        CnslFlg,
        CntQty,
        DlvAddsId,
        DlvDt,
        DlvMode,
        DlvQty,
        DlvQtyBs,
        DlvSchdlNo,
        DlvTime,
        DlvType,
        DocId,
        GtcId,
        HoOrgId,
        ItmId,
        ItmSrNo,
        ItmUom,
        ItmUomBs,
        LrBalQty,
        LrTempBalQty,
        OldBalQty,
        OrgId,
        PiBalQty,
        PlnQty,
        PoDocId,
        PrjId,
        Remarks,
        ReturnQty,
        RsrvQty,
        ShipFlg,
        SlocId,
        TlrncQtyType,
        TlrncQtyVal,
        TmpBalQty,
        TotQty,
        UomConvFctr,
        UsrIdCreate,
        UsrIdCreateDt,
        UsrIdMod,
        UsrIdModDt,
        WhId;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int ATCID = AttributesEnum.AtcId.index();
    public static final int AVLQTY = AttributesEnum.AvlQty.index();
    public static final int BALQTY = AttributesEnum.BalQty.index();
    public static final int CLDID = AttributesEnum.CldId.index();
    public static final int CNSLFLG = AttributesEnum.CnslFlg.index();
    public static final int CNTQTY = AttributesEnum.CntQty.index();
    public static final int DLVADDSID = AttributesEnum.DlvAddsId.index();
    public static final int DLVDT = AttributesEnum.DlvDt.index();
    public static final int DLVMODE = AttributesEnum.DlvMode.index();
    public static final int DLVQTY = AttributesEnum.DlvQty.index();
    public static final int DLVQTYBS = AttributesEnum.DlvQtyBs.index();
    public static final int DLVSCHDLNO = AttributesEnum.DlvSchdlNo.index();
    public static final int DLVTIME = AttributesEnum.DlvTime.index();
    public static final int DLVTYPE = AttributesEnum.DlvType.index();
    public static final int DOCID = AttributesEnum.DocId.index();
    public static final int GTCID = AttributesEnum.GtcId.index();
    public static final int HOORGID = AttributesEnum.HoOrgId.index();
    public static final int ITMID = AttributesEnum.ItmId.index();
    public static final int ITMSRNO = AttributesEnum.ItmSrNo.index();
    public static final int ITMUOM = AttributesEnum.ItmUom.index();
    public static final int ITMUOMBS = AttributesEnum.ItmUomBs.index();
    public static final int LRBALQTY = AttributesEnum.LrBalQty.index();
    public static final int LRTEMPBALQTY = AttributesEnum.LrTempBalQty.index();
    public static final int OLDBALQTY = AttributesEnum.OldBalQty.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int PIBALQTY = AttributesEnum.PiBalQty.index();
    public static final int PLNQTY = AttributesEnum.PlnQty.index();
    public static final int PODOCID = AttributesEnum.PoDocId.index();
    public static final int PRJID = AttributesEnum.PrjId.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int RETURNQTY = AttributesEnum.ReturnQty.index();
    public static final int RSRVQTY = AttributesEnum.RsrvQty.index();
    public static final int SHIPFLG = AttributesEnum.ShipFlg.index();
    public static final int SLOCID = AttributesEnum.SlocId.index();
    public static final int TLRNCQTYTYPE = AttributesEnum.TlrncQtyType.index();
    public static final int TLRNCQTYVAL = AttributesEnum.TlrncQtyVal.index();
    public static final int TMPBALQTY = AttributesEnum.TmpBalQty.index();
    public static final int TOTQTY = AttributesEnum.TotQty.index();
    public static final int UOMCONVFCTR = AttributesEnum.UomConvFctr.index();
    public static final int USRIDCREATE = AttributesEnum.UsrIdCreate.index();
    public static final int USRIDCREATEDT = AttributesEnum.UsrIdCreateDt.index();
    public static final int USRIDMOD = AttributesEnum.UsrIdMod.index();
    public static final int USRIDMODDT = AttributesEnum.UsrIdModDt.index();
    public static final int WHID = AttributesEnum.WhId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SlsSoDlvSchdlVORowImpl() {
    }

    /**
     * Gets SlsSoDlvSchdlEO entity object.
     * @return the SlsSoDlvSchdlEO
     */
    public SlsSoDlvSchdlEOImpl getSlsSoDlvSchdlEO() {
        return (SlsSoDlvSchdlEOImpl) getEntity(ENTITY_SLSSODLVSCHDLEO);
    }

    /**
     * Gets the attribute value for ATC_ID using the alias name AtcId.
     * @return the ATC_ID
     */
    public String getAtcId() {
        return (String) getAttributeInternal(ATCID);
    }

    /**
     * Sets <code>value</code> as attribute value for ATC_ID using the alias name AtcId.
     * @param value value to set the ATC_ID
     */
    public void setAtcId(String value) {
        setAttributeInternal(ATCID, value);
    }

    /**
     * Gets the attribute value for AVL_QTY using the alias name AvlQty.
     * @return the AVL_QTY
     */
    public oracle.jbo.domain.Number getAvlQty() {
        return (oracle.jbo.domain.Number) getAttributeInternal(AVLQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for AVL_QTY using the alias name AvlQty.
     * @param value value to set the AVL_QTY
     */
    public void setAvlQty(oracle.jbo.domain.Number value) {
        setAttributeInternal(AVLQTY, value);
    }

    /**
     * Gets the attribute value for BAL_QTY using the alias name BalQty.
     * @return the BAL_QTY
     */
    public oracle.jbo.domain.Number getBalQty() {
        return (oracle.jbo.domain.Number) getAttributeInternal(BALQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for BAL_QTY using the alias name BalQty.
     * @param value value to set the BAL_QTY
     */
    public void setBalQty(oracle.jbo.domain.Number value) {
        setAttributeInternal(BALQTY, value);
    }

    /**
     * Gets the attribute value for CLD_ID using the alias name CldId.
     * @return the CLD_ID
     */
    public String getCldId() {
        return (String) getAttributeInternal(CLDID);
    }

    /**
     * Sets <code>value</code> as attribute value for CLD_ID using the alias name CldId.
     * @param value value to set the CLD_ID
     */
    public void setCldId(String value) {
        setAttributeInternal(CLDID, value);
    }

    /**
     * Gets the attribute value for CNSL_FLG using the alias name CnslFlg.
     * @return the CNSL_FLG
     */
    public String getCnslFlg() {
        return (String) getAttributeInternal(CNSLFLG);
    }

    /**
     * Sets <code>value</code> as attribute value for CNSL_FLG using the alias name CnslFlg.
     * @param value value to set the CNSL_FLG
     */
    public void setCnslFlg(String value) {
        setAttributeInternal(CNSLFLG, value);
    }

    /**
     * Gets the attribute value for CNT_QTY using the alias name CntQty.
     * @return the CNT_QTY
     */
    public oracle.jbo.domain.Number getCntQty() {
        return (oracle.jbo.domain.Number) getAttributeInternal(CNTQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for CNT_QTY using the alias name CntQty.
     * @param value value to set the CNT_QTY
     */
    public void setCntQty(oracle.jbo.domain.Number value) {
        setAttributeInternal(CNTQTY, value);
    }

    /**
     * Gets the attribute value for DLV_ADDS_ID using the alias name DlvAddsId.
     * @return the DLV_ADDS_ID
     */
    public String getDlvAddsId() {
        return (String) getAttributeInternal(DLVADDSID);
    }

    /**
     * Sets <code>value</code> as attribute value for DLV_ADDS_ID using the alias name DlvAddsId.
     * @param value value to set the DLV_ADDS_ID
     */
    public void setDlvAddsId(String value) {
        setAttributeInternal(DLVADDSID, value);
    }

    /**
     * Gets the attribute value for DLV_DT using the alias name DlvDt.
     * @return the DLV_DT
     */
    public Timestamp getDlvDt() {
        return (Timestamp) getAttributeInternal(DLVDT);
    }

    /**
     * Sets <code>value</code> as attribute value for DLV_DT using the alias name DlvDt.
     * @param value value to set the DLV_DT
     */
    public void setDlvDt(Timestamp value) {
        setAttributeInternal(DLVDT, value);
    }

    /**
     * Gets the attribute value for DLV_MODE using the alias name DlvMode.
     * @return the DLV_MODE
     */
    public Integer getDlvMode() {
        return (Integer) getAttributeInternal(DLVMODE);
    }

    /**
     * Sets <code>value</code> as attribute value for DLV_MODE using the alias name DlvMode.
     * @param value value to set the DLV_MODE
     */
    public void setDlvMode(Integer value) {
        setAttributeInternal(DLVMODE, value);
    }

    /**
     * Gets the attribute value for DLV_QTY using the alias name DlvQty.
     * @return the DLV_QTY
     */
    public oracle.jbo.domain.Number getDlvQty() {
        return (oracle.jbo.domain.Number) getAttributeInternal(DLVQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for DLV_QTY using the alias name DlvQty.
     * @param value value to set the DLV_QTY
     */
    public void setDlvQty(oracle.jbo.domain.Number value) {
        setAttributeInternal(DLVQTY, value);
    }

    /**
     * Gets the attribute value for DLV_QTY_BS using the alias name DlvQtyBs.
     * @return the DLV_QTY_BS
     */
    public oracle.jbo.domain.Number getDlvQtyBs() {
        return (oracle.jbo.domain.Number) getAttributeInternal(DLVQTYBS);
    }

    /**
     * Sets <code>value</code> as attribute value for DLV_QTY_BS using the alias name DlvQtyBs.
     * @param value value to set the DLV_QTY_BS
     */
    public void setDlvQtyBs(oracle.jbo.domain.Number value) {
        setAttributeInternal(DLVQTYBS, value);
    }

    /**
     * Gets the attribute value for DLV_SCHDL_NO using the alias name DlvSchdlNo.
     * @return the DLV_SCHDL_NO
     */
    public Integer getDlvSchdlNo() {
        return (Integer) getAttributeInternal(DLVSCHDLNO);
    }

    /**
     * Sets <code>value</code> as attribute value for DLV_SCHDL_NO using the alias name DlvSchdlNo.
     * @param value value to set the DLV_SCHDL_NO
     */
    public void setDlvSchdlNo(Integer value) {
        setAttributeInternal(DLVSCHDLNO, value);
    }

    /**
     * Gets the attribute value for DLV_TIME using the alias name DlvTime.
     * @return the DLV_TIME
     */
    public String getDlvTime() {
        return (String) getAttributeInternal(DLVTIME);
    }

    /**
     * Sets <code>value</code> as attribute value for DLV_TIME using the alias name DlvTime.
     * @param value value to set the DLV_TIME
     */
    public void setDlvTime(String value) {
        setAttributeInternal(DLVTIME, value);
    }

    /**
     * Gets the attribute value for DLV_TYPE using the alias name DlvType.
     * @return the DLV_TYPE
     */
    public Integer getDlvType() {
        return (Integer) getAttributeInternal(DLVTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for DLV_TYPE using the alias name DlvType.
     * @param value value to set the DLV_TYPE
     */
    public void setDlvType(Integer value) {
        setAttributeInternal(DLVTYPE, value);
    }

    /**
     * Gets the attribute value for DOC_ID using the alias name DocId.
     * @return the DOC_ID
     */
    public String getDocId() {
        return (String) getAttributeInternal(DOCID);
    }

    /**
     * Sets <code>value</code> as attribute value for DOC_ID using the alias name DocId.
     * @param value value to set the DOC_ID
     */
    public void setDocId(String value) {
        setAttributeInternal(DOCID, value);
    }

    /**
     * Gets the attribute value for GTC_ID using the alias name GtcId.
     * @return the GTC_ID
     */
    public String getGtcId() {
        return (String) getAttributeInternal(GTCID);
    }

    /**
     * Sets <code>value</code> as attribute value for GTC_ID using the alias name GtcId.
     * @param value value to set the GTC_ID
     */
    public void setGtcId(String value) {
        setAttributeInternal(GTCID, value);
    }

    /**
     * Gets the attribute value for HO_ORG_ID using the alias name HoOrgId.
     * @return the HO_ORG_ID
     */
    public String getHoOrgId() {
        return (String) getAttributeInternal(HOORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for HO_ORG_ID using the alias name HoOrgId.
     * @param value value to set the HO_ORG_ID
     */
    public void setHoOrgId(String value) {
        setAttributeInternal(HOORGID, value);
    }

    /**
     * Gets the attribute value for ITM_ID using the alias name ItmId.
     * @return the ITM_ID
     */
    public String getItmId() {
        return (String) getAttributeInternal(ITMID);
    }

    /**
     * Sets <code>value</code> as attribute value for ITM_ID using the alias name ItmId.
     * @param value value to set the ITM_ID
     */
    public void setItmId(String value) {
        setAttributeInternal(ITMID, value);
    }

    /**
     * Gets the attribute value for ITM_SR_NO using the alias name ItmSrNo.
     * @return the ITM_SR_NO
     */
    public Long getItmSrNo() {
        return (Long) getAttributeInternal(ITMSRNO);
    }

    /**
     * Sets <code>value</code> as attribute value for ITM_SR_NO using the alias name ItmSrNo.
     * @param value value to set the ITM_SR_NO
     */
    public void setItmSrNo(Long value) {
        setAttributeInternal(ITMSRNO, value);
    }

    /**
     * Gets the attribute value for ITM_UOM using the alias name ItmUom.
     * @return the ITM_UOM
     */
    public String getItmUom() {
        return (String) getAttributeInternal(ITMUOM);
    }

    /**
     * Sets <code>value</code> as attribute value for ITM_UOM using the alias name ItmUom.
     * @param value value to set the ITM_UOM
     */
    public void setItmUom(String value) {
        setAttributeInternal(ITMUOM, value);
    }

    /**
     * Gets the attribute value for ITM_UOM_BS using the alias name ItmUomBs.
     * @return the ITM_UOM_BS
     */
    public String getItmUomBs() {
        return (String) getAttributeInternal(ITMUOMBS);
    }

    /**
     * Sets <code>value</code> as attribute value for ITM_UOM_BS using the alias name ItmUomBs.
     * @param value value to set the ITM_UOM_BS
     */
    public void setItmUomBs(String value) {
        setAttributeInternal(ITMUOMBS, value);
    }

    /**
     * Gets the attribute value for LR_BAL_QTY using the alias name LrBalQty.
     * @return the LR_BAL_QTY
     */
    public oracle.jbo.domain.Number getLrBalQty() {
        return (oracle.jbo.domain.Number) getAttributeInternal(LRBALQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for LR_BAL_QTY using the alias name LrBalQty.
     * @param value value to set the LR_BAL_QTY
     */
    public void setLrBalQty(oracle.jbo.domain.Number value) {
        setAttributeInternal(LRBALQTY, value);
    }

    /**
     * Gets the attribute value for LR_TEMP_BAL_QTY using the alias name LrTempBalQty.
     * @return the LR_TEMP_BAL_QTY
     */
    public oracle.jbo.domain.Number getLrTempBalQty() {
        return (oracle.jbo.domain.Number) getAttributeInternal(LRTEMPBALQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for LR_TEMP_BAL_QTY using the alias name LrTempBalQty.
     * @param value value to set the LR_TEMP_BAL_QTY
     */
    public void setLrTempBalQty(oracle.jbo.domain.Number value) {
        setAttributeInternal(LRTEMPBALQTY, value);
    }

    /**
     * Gets the attribute value for OLD_BAL_QTY using the alias name OldBalQty.
     * @return the OLD_BAL_QTY
     */
    public oracle.jbo.domain.Number getOldBalQty() {
        return (oracle.jbo.domain.Number) getAttributeInternal(OLDBALQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for OLD_BAL_QTY using the alias name OldBalQty.
     * @param value value to set the OLD_BAL_QTY
     */
    public void setOldBalQty(oracle.jbo.domain.Number value) {
        setAttributeInternal(OLDBALQTY, value);
    }

    /**
     * Gets the attribute value for ORG_ID using the alias name OrgId.
     * @return the ORG_ID
     */
    public String getOrgId() {
        return (String) getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_ID using the alias name OrgId.
     * @param value value to set the ORG_ID
     */
    public void setOrgId(String value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for PI_BAL_QTY using the alias name PiBalQty.
     * @return the PI_BAL_QTY
     */
    public oracle.jbo.domain.Number getPiBalQty() {
        return (oracle.jbo.domain.Number) getAttributeInternal(PIBALQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for PI_BAL_QTY using the alias name PiBalQty.
     * @param value value to set the PI_BAL_QTY
     */
    public void setPiBalQty(oracle.jbo.domain.Number value) {
        setAttributeInternal(PIBALQTY, value);
    }

    /**
     * Gets the attribute value for PLN_QTY using the alias name PlnQty.
     * @return the PLN_QTY
     */
    public oracle.jbo.domain.Number getPlnQty() {
        return (oracle.jbo.domain.Number) getAttributeInternal(PLNQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for PLN_QTY using the alias name PlnQty.
     * @param value value to set the PLN_QTY
     */
    public void setPlnQty(oracle.jbo.domain.Number value) {
        setAttributeInternal(PLNQTY, value);
    }

    /**
     * Gets the attribute value for PO_DOC_ID using the alias name PoDocId.
     * @return the PO_DOC_ID
     */
    public String getPoDocId() {
        return (String) getAttributeInternal(PODOCID);
    }

    /**
     * Sets <code>value</code> as attribute value for PO_DOC_ID using the alias name PoDocId.
     * @param value value to set the PO_DOC_ID
     */
    public void setPoDocId(String value) {
        setAttributeInternal(PODOCID, value);
    }

    /**
     * Gets the attribute value for PRJ_ID using the alias name PrjId.
     * @return the PRJ_ID
     */
    public String getPrjId() {
        return (String) getAttributeInternal(PRJID);
    }

    /**
     * Sets <code>value</code> as attribute value for PRJ_ID using the alias name PrjId.
     * @param value value to set the PRJ_ID
     */
    public void setPrjId(String value) {
        setAttributeInternal(PRJID, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for RETURN_QTY using the alias name ReturnQty.
     * @return the RETURN_QTY
     */
    public oracle.jbo.domain.Number getReturnQty() {
        return (oracle.jbo.domain.Number) getAttributeInternal(RETURNQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for RETURN_QTY using the alias name ReturnQty.
     * @param value value to set the RETURN_QTY
     */
    public void setReturnQty(oracle.jbo.domain.Number value) {
        setAttributeInternal(RETURNQTY, value);
    }

    /**
     * Gets the attribute value for RSRV_QTY using the alias name RsrvQty.
     * @return the RSRV_QTY
     */
    public oracle.jbo.domain.Number getRsrvQty() {
        return (oracle.jbo.domain.Number) getAttributeInternal(RSRVQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for RSRV_QTY using the alias name RsrvQty.
     * @param value value to set the RSRV_QTY
     */
    public void setRsrvQty(oracle.jbo.domain.Number value) {
        setAttributeInternal(RSRVQTY, value);
    }

    /**
     * Gets the attribute value for SHIP_FLG using the alias name ShipFlg.
     * @return the SHIP_FLG
     */
    public String getShipFlg() {
        return (String) getAttributeInternal(SHIPFLG);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIP_FLG using the alias name ShipFlg.
     * @param value value to set the SHIP_FLG
     */
    public void setShipFlg(String value) {
        setAttributeInternal(SHIPFLG, value);
    }

    /**
     * Gets the attribute value for SLOC_ID using the alias name SlocId.
     * @return the SLOC_ID
     */
    public Integer getSlocId() {
        return (Integer) getAttributeInternal(SLOCID);
    }

    /**
     * Sets <code>value</code> as attribute value for SLOC_ID using the alias name SlocId.
     * @param value value to set the SLOC_ID
     */
    public void setSlocId(Integer value) {
        setAttributeInternal(SLOCID, value);
    }

    /**
     * Gets the attribute value for TLRNC_QTY_TYPE using the alias name TlrncQtyType.
     * @return the TLRNC_QTY_TYPE
     */
    public String getTlrncQtyType() {
        return (String) getAttributeInternal(TLRNCQTYTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for TLRNC_QTY_TYPE using the alias name TlrncQtyType.
     * @param value value to set the TLRNC_QTY_TYPE
     */
    public void setTlrncQtyType(String value) {
        setAttributeInternal(TLRNCQTYTYPE, value);
    }

    /**
     * Gets the attribute value for TLRNC_QTY_VAL using the alias name TlrncQtyVal.
     * @return the TLRNC_QTY_VAL
     */
    public oracle.jbo.domain.Number getTlrncQtyVal() {
        return (oracle.jbo.domain.Number) getAttributeInternal(TLRNCQTYVAL);
    }

    /**
     * Sets <code>value</code> as attribute value for TLRNC_QTY_VAL using the alias name TlrncQtyVal.
     * @param value value to set the TLRNC_QTY_VAL
     */
    public void setTlrncQtyVal(oracle.jbo.domain.Number value) {
        setAttributeInternal(TLRNCQTYVAL, value);
    }

    /**
     * Gets the attribute value for TMP_BAL_QTY using the alias name TmpBalQty.
     * @return the TMP_BAL_QTY
     */
    public oracle.jbo.domain.Number getTmpBalQty() {
        return (oracle.jbo.domain.Number) getAttributeInternal(TMPBALQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for TMP_BAL_QTY using the alias name TmpBalQty.
     * @param value value to set the TMP_BAL_QTY
     */
    public void setTmpBalQty(oracle.jbo.domain.Number value) {
        setAttributeInternal(TMPBALQTY, value);
    }

    /**
     * Gets the attribute value for TOT_QTY using the alias name TotQty.
     * @return the TOT_QTY
     */
    public oracle.jbo.domain.Number getTotQty() {
        return (oracle.jbo.domain.Number) getAttributeInternal(TOTQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for TOT_QTY using the alias name TotQty.
     * @param value value to set the TOT_QTY
     */
    public void setTotQty(oracle.jbo.domain.Number value) {
        setAttributeInternal(TOTQTY, value);
    }

    /**
     * Gets the attribute value for UOM_CONV_FCTR using the alias name UomConvFctr.
     * @return the UOM_CONV_FCTR
     */
    public Number getUomConvFctr() {
        return (Number) getAttributeInternal(UOMCONVFCTR);
    }

    /**
     * Sets <code>value</code> as attribute value for UOM_CONV_FCTR using the alias name UomConvFctr.
     * @param value value to set the UOM_CONV_FCTR
     */
    public void setUomConvFctr(Number value) {
        setAttributeInternal(UOMCONVFCTR, value);
    }

    /**
     * Gets the attribute value for USR_ID_CREATE using the alias name UsrIdCreate.
     * @return the USR_ID_CREATE
     */
    public Integer getUsrIdCreate() {
        return (Integer) getAttributeInternal(USRIDCREATE);
    }

    /**
     * Sets <code>value</code> as attribute value for USR_ID_CREATE using the alias name UsrIdCreate.
     * @param value value to set the USR_ID_CREATE
     */
    public void setUsrIdCreate(Integer value) {
        setAttributeInternal(USRIDCREATE, value);
    }

    /**
     * Gets the attribute value for USR_ID_CREATE_DT using the alias name UsrIdCreateDt.
     * @return the USR_ID_CREATE_DT
     */
    public Timestamp getUsrIdCreateDt() {
        return (Timestamp) getAttributeInternal(USRIDCREATEDT);
    }

    /**
     * Sets <code>value</code> as attribute value for USR_ID_CREATE_DT using the alias name UsrIdCreateDt.
     * @param value value to set the USR_ID_CREATE_DT
     */
    public void setUsrIdCreateDt(Timestamp value) {
        setAttributeInternal(USRIDCREATEDT, value);
    }

    /**
     * Gets the attribute value for USR_ID_MOD using the alias name UsrIdMod.
     * @return the USR_ID_MOD
     */
    public Integer getUsrIdMod() {
        return (Integer) getAttributeInternal(USRIDMOD);
    }

    /**
     * Sets <code>value</code> as attribute value for USR_ID_MOD using the alias name UsrIdMod.
     * @param value value to set the USR_ID_MOD
     */
    public void setUsrIdMod(Integer value) {
        setAttributeInternal(USRIDMOD, value);
    }

    /**
     * Gets the attribute value for USR_ID_MOD_DT using the alias name UsrIdModDt.
     * @return the USR_ID_MOD_DT
     */
    public Timestamp getUsrIdModDt() {
        return (Timestamp) getAttributeInternal(USRIDMODDT);
    }

    /**
     * Sets <code>value</code> as attribute value for USR_ID_MOD_DT using the alias name UsrIdModDt.
     * @param value value to set the USR_ID_MOD_DT
     */
    public void setUsrIdModDt(Timestamp value) {
        setAttributeInternal(USRIDMODDT, value);
    }

    /**
     * Gets the attribute value for WH_ID using the alias name WhId.
     * @return the WH_ID
     */
    public String getWhId() {
        return (String) getAttributeInternal(WHID);
    }

    /**
     * Sets <code>value</code> as attribute value for WH_ID using the alias name WhId.
     * @param value value to set the WH_ID
     */
    public void setWhId(String value) {
        setAttributeInternal(WHID, value);
    }
}

