package trnpbulkvhclreqapp.model.views;

import adf.utils.bean.StaticValue;
import adf.utils.ebiz.EbizParams;
import adf.utils.ebiz.EbizParamsAPPUtils;

import java.math.BigDecimal;
import java.math.BigInteger;

import java.sql.Timestamp;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;

import trnpbulkvhclreqapp.model.entities.SlsTrnpBulkVrEOImpl;
import trnpbulkvhclreqapp.model.services.TrnpBulkVhclReqAMImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jul 06 12:57:41 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SlsTrnpBulkVrVORowImpl extends ViewRowImpl
{


  public static final int ENTITY_SLSTRNPBULKVREO = 0;

  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
    public enum AttributesEnum {
    CldId,
    DispId,
    DocDt,
    DocId,
    DrftDispId,
    HoOrgId,
    OrgId,
    SlocId,
    UsrIdCreate,
    UsrIdCreateDt,
    UsrIdMod,
    UsrIdModDt,
    TransSoIdSearch,
    TransCustSearch,
    TransItemSearch,
    TransSoDocId,
    TransEoId,
    TransItemId,
    TransTotalGrossWt,
    TransVhclType,
    TransVhclTypeId,
    TransReqType,
    TransReqTypeId,
    TransRouteName,
    TransRouteId,
    TransLocNm,
    TransLocId,
    TransUsrNm,
    LrStatus,
    FyId,
    TransStatusNm,
    Freeze,
    CurrIdSp,
    CurrConvFctr,
    TransCurrDesc,
    TransStDt,
    TransEndDt,
    TransLocNmSrch,
    TransLocIdSearch,
    TransLrStatus,
    TransGLBLLangid,
    DocTypId,
    TransDocSwitch,
    TransRmaDocId,
    TransDocTyp,
    TransTotalBalanceWt,
    VhclNo,
    VrMode,
    TransVrMode,
    TransLrDtls,
    TransTotalBundle,
    TransTotalAmt,
    TransGroupId,
    TransGroupNm,
    CageId,
    TransCageName,
    TransTotalCbmVal,
    AmdNo,
    TransTrfDocId,
    TransCreateType,
    TransBulkTrfOrdDocId,
    TrfType,
    SlsTrnpBulkVrSrc,
    SlsTrnpBulkVrItm,
    LovSoIdVO1,
    LOVCustNameVO1,
    LOVItemNmVO1,
    LOVVhclTypeVO1,
    LOVReqTypVO1,
    LOVRouteVO1,
    LOVLocationIdVO1,
    LOVCurrIdVO1,
    LovSalesRegnVO1,
    LOVSlsRegionVO1,
    LOVStatusVO1,
    LovDocumentTypeVO1,
    LovRmaVO1,
    LovDocumentTypeVO2,
    LovGroupNmVO1,
    LovCageVO1,
    LovTrfIdVO1,
    LovBulkTrfOrdVO1,
    LovTrfType1;
    static AttributesEnum[] vals = null;
    ;
    private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


  public static final int CLDID = AttributesEnum.CldId.index();
  public static final int DISPID = AttributesEnum.DispId.index();
  public static final int DOCDT = AttributesEnum.DocDt.index();
  public static final int DOCID = AttributesEnum.DocId.index();
  public static final int DRFTDISPID = AttributesEnum.DrftDispId.index();
  public static final int HOORGID = AttributesEnum.HoOrgId.index();
  public static final int ORGID = AttributesEnum.OrgId.index();
  public static final int SLOCID = AttributesEnum.SlocId.index();
  public static final int USRIDCREATE = AttributesEnum.UsrIdCreate.index();
  public static final int USRIDCREATEDT = AttributesEnum.UsrIdCreateDt.index();
  public static final int USRIDMOD = AttributesEnum.UsrIdMod.index();
  public static final int USRIDMODDT = AttributesEnum.UsrIdModDt.index();
  public static final int TRANSSOIDSEARCH = AttributesEnum.TransSoIdSearch.index();
  public static final int TRANSCUSTSEARCH = AttributesEnum.TransCustSearch.index();
  public static final int TRANSITEMSEARCH = AttributesEnum.TransItemSearch.index();
  public static final int TRANSSODOCID = AttributesEnum.TransSoDocId.index();
  public static final int TRANSEOID = AttributesEnum.TransEoId.index();
  public static final int TRANSITEMID = AttributesEnum.TransItemId.index();
  public static final int TRANSTOTALGROSSWT = AttributesEnum.TransTotalGrossWt.index();
  public static final int TRANSVHCLTYPE = AttributesEnum.TransVhclType.index();
  public static final int TRANSVHCLTYPEID = AttributesEnum.TransVhclTypeId.index();
  public static final int TRANSREQTYPE = AttributesEnum.TransReqType.index();
  public static final int TRANSREQTYPEID = AttributesEnum.TransReqTypeId.index();
  public static final int TRANSROUTENAME = AttributesEnum.TransRouteName.index();
  public static final int TRANSROUTEID = AttributesEnum.TransRouteId.index();
  public static final int TRANSLOCNM = AttributesEnum.TransLocNm.index();
  public static final int TRANSLOCID = AttributesEnum.TransLocId.index();
  public static final int TRANSUSRNM = AttributesEnum.TransUsrNm.index();
  public static final int LRSTATUS = AttributesEnum.LrStatus.index();
  public static final int FYID = AttributesEnum.FyId.index();
  public static final int TRANSSTATUSNM = AttributesEnum.TransStatusNm.index();
  public static final int FREEZE = AttributesEnum.Freeze.index();
  public static final int CURRIDSP = AttributesEnum.CurrIdSp.index();
  public static final int CURRCONVFCTR = AttributesEnum.CurrConvFctr.index();
  public static final int TRANSCURRDESC = AttributesEnum.TransCurrDesc.index();
  public static final int TRANSSTDT = AttributesEnum.TransStDt.index();
  public static final int TRANSENDDT = AttributesEnum.TransEndDt.index();
  public static final int TRANSLOCNMSRCH = AttributesEnum.TransLocNmSrch.index();
  public static final int TRANSLOCIDSEARCH = AttributesEnum.TransLocIdSearch.index();
  public static final int TRANSLRSTATUS = AttributesEnum.TransLrStatus.index();
  public static final int TRANSGLBLLANGID = AttributesEnum.TransGLBLLangid.index();
  public static final int DOCTYPID = AttributesEnum.DocTypId.index();
  public static final int TRANSDOCSWITCH = AttributesEnum.TransDocSwitch.index();
  public static final int TRANSRMADOCID = AttributesEnum.TransRmaDocId.index();
  public static final int TRANSDOCTYP = AttributesEnum.TransDocTyp.index();
  public static final int TRANSTOTALBALANCEWT = AttributesEnum.TransTotalBalanceWt.index();
  public static final int VHCLNO = AttributesEnum.VhclNo.index();
  public static final int VRMODE = AttributesEnum.VrMode.index();
  public static final int TRANSVRMODE = AttributesEnum.TransVrMode.index();
  public static final int TRANSLRDTLS = AttributesEnum.TransLrDtls.index();
  public static final int TRANSTOTALBUNDLE = AttributesEnum.TransTotalBundle.index();
  public static final int TRANSTOTALAMT = AttributesEnum.TransTotalAmt.index();
  public static final int TRANSGROUPID = AttributesEnum.TransGroupId.index();
  public static final int TRANSGROUPNM = AttributesEnum.TransGroupNm.index();
  public static final int CAGEID = AttributesEnum.CageId.index();
  public static final int TRANSCAGENAME = AttributesEnum.TransCageName.index();
  public static final int TRANSTOTALCBMVAL = AttributesEnum.TransTotalCbmVal.index();
  public static final int AMDNO = AttributesEnum.AmdNo.index();
  public static final int TRANSTRFDOCID = AttributesEnum.TransTrfDocId.index();
  public static final int TRANSCREATETYPE = AttributesEnum.TransCreateType.index();
  public static final int TRANSBULKTRFORDDOCID = AttributesEnum.TransBulkTrfOrdDocId.index();
  public static final int TRFTYPE = AttributesEnum.TrfType.index();
  public static final int SLSTRNPBULKVRSRC = AttributesEnum.SlsTrnpBulkVrSrc.index();
  public static final int SLSTRNPBULKVRITM = AttributesEnum.SlsTrnpBulkVrItm.index();
  public static final int LOVSOIDVO1 = AttributesEnum.LovSoIdVO1.index();
  public static final int LOVCUSTNAMEVO1 = AttributesEnum.LOVCustNameVO1.index();
  public static final int LOVITEMNMVO1 = AttributesEnum.LOVItemNmVO1.index();
  public static final int LOVVHCLTYPEVO1 = AttributesEnum.LOVVhclTypeVO1.index();
  public static final int LOVREQTYPVO1 = AttributesEnum.LOVReqTypVO1.index();
  public static final int LOVROUTEVO1 = AttributesEnum.LOVRouteVO1.index();
  public static final int LOVLOCATIONIDVO1 = AttributesEnum.LOVLocationIdVO1.index();
  public static final int LOVCURRIDVO1 = AttributesEnum.LOVCurrIdVO1.index();
  public static final int LOVSALESREGNVO1 = AttributesEnum.LovSalesRegnVO1.index();
  public static final int LOVSLSREGIONVO1 = AttributesEnum.LOVSlsRegionVO1.index();
  public static final int LOVSTATUSVO1 = AttributesEnum.LOVStatusVO1.index();
  public static final int LOVDOCUMENTTYPEVO1 = AttributesEnum.LovDocumentTypeVO1.index();
  public static final int LOVRMAVO1 = AttributesEnum.LovRmaVO1.index();
  public static final int LOVDOCUMENTTYPEVO2 = AttributesEnum.LovDocumentTypeVO2.index();
  public static final int LOVGROUPNMVO1 = AttributesEnum.LovGroupNmVO1.index();
  public static final int LOVCAGEVO1 = AttributesEnum.LovCageVO1.index();
  public static final int LOVTRFIDVO1 = AttributesEnum.LovTrfIdVO1.index();
  public static final int LOVBULKTRFORDVO1 = AttributesEnum.LovBulkTrfOrdVO1.index();
  public static final int LOVTRFTYPE1 = AttributesEnum.LovTrfType1.index();

  /**
   * This is the default constructor (do not remove).
   */
    public SlsTrnpBulkVrVORowImpl() {
    }

    /**
     * Gets SlsTrnpBulkVrEO entity object.
     * @return the SlsTrnpBulkVrEO
     */
    public SlsTrnpBulkVrEOImpl getSlsTrnpBulkVrEO() {
        return (SlsTrnpBulkVrEOImpl) getEntity(ENTITY_SLSTRNPBULKVREO);
    }

    /**
     * Gets the attribute value for CLD_ID using the alias name CldId.
     * @return the CLD_ID
     */
    public String getCldId() {
        return (String) getAttributeInternal(CLDID);
    }

    /**
     * Sets <code>value</code> as attribute value for CLD_ID using the alias name CldId.
     * @param value value to set the CLD_ID
     */
    public void setCldId(String value) {
        setAttributeInternal(CLDID, value);
    }

    /**
     * Gets the attribute value for DISP_ID using the alias name DispId.
     * @return the DISP_ID
     */
    public String getDispId() {
        return (String) getAttributeInternal(DISPID);
    }

    /**
     * Sets <code>value</code> as attribute value for DISP_ID using the alias name DispId.
     * @param value value to set the DISP_ID
     */
    public void setDispId(String value) {
        setAttributeInternal(DISPID, value);
    }

    /**
     * Gets the attribute value for DOC_DT using the alias name DocDt.
     * @return the DOC_DT
     */
    public oracle.jbo.domain.Timestamp getDocDt() {
        return (oracle.jbo.domain.Timestamp) getAttributeInternal(DOCDT);
    }

    /**
     * Sets <code>value</code> as attribute value for DOC_DT using the alias name DocDt.
     * @param value value to set the DOC_DT
     */
    public void setDocDt(oracle.jbo.domain.Timestamp value) {
        setAttributeInternal(DOCDT, value);
    }

    /**
     * Gets the attribute value for DOC_ID using the alias name DocId.
     * @return the DOC_ID
     */
    public String getDocId() {
        return (String) getAttributeInternal(DOCID);
    }

    /**
     * Sets <code>value</code> as attribute value for DOC_ID using the alias name DocId.
     * @param value value to set the DOC_ID
     */
    public void setDocId(String value) {
        setAttributeInternal(DOCID, value);
    }

    /**
     * Gets the attribute value for DRFT_DISP_ID using the alias name DrftDispId.
     * @return the DRFT_DISP_ID
     */
    public String getDrftDispId() {
        return (String) getAttributeInternal(DRFTDISPID);
    }

    /**
     * Sets <code>value</code> as attribute value for DRFT_DISP_ID using the alias name DrftDispId.
     * @param value value to set the DRFT_DISP_ID
     */
    public void setDrftDispId(String value) {
        setAttributeInternal(DRFTDISPID, value);
    }

    /**
     * Gets the attribute value for HO_ORG_ID using the alias name HoOrgId.
     * @return the HO_ORG_ID
     */
    public String getHoOrgId() {
        return (String) getAttributeInternal(HOORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for HO_ORG_ID using the alias name HoOrgId.
     * @param value value to set the HO_ORG_ID
     */
    public void setHoOrgId(String value) {
        setAttributeInternal(HOORGID, value);
    }

    /**
     * Gets the attribute value for ORG_ID using the alias name OrgId.
     * @return the ORG_ID
     */
    public String getOrgId() {
        return (String) getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_ID using the alias name OrgId.
     * @param value value to set the ORG_ID
     */
    public void setOrgId(String value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for SLOC_ID using the alias name SlocId.
     * @return the SLOC_ID
     */
    public Integer getSlocId() {
        return (Integer) getAttributeInternal(SLOCID);
    }

    /**
     * Sets <code>value</code> as attribute value for SLOC_ID using the alias name SlocId.
     * @param value value to set the SLOC_ID
     */
    public void setSlocId(Integer value) {
        setAttributeInternal(SLOCID, value);
    }

    /**
     * Gets the attribute value for USR_ID_CREATE using the alias name UsrIdCreate.
     * @return the USR_ID_CREATE
     */
    public Integer getUsrIdCreate() {
        return (Integer) getAttributeInternal(USRIDCREATE);
    }

    /**
     * Sets <code>value</code> as attribute value for USR_ID_CREATE using the alias name UsrIdCreate.
     * @param value value to set the USR_ID_CREATE
     */
    public void setUsrIdCreate(Integer value) {
        setAttributeInternal(USRIDCREATE, value);
    }

    /**
     * Gets the attribute value for USR_ID_CREATE_DT using the alias name UsrIdCreateDt.
     * @return the USR_ID_CREATE_DT
     */
    public oracle.jbo.domain.Timestamp getUsrIdCreateDt() {
        return (oracle.jbo.domain.Timestamp) getAttributeInternal(USRIDCREATEDT);
    }

    /**
     * Sets <code>value</code> as attribute value for USR_ID_CREATE_DT using the alias name UsrIdCreateDt.
     * @param value value to set the USR_ID_CREATE_DT
     */
    public void setUsrIdCreateDt(oracle.jbo.domain.Timestamp value) {
        setAttributeInternal(USRIDCREATEDT, value);
    }

    /**
     * Gets the attribute value for USR_ID_MOD using the alias name UsrIdMod.
     * @return the USR_ID_MOD
     */
    public Integer getUsrIdMod() {
        return (Integer) getAttributeInternal(USRIDMOD);
    }

    /**
     * Sets <code>value</code> as attribute value for USR_ID_MOD using the alias name UsrIdMod.
     * @param value value to set the USR_ID_MOD
     */
    public void setUsrIdMod(Integer value) {
        setAttributeInternal(USRIDMOD, value);
    }

    /**
     * Gets the attribute value for USR_ID_MOD_DT using the alias name UsrIdModDt.
     * @return the USR_ID_MOD_DT
     */
    public oracle.jbo.domain.Timestamp getUsrIdModDt() {
        return (oracle.jbo.domain.Timestamp) getAttributeInternal(USRIDMODDT);
    }

    /**
     * Sets <code>value</code> as attribute value for USR_ID_MOD_DT using the alias name UsrIdModDt.
     * @param value value to set the USR_ID_MOD_DT
     */
    public void setUsrIdModDt(oracle.jbo.domain.Timestamp value) {
        setAttributeInternal(USRIDMODDT, value);
    }
  protected TrnpBulkVhclReqAMImpl getAm() {
        return (TrnpBulkVhclReqAMImpl) this.getDBTransaction().getRootApplicationModule();
    }
    /**
     * Gets the attribute value for the calculated attribute TransSoIdSearch.
     * @return the TransSoIdSearch
     */
    public String getTransSoIdSearch() {
      /**
               * Modified by : Manjeet Singh
               * Modified on : 13-10-2023
               * Remarks :  This below is used for showing Transfer Order document.
               * TMS ID : 128922
            **/
      Integer typeId= new Integer(0);
      ViewObjectImpl vo1 = getAm().getSlsTrnpBulkVrSrc1();
      Row rw=vo1.getCurrentRow();
        typeId = (Integer) this.getDocTypId();
//        System.err.println("_____________Inside getTransSoIdSearch___typeId__________"+typeId);
        if(getAttributeInternal(TRANSSOIDSEARCH)==null && (vo1.getCurrentRow()!=null && rw.getAttribute("SrcDocId")!=null)  && typeId==915)
        {
//        System.err.println("____________________inside rw.getAttribute(\"SrcDocId\")______"+rw.getAttribute("SrcDocId"));
          ViewObjectImpl impl = getAm().getLovTrfDispIdVO1();
          impl.setNamedWhereClauseParam("BindCldId", EbizParams.GLBL_APP_CLD_ID());
          impl.setNamedWhereClauseParam("Binddocid", rw.getAttribute("SrcDocId"));
          impl.setNamedWhereClauseParam("BindOrgId", EbizParams.GLBL_APP_USR_ORG());
          impl.setNamedWhereClauseParam("BindSlocId", EbizParams.GLBL_APP_SERV_LOC());
          impl.setRangeSize(-1);
          impl.executeQuery();
          Row [] r=impl.getAllRowsInRange();
//          System.err.println("_____________Inside getTransSoIdSearch___r.length_________"+r.length);
          if(r.length>0)
          {
            String trfId=(String)r[0].getAttribute("TrfNo");
//            System.err.println("_____________Inside getTransSoIdSearch__typeId__________"+trfId);
            return trfId;
          }
      }
      
      /**   **********************END HERE***********************************    **/
        return (String) getAttributeInternal(TRANSSOIDSEARCH);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransSoIdSearch.
     * @param value value to set the  TransSoIdSearch
     */
    public void setTransSoIdSearch(String value) {
        setAttributeInternal(TRANSSOIDSEARCH, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransCustSearch.
     * @return the TransCustSearch
     */
    public String getTransCustSearch() {
        return (String) getAttributeInternal(TRANSCUSTSEARCH);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransCustSearch.
     * @param value value to set the  TransCustSearch
     */
    public void setTransCustSearch(String value) {
        setAttributeInternal(TRANSCUSTSEARCH, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransItemSearch.
     * @return the TransItemSearch
     */
    public String getTransItemSearch() {
        return (String) getAttributeInternal(TRANSITEMSEARCH);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransItemSearch.
     * @param value value to set the  TransItemSearch
     */
    public void setTransItemSearch(String value) {
        setAttributeInternal(TRANSITEMSEARCH, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransSoDocId.
     * @return the TransSoDocId
     */
    public String getTransSoDocId() {
        return (String) getAttributeInternal(TRANSSODOCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransSoDocId.
     * @param value value to set the  TransSoDocId
     */
    public void setTransSoDocId(String value) {
        setAttributeInternal(TRANSSODOCID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransEoId.
     * @return the TransEoId
     */
    public Integer getTransEoId() {
        return (Integer) getAttributeInternal(TRANSEOID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransEoId.
     * @param value value to set the  TransEoId
     */
    public void setTransEoId(Integer value) {
        setAttributeInternal(TRANSEOID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransItemId.
     * @return the TransItemId
     */
    public String getTransItemId() {
        return (String) getAttributeInternal(TRANSITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransItemId.
     * @param value value to set the  TransItemId
     */
    public void setTransItemId(String value) {
        setAttributeInternal(TRANSITEMID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransTotalGrossWt.
     * @return the TransTotalGrossWt
     */
    public Number getTransTotalGrossWt() {
        if (getAttributeInternal(TRANSTOTALGROSSWT) == null ||
            (Number) getAttributeInternal(TRANSTOTALGROSSWT) == StaticValue.NUMBER_ZERO) {
            setTransTotalGrossWt(this.getAm().getTotalGrossWtVal());
        }
        return (Number) getAttributeInternal(TRANSTOTALGROSSWT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransTotalGrossWt.
     * @param value value to set the  TransTotalGrossWt
     */
    public void setTransTotalGrossWt(Number value) {
        setAttributeInternal(TRANSTOTALGROSSWT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransVhclType.
     * @return the TransVhclType
     */
    public String getTransVhclType() {
        return (String) getAttributeInternal(TRANSVHCLTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransVhclType.
     * @param value value to set the  TransVhclType
     */
    public void setTransVhclType(String value) {
        setAttributeInternal(TRANSVHCLTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransVhclTypeId.
     * @return the TransVhclTypeId
     */
    public Integer getTransVhclTypeId() {
        return (Integer) getAttributeInternal(TRANSVHCLTYPEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransVhclTypeId.
     * @param value value to set the  TransVhclTypeId
     */
    public void setTransVhclTypeId(Integer value) {
        setAttributeInternal(TRANSVHCLTYPEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransReqType.
     * @return the TransReqType
     */
    public String getTransReqType() {
        return (String) getAttributeInternal(TRANSREQTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransReqType.
     * @param value value to set the  TransReqType
     */
    public void setTransReqType(String value) {
        setAttributeInternal(TRANSREQTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransReqTypeId.
     * @return the TransReqTypeId
     */
    public String getTransReqTypeId() {
        return (String) getAttributeInternal(TRANSREQTYPEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransReqTypeId.
     * @param value value to set the  TransReqTypeId
     */
    public void setTransReqTypeId(String value) {
        setAttributeInternal(TRANSREQTYPEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransRouteName.
     * @return the TransRouteName
     */
    public String getTransRouteName() {
        return (String) getAttributeInternal(TRANSROUTENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransRouteName.
     * @param value value to set the  TransRouteName
     */
    public void setTransRouteName(String value) {
        setAttributeInternal(TRANSROUTENAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransRouteId.
     * @return the TransRouteId
     */
    public String getTransRouteId() {
        return (String) getAttributeInternal(TRANSROUTEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransRouteId.
     * @param value value to set the  TransRouteId
     */
    public void setTransRouteId(String value) {
        setAttributeInternal(TRANSROUTEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransLocNm.
     * @return the TransLocNm
     */
    public String getTransLocNm() {
        return (String) getAttributeInternal(TRANSLOCNM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransLocNm.
     * @param value value to set the  TransLocNm
     */
    public void setTransLocNm(String value) {
        setAttributeInternal(TRANSLOCNM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransLocId.
     * @return the TransLocId
     */
    public String getTransLocId() {
        return (String) getAttributeInternal(TRANSLOCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransLocId.
     * @param value value to set the  TransLocId
     */
    public void setTransLocId(String value) {
        setAttributeInternal(TRANSLOCID, value);
    }


    /**
     * @return the Application Module
     */
//    protected TrnpBulkVhclReqAMImpl getAm() {
//        return (TrnpBulkVhclReqAMImpl) this.getDBTransaction().getRootApplicationModule();
//    }

    /**
     * Gets the attribute value for the calculated attribute TransUsrNm.
     * @return the TransUsrNm
     */
    public String getTransUsrNm() {
        if (getAttributeInternal(TRANSUSRNM) == null && this.getUsrIdCreate() != null) {
            String UsrNm = EbizParamsAPPUtils.getUsrDescFrmUsrId(this.getAm(), this.getUsrIdCreate());
            setTransUsrNm(UsrNm);
        }
        return (String) getAttributeInternal(TRANSUSRNM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransUsrNm.
     * @param value value to set the  TransUsrNm
     */
    public void setTransUsrNm(String value) {
        setAttributeInternal(TRANSUSRNM, value);
    }

    /**
     * Gets the attribute value for LR_STATUS using the alias name LrStatus.
     * @return the LR_STATUS
     */
    public Integer getLrStatus() {
        //System.out.println("Lr Status =" + getAttributeInternal(LRSTATUS));
        return (Integer) getAttributeInternal(LRSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for LR_STATUS using the alias name LrStatus.
     * @param value value to set the LR_STATUS
     */
    public void setLrStatus(Integer value) {
        setAttributeInternal(LRSTATUS, value);
    }

    /**
     * Gets the attribute value for FY_ID using the alias name FyId.
     * @return the FY_ID
     */
    public Integer getFyId() {
        return (Integer) getAttributeInternal(FYID);
    }

    /**
     * Sets <code>value</code> as attribute value for FY_ID using the alias name FyId.
     * @param value value to set the FY_ID
     */
    public void setFyId(Integer value) {
        setAttributeInternal(FYID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransStatusNm.
     * @return the TransStatusNm
     */
    public String getTransStatusNm() {
        //        if(getAttributeInternal(TRANSSTATUSNM) == null && this.getLrStatus()!= null){
        //                   String Status = EbizParamsAPPUtils.getDsDescFrmAttId(getAm(), this.getLrStatus());
        //                    setTransStatusNm(Status); }
        return (String) getAttributeInternal(TRANSSTATUSNM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransStatusNm.
     * @param value value to set the  TransStatusNm
     */
    public void setTransStatusNm(String value) {
        setAttributeInternal(TRANSSTATUSNM, value);
    }

    /**
     * Gets the attribute value for FREEZE using the alias name Freeze.
     * @return the FREEZE
     */
    public String getFreeze() {
        return (String) getAttributeInternal(FREEZE);
    }

    /**
     * Sets <code>value</code> as attribute value for FREEZE using the alias name Freeze.
     * @param value value to set the FREEZE
     */
    public void setFreeze(String value) {
        if (value == null) {
            value = "N";
        } else {
            value = "Y";
        }

        setAttributeInternal(FREEZE, value);
    }

    /**
     * Gets the attribute value for CURR_ID_SP using the alias name CurrIdSp.
     * @return the CURR_ID_SP
     */
    public Integer getCurrIdSp() {
        return (Integer) getAttributeInternal(CURRIDSP);
    }

    /**
     * Sets <code>value</code> as attribute value for CURR_ID_SP using the alias name CurrIdSp.
     * @param value value to set the CURR_ID_SP
     */
    public void setCurrIdSp(Integer value) {
        setAttributeInternal(CURRIDSP, value);
    }

    /**
     * Gets the attribute value for CURR_CONV_FCTR using the alias name CurrConvFctr.
     * @return the CURR_CONV_FCTR
     */
    public oracle.jbo.domain.Number getCurrConvFctr() {
        return (oracle.jbo.domain.Number) getAttributeInternal(CURRCONVFCTR);
    }

    /**
     * Sets <code>value</code> as attribute value for CURR_CONV_FCTR using the alias name CurrConvFctr.
     * @param value value to set the CURR_CONV_FCTR
     */
    public void setCurrConvFctr(oracle.jbo.domain.Number value) {
        setAttributeInternal(CURRCONVFCTR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransCurrDesc.
     * @return the TransCurrDesc
     */
    public String getTransCurrDesc() {
       // System.out.println("value of curr" + this.getCurrIdSp());
        if (getAttributeInternal(TRANSCURRDESC) == null && this.getCurrIdSp() != null) {
            ViewObjectImpl vo = this.getAm().getLOVCurrId1();
            vo.setNamedWhereClauseParam("bindCurrDescTxn", this.getCurrIdSp());
            vo.setNamedWhereClauseParam("bindCldId", this.getCldId());
            vo.setNamedWhereClauseParam("bindOrgId", this.getOrgId());
            vo.executeQuery();
            Row[] r = vo.getAllRowsInRange();
            if (r.length > 0) {
                setTransCurrDesc((String) r[0].getAttribute("CurrDescTxn"));
            }
        }
        return (String) getAttributeInternal(TRANSCURRDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransCurrDesc.
     * @param value value to set the  TransCurrDesc
     */
    public void setTransCurrDesc(String value) {
        setAttributeInternal(TRANSCURRDESC, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransStDt.
     * @return the TransStDt
     */
    public Timestamp getTransStDt() {
        return (Timestamp) getAttributeInternal(TRANSSTDT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransStDt.
     * @param value value to set the  TransStDt
     */
    public void setTransStDt(Timestamp value) {
        setAttributeInternal(TRANSSTDT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransEndDt.
     * @return the TransEndDt
     */
    public Timestamp getTransEndDt() {
        return (Timestamp) getAttributeInternal(TRANSENDDT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransEndDt.
     * @param value value to set the  TransEndDt
     */
    public void setTransEndDt(Timestamp value) {
        setAttributeInternal(TRANSENDDT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransLocNmSrch.
     * @return the TransLocNmSrch
     */
    public String getTransLocNmSrch() {
        return (String) getAttributeInternal(TRANSLOCNMSRCH);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransLocNmSrch.
     * @param value value to set the  TransLocNmSrch
     */
    public void setTransLocNmSrch(String value) {
        setAttributeInternal(TRANSLOCNMSRCH, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransLocIdSearch.
     * @return the TransLocIdSearch
     */
    public String getTransLocIdSearch() {
        return (String) getAttributeInternal(TRANSLOCIDSEARCH);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransLocIdSearch.
     * @param value value to set the  TransLocIdSearch
     */
    public void setTransLocIdSearch(String value) {
        setAttributeInternal(TRANSLOCIDSEARCH, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransLrStatus.
     * @return the TransLrStatus
     */
    public String getTransLrStatus() {
        //        if (getAttributeInternal(TRANSLRSTATUS) == null && this.getLrStatus() != null) {
        //            String UsrNm = EbizParamsAPPUtils.getDsDescFrmAttId(this.getAm(), this.getLrStatus());
        //            setTransLrStatus(UsrNm);
        //        }
        return (String) getAttributeInternal(TRANSLRSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransLrStatus.
     * @param value value to set the  TransLrStatus
     */
    public void setTransLrStatus(String value) {
        setAttributeInternal(TRANSLRSTATUS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransGLBLLangid.
     * @return the TransGLBLLangid
     */
    public Integer getTransGLBLLangid() {
        return EbizParams.GLBL_LANG_ID();
        //        return (Integer) getAttributeInternal(TRANSGLBLLANGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransGLBLLangid.
     * @param value value to set the  TransGLBLLangid
     */
    public void setTransGLBLLangid(Integer value) {
        setAttributeInternal(TRANSGLBLLANGID, value);
    }


    /**
     * Gets the attribute value for DOC_TYP_ID using the alias name DocTypId.
     * @return the DOC_TYP_ID
     */
    public Integer getDocTypId() {
//        if (getAttributeInternal(DOCTYPID) == null)
//            System.out.println("docTypeID get =" + getAttributeInternal(DOCTYPID));
        return (Integer) getAttributeInternal(DOCTYPID);

    }

    /**
     * Sets <code>value</code> as attribute value for DOC_TYP_ID using the alias name DocTypId.
     * @param value value to set the DOC_TYP_ID
     */
    public void setDocTypId(Integer value) {
        setAttributeInternal(DOCTYPID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransDocSwitch.
     * @return the TransDocSwitch
     */
    public String getTransDocSwitch() {
        return (String) getAttributeInternal(TRANSDOCSWITCH);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransDocSwitch.
     * @param value value to set the  TransDocSwitch
     */
    public void setTransDocSwitch(String value) {
        setAttributeInternal(TRANSDOCSWITCH, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransRmaDocId.
     * @return the TransRmaDocId
     */
    public String getTransRmaDocId() {
        return (String) getAttributeInternal(TRANSRMADOCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransRmaDocId.
     * @param value value to set the  TransRmaDocId
     */
    public void setTransRmaDocId(String value) {
        setAttributeInternal(TRANSRMADOCID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransDocTyp.
     * @return the TransDocTyp
     */
    public String getTransDocTyp() {
      if(getAttributeInternal(TRANSDOCTYP)==null && getDocTypId()!=null)
      {
        String DocType=(String)EbizParamsAPPUtils.getDsDescFrmAttId(this.getAm(), this.getDocTypId());
        return DocType;
      }
        return (String) getAttributeInternal(TRANSDOCTYP);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransDocTyp.
     * @param value value to set the  TransDocTyp
     */
    public void setTransDocTyp(String value) {
        setAttributeInternal(TRANSDOCTYP, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransTotalBalanceWt.
     * @return the TransTotalBalanceWt
     */
    public Number getTransTotalBalanceWt() {
        if (getAttributeInternal(TRANSTOTALBALANCEWT) == null ||
            (Number) getAttributeInternal(TRANSTOTALGROSSWT) == StaticValue.NUMBER_ZERO) {
           // setTransTotalBalanceWt(this.getAm().getTotalBalanceWtVal());
        }
        return (Number) getAttributeInternal(TRANSTOTALBALANCEWT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransTotalBalanceWt.
     * @param value value to set the  TransTotalBalanceWt
     */
    public void setTransTotalBalanceWt(Number value) {
        setAttributeInternal(TRANSTOTALBALANCEWT, value);
    }

    /**
     * Gets the attribute value for VHCL_NO using the alias name VhclNo.
     * @return the VHCL_NO
     */
    public String getVhclNo() {
        return (String) getAttributeInternal(VHCLNO);
    }

    /**
     * Sets <code>value</code> as attribute value for VHCL_NO using the alias name VhclNo.
     * @param value value to set the VHCL_NO
     */
    public void setVhclNo(String value) {
        setAttributeInternal(VHCLNO, value);
    }

    /**
     * Gets the attribute value for VR_MODE using the alias name VrMode.
     * @return the VR_MODE
     */
    public Integer getVrMode() {
        return (Integer) getAttributeInternal(VRMODE);
    }

    /**
     * Sets <code>value</code> as attribute value for VR_MODE using the alias name VrMode.
     * @param value value to set the VR_MODE
     */
    public void setVrMode(Integer value) {
        setAttributeInternal(VRMODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransVrMode.
     * @return the TransVrMode
     */
    public String getTransVrMode() {
        if (getVrMode() != null && getAttributeInternal(TRANSVRMODE) == null) {
           
            return EbizParamsAPPUtils.getDsDescFrmAttId(this.getAm(), getVrMode());
        }
        return (String) getAttributeInternal(TRANSVRMODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransVrMode.
     * @param value value to set the  TransVrMode
     */
    public void setTransVrMode(String value) {
        setAttributeInternal(TRANSVRMODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransLrDtls.
     * @return the TransLrDtls
     */
    public String getTransLrDtls() {
        
        if(getAttributeInternal(TRANSLRDTLS) == null && getDocId()!=null){
            
            return getAm().getGeneratedLr();
        }
        return (String) getAttributeInternal(TRANSLRDTLS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransLrDtls.
     * @param value value to set the  TransLrDtls
     */
    public void setTransLrDtls(String value) {
        setAttributeInternal(TRANSLRDTLS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransTotalBundle.
     * @return the TransTotalBundle
     */
    public Number getTransTotalBundle() {
        if (getAttributeInternal(TRANSTOTALBUNDLE) == null ||
            (Number) getAttributeInternal(TRANSTOTALBUNDLE) == StaticValue.NUMBER_ZERO) {
//            System.out.println(" ============ getter of getTransTotalBundle "+this.getAm().getTotalBundleVal());
            setTransTotalBundle(this.getAm().getTotalBundleVal());
        }
        return (Number) getAttributeInternal(TRANSTOTALBUNDLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransTotalBundle.
     * @param value value to set the  TransTotalBundle
     */
    public void setTransTotalBundle(Number value) {
        setAttributeInternal(TRANSTOTALBUNDLE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransTotalAmt.
     * @return the TransTotalAmt
     */
    public Number getTransTotalAmt() {
        if (getAttributeInternal(TRANSTOTALAMT) == null ||
            (Number) getAttributeInternal(TRANSTOTALAMT) == StaticValue.NUMBER_ZERO) {
            //System.out.println(" ============ getter of getTransTotalAmt "+this.getAm().getTotalBundleVal());
            setTransTotalAmt(this.getAm().getTotalAmount());
        }
        return (Number) getAttributeInternal(TRANSTOTALAMT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransTotalAmt.
     * @param value value to set the  TransTotalAmt
     */
    public void setTransTotalAmt(Number value) {
        setAttributeInternal(TRANSTOTALAMT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransGroupId.
     * @return the TransGroupId
     */
    public String getTransGroupId() {
        return (String) getAttributeInternal(TRANSGROUPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransGroupId.
     * @param value value to set the  TransGroupId
     */
    public void setTransGroupId(String value) {
        setAttributeInternal(TRANSGROUPID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransGroupNm.
     * @return the TransGroupNm
     */
    public String getTransGroupNm() {
        return (String) getAttributeInternal(TRANSGROUPNM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransGroupNm.
     * @param value value to set the  TransGroupNm
     */
    public void setTransGroupNm(String value) {
        setAttributeInternal(TRANSGROUPNM, value);
    }

    /**
     * Gets the attribute value for CAGE_ID using the alias name CageId.
     * @return the CAGE_ID
     */
    public String getCageId() {
        return (String) getAttributeInternal(CAGEID);
    }

    /**
     * Sets <code>value</code> as attribute value for CAGE_ID using the alias name CageId.
     * @param value value to set the CAGE_ID
     */
    public void setCageId(String value) {
        setAttributeInternal(CAGEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransCageName.
     * @return the TransCageName
     */
    public String getTransCageName() {
        return (String) getAttributeInternal(TRANSCAGENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransCageName.
     * @param value value to set the  TransCageName
     */
    public void setTransCageName(String value) {
        setAttributeInternal(TRANSCAGENAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransTotalCbmVal.
     * @return the TransTotalCbmVal
     */
    public Number getTransTotalCbmVal() {
        if(getAttributeInternal(TRANSTOTALCBMVAL)==null ||(Number)getAttributeInternal(TRANSTOTALCBMVAL)==StaticValue.NUMBER_ZERO){
            setTransTotalCbmVal(this.getAm().getTotalItmCBM());
        }
        
        return (Number) getAttributeInternal(TRANSTOTALCBMVAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransTotalCbmVal.
     * @param value value to set the  TransTotalCbmVal
     */
    public void setTransTotalCbmVal(Number value) {
        setAttributeInternal(TRANSTOTALCBMVAL, value);
    }

    /**
     * Gets the attribute value for AMD_NO using the alias name AmdNo.
     * @return the AMD_NO
     */
    public String getAmdNo() {
        return (String) getAttributeInternal(AMDNO);
    }

    /**
     * Sets <code>value</code> as attribute value for AMD_NO using the alias name AmdNo.
     * @param value value to set the AMD_NO
     */
    public void setAmdNo(String value) {
        setAttributeInternal(AMDNO, value);
    }

  /**
   * Gets the attribute value for the calculated attribute TransTrfDocId.
   * @return the TransTrfDocId
   */
  public String getTransTrfDocId()
  {
    return (String) getAttributeInternal(TRANSTRFDOCID);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute TransTrfDocId.
   * @param value value to set the  TransTrfDocId
   */
  public void setTransTrfDocId(String value)
  {
    setAttributeInternal(TRANSTRFDOCID, value);
  }

  /**
   * Gets the attribute value for the calculated attribute TransCreateType.
   * @return the TransCreateType
   */
  public String getTransCreateType()
  {
    return "C";
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute TransCreateType.
   * @param value value to set the  TransCreateType
   */
  public void setTransCreateType(String value)
  {
    setAttributeInternal(TRANSCREATETYPE, value);
  }

    /**
     * Gets the attribute value for the calculated attribute TransBulkTrfOrdDocId.
     * @return the TransBulkTrfOrdDocId
     */
    public String getTransBulkTrfOrdDocId() {
        return (String) getAttributeInternal(TRANSBULKTRFORDDOCID);
    }
    public void setTransBulkTrfOrdDocId(String value)
    {System.err.println(" value of TransBulkTrfOrdDocId : "+value);
      setAttributeInternal(TRANSBULKTRFORDDOCID, value);
    }

  /**
   * Gets the attribute value for TRF_TYPE using the alias name TrfType.
   * @return the TRF_TYPE
   */
  public Integer getTrfType()
  {
    return (Integer) getAttributeInternal(TRFTYPE);
  }

  /**
   * Sets <code>value</code> as attribute value for TRF_TYPE using the alias name TrfType.
   * @param value value to set the TRF_TYPE
   */
  public void setTrfType(Integer value)
  {
    setAttributeInternal(TRFTYPE, value);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link SlsTrnpBulkVrSrc.
   */
    public RowIterator getSlsTrnpBulkVrSrc() {
        return (RowIterator) getAttributeInternal(SLSTRNPBULKVRSRC);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link SlsTrnpBulkVrItm.
     */
    public RowIterator getSlsTrnpBulkVrItm() {
        return (RowIterator) getAttributeInternal(SLSTRNPBULKVRITM);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovSoIdVO1.
     */
    public RowSet getLovSoIdVO1() {
        return (RowSet) getAttributeInternal(LOVSOIDVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LOVCustNameVO1.
     */
    public RowSet getLOVCustNameVO1() {
        return (RowSet) getAttributeInternal(LOVCUSTNAMEVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LOVItemNmVO1.
     */
    public RowSet getLOVItemNmVO1() {
        return (RowSet) getAttributeInternal(LOVITEMNMVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LOVVhclTypeVO1.
     */
    public RowSet getLOVVhclTypeVO1() {
        return (RowSet) getAttributeInternal(LOVVHCLTYPEVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LOVReqTypVO1.
     */
    public RowSet getLOVReqTypVO1() {
        return (RowSet) getAttributeInternal(LOVREQTYPVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LOVRouteVO1.
     */
    public RowSet getLOVRouteVO1() {
        return (RowSet) getAttributeInternal(LOVROUTEVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LOVLocationIdVO1.
     */
    public RowSet getLOVLocationIdVO1() {
        return (RowSet) getAttributeInternal(LOVLOCATIONIDVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LOVCurrIdVO1.
     */
    public RowSet getLOVCurrIdVO1() {
        return (RowSet) getAttributeInternal(LOVCURRIDVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovSalesRegnVO1.
     */
    public RowSet getLovSalesRegnVO1() {
        return (RowSet) getAttributeInternal(LOVSALESREGNVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LOVSlsRegionVO1.
     */
    public RowSet getLOVSlsRegionVO1() {
        return (RowSet) getAttributeInternal(LOVSLSREGIONVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LOVStatusVO1.
     */
    public RowSet getLOVStatusVO1() {
        return (RowSet) getAttributeInternal(LOVSTATUSVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovDocumentTypeVO1.
     */
    public RowSet getLovDocumentTypeVO1() {
        return (RowSet) getAttributeInternal(LOVDOCUMENTTYPEVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovRmaVO1.
     */
    public RowSet getLovRmaVO1() {
        return (RowSet) getAttributeInternal(LOVRMAVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovDocumentTypeVO2.
     */
    public RowSet getLovDocumentTypeVO2() {
        return (RowSet) getAttributeInternal(LOVDOCUMENTTYPEVO2);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovGroupNmVO1.
     */
    public RowSet getLovGroupNmVO1() {
        return (RowSet) getAttributeInternal(LOVGROUPNMVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovCageVO1.
     */
    public RowSet getLovCageVO1() {
        return (RowSet) getAttributeInternal(LOVCAGEVO1);
    }

  /**
   * Gets the view accessor <code>RowSet</code> LovTrfIdVO1.
   */
  public RowSet getLovTrfIdVO1()
  {
    return (RowSet) getAttributeInternal(LOVTRFIDVO1);
  }

    /**
     * Gets the view accessor <code>RowSet</code> LovBulkTrfOrdVO1.
     */
    public RowSet getLovBulkTrfOrdVO1() {
        return (RowSet) getAttributeInternal(LOVBULKTRFORDVO1);
    }

  /**
   * Gets the view accessor <code>RowSet</code> LovTrfType1.
   */
  public RowSet getLovTrfType1()
  {
    return (RowSet) getAttributeInternal(LOVTRFTYPE1);
  }
}

