package trnpbulkvhclreqapp.model.views;

import adf.utils.bean.StaticValue;
import adf.utils.ebiz.EbizParams;
import adf.utils.ebiz.EbizParamsAPPUtils;

import adf.utils.model.ADFModelUtils;

import com.tangosol.dev.tools.Replace;

import java.math.BigDecimal;
import java.math.BigInteger;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;

import java.sql.Types;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;

import javax.sql.DataSource;

import oracle.adf.view.rich.context.AdfFacesContext;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.ViewObject;
import oracle.jbo.domain.NClobDomain;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;

import trnpbulkvhclreqapp.model.entities.SlsTrnpBulkVrSrcEOImpl;
import trnpbulkvhclreqapp.model.services.TrnpBulkVhclReqAMImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jul 06 12:58:30 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SlsTrnpBulkVrSrcVORowImpl extends ViewRowImpl
{


  public static final int ENTITY_SLSTRNPBULKVRSRCEO = 0;

  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
    public enum AttributesEnum {
    CldId,
    DocId,
    EoId,
    GrossWt,
    HoOrgId,
    LocId,
    OrgId,
    ReqTyp,
    RouteDocId,
    SlocId,
    SrcDocDt,
    SrcDocId,
    UsrIdCreate,
    UsrIdCreateDt,
    UsrIdMod,
    UsrIdModDt,
    VehicleTyp,
    TransSoId,
    TransEoNm,
    TransRoutNm,
    TransVhclTyp,
    TransReqTyp,
    TransChkSelectOrd,
    TransLocNm,
    TransLocId,
    DlvDt,
    DlvSchdlNo,
    WhId,
    ArrivalPnt,
    DeparturePnt,
    TransShipAdds,
    TransBalanceWt,
    TransMode,
    BlncWt,
    TotAmt,
    TotBndl,
    TransWhName,
    VhclNo,
    OldVhclNo,
    TransVhclName,
    TransCageName,
    BtoDocId,
    SlsTrnpBulkVrItm,
    LovVhclName1;
    static AttributesEnum[] vals = null;
    ;
    private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


  public static final int CLDID = AttributesEnum.CldId.index();
  public static final int DOCID = AttributesEnum.DocId.index();
  public static final int EOID = AttributesEnum.EoId.index();
  public static final int GROSSWT = AttributesEnum.GrossWt.index();
  public static final int HOORGID = AttributesEnum.HoOrgId.index();
  public static final int LOCID = AttributesEnum.LocId.index();
  public static final int ORGID = AttributesEnum.OrgId.index();
  public static final int REQTYP = AttributesEnum.ReqTyp.index();
  public static final int ROUTEDOCID = AttributesEnum.RouteDocId.index();
  public static final int SLOCID = AttributesEnum.SlocId.index();
  public static final int SRCDOCDT = AttributesEnum.SrcDocDt.index();
  public static final int SRCDOCID = AttributesEnum.SrcDocId.index();
  public static final int USRIDCREATE = AttributesEnum.UsrIdCreate.index();
  public static final int USRIDCREATEDT = AttributesEnum.UsrIdCreateDt.index();
  public static final int USRIDMOD = AttributesEnum.UsrIdMod.index();
  public static final int USRIDMODDT = AttributesEnum.UsrIdModDt.index();
  public static final int VEHICLETYP = AttributesEnum.VehicleTyp.index();
  public static final int TRANSSOID = AttributesEnum.TransSoId.index();
  public static final int TRANSEONM = AttributesEnum.TransEoNm.index();
  public static final int TRANSROUTNM = AttributesEnum.TransRoutNm.index();
  public static final int TRANSVHCLTYP = AttributesEnum.TransVhclTyp.index();
  public static final int TRANSREQTYP = AttributesEnum.TransReqTyp.index();
  public static final int TRANSCHKSELECTORD = AttributesEnum.TransChkSelectOrd.index();
  public static final int TRANSLOCNM = AttributesEnum.TransLocNm.index();
  public static final int TRANSLOCID = AttributesEnum.TransLocId.index();
  public static final int DLVDT = AttributesEnum.DlvDt.index();
  public static final int DLVSCHDLNO = AttributesEnum.DlvSchdlNo.index();
  public static final int WHID = AttributesEnum.WhId.index();
  public static final int ARRIVALPNT = AttributesEnum.ArrivalPnt.index();
  public static final int DEPARTUREPNT = AttributesEnum.DeparturePnt.index();
  public static final int TRANSSHIPADDS = AttributesEnum.TransShipAdds.index();
  public static final int TRANSBALANCEWT = AttributesEnum.TransBalanceWt.index();
  public static final int TRANSMODE = AttributesEnum.TransMode.index();
  public static final int BLNCWT = AttributesEnum.BlncWt.index();
  public static final int TOTAMT = AttributesEnum.TotAmt.index();
  public static final int TOTBNDL = AttributesEnum.TotBndl.index();
  public static final int TRANSWHNAME = AttributesEnum.TransWhName.index();
  public static final int VHCLNO = AttributesEnum.VhclNo.index();
  public static final int OLDVHCLNO = AttributesEnum.OldVhclNo.index();
  public static final int TRANSVHCLNAME = AttributesEnum.TransVhclName.index();
  public static final int TRANSCAGENAME = AttributesEnum.TransCageName.index();
  public static final int BTODOCID = AttributesEnum.BtoDocId.index();
  public static final int SLSTRNPBULKVRITM = AttributesEnum.SlsTrnpBulkVrItm.index();
  public static final int LOVVHCLNAME1 = AttributesEnum.LovVhclName1.index();

  /**
   * This is the default constructor (do not remove).
   */
    public SlsTrnpBulkVrSrcVORowImpl() {
    }

    /**
     * Gets SlsTrnpBulkVrSrcEO entity object.
     * @return the SlsTrnpBulkVrSrcEO
     */
    public SlsTrnpBulkVrSrcEOImpl getSlsTrnpBulkVrSrcEO() {
        return (SlsTrnpBulkVrSrcEOImpl) getEntity(ENTITY_SLSTRNPBULKVRSRCEO);
    }

    /**
     * Gets the attribute value for CLD_ID using the alias name CldId.
     * @return the CLD_ID
     */
    public String getCldId() {
        return (String) getAttributeInternal(CLDID);
    }

    /**
     * Sets <code>value</code> as attribute value for CLD_ID using the alias name CldId.
     * @param value value to set the CLD_ID
     */
    public void setCldId(String value) {
        setAttributeInternal(CLDID, value);
    }

    /**
     * Gets the attribute value for DOC_ID using the alias name DocId.
     * @return the DOC_ID
     */
    public String getDocId() {
        return (String) getAttributeInternal(DOCID);
    }

    /**
     * Sets <code>value</code> as attribute value for DOC_ID using the alias name DocId.
     * @param value value to set the DOC_ID
     */
    public void setDocId(String value) {
        setAttributeInternal(DOCID, value);
    }

    /**
     * Gets the attribute value for EO_ID using the alias name EoId.
     * @return the EO_ID
     */
    public Integer getEoId() {
        return (Integer) getAttributeInternal(EOID);
    }

    /**
     * Sets <code>value</code> as attribute value for EO_ID using the alias name EoId.
     * @param value value to set the EO_ID
     */
    public void setEoId(Integer value) {
        setAttributeInternal(EOID, value);
    }

    /**
     * Gets the attribute value for GROSS_WT using the alias name GrossWt.
     * @return the GROSS_WT
     */
    public oracle.jbo.domain.Number getGrossWt() {
        return (oracle.jbo.domain.Number) getAttributeInternal(GROSSWT);
    }

    /**
     * Sets <code>value</code> as attribute value for GROSS_WT using the alias name GrossWt.
     * @param value value to set the GROSS_WT
     */
    public void setGrossWt(oracle.jbo.domain.Number value) {
        setAttributeInternal(GROSSWT, value);
    }

    /**
     * Gets the attribute value for HO_ORG_ID using the alias name HoOrgId.
     * @return the HO_ORG_ID
     */
    public String getHoOrgId() {
        return (String) getAttributeInternal(HOORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for HO_ORG_ID using the alias name HoOrgId.
     * @param value value to set the HO_ORG_ID
     */
    public void setHoOrgId(String value) {
        setAttributeInternal(HOORGID, value);
    }

    /**
     * Gets the attribute value for LOC_ID using the alias name LocId.
     * @return the LOC_ID
     */
    public String getLocId() {
        return (String) getAttributeInternal(LOCID);
    }

    /**
     * Sets <code>value</code> as attribute value for LOC_ID using the alias name LocId.
     * @param value value to set the LOC_ID
     */
    public void setLocId(String value) {
        setAttributeInternal(LOCID, value);
    }

    /**
     * Gets the attribute value for ORG_ID using the alias name OrgId.
     * @return the ORG_ID
     */
    public String getOrgId() {
        return (String) getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_ID using the alias name OrgId.
     * @param value value to set the ORG_ID
     */
    public void setOrgId(String value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for REQ_TYP using the alias name ReqTyp.
     * @return the REQ_TYP
     */
    public String getReqTyp() {
        return (String) getAttributeInternal(REQTYP);
    }

    /**
     * Sets <code>value</code> as attribute value for REQ_TYP using the alias name ReqTyp.
     * @param value value to set the REQ_TYP
     */
    public void setReqTyp(String value) {
        setAttributeInternal(REQTYP, value);
    }

    /**
     * Gets the attribute value for ROUTE_DOC_ID using the alias name RouteDocId.
     * @return the ROUTE_DOC_ID
     */
    public String getRouteDocId() {
        return (String) getAttributeInternal(ROUTEDOCID);
    }

    /**
     * Sets <code>value</code> as attribute value for ROUTE_DOC_ID using the alias name RouteDocId.
     * @param value value to set the ROUTE_DOC_ID
     */
    public void setRouteDocId(String value) {
        setAttributeInternal(ROUTEDOCID, value);
    }

    /**
     * Gets the attribute value for SLOC_ID using the alias name SlocId.
     * @return the SLOC_ID
     */
    public Integer getSlocId() {
        return (Integer) getAttributeInternal(SLOCID);
    }

    /**
     * Sets <code>value</code> as attribute value for SLOC_ID using the alias name SlocId.
     * @param value value to set the SLOC_ID
     */
    public void setSlocId(Integer value) {
        setAttributeInternal(SLOCID, value);
    }

    /**
     * Gets the attribute value for SRC_DOC_DT using the alias name SrcDocDt.
     * @return the SRC_DOC_DT
     */
    public Timestamp getSrcDocDt() {
        return (Timestamp) getAttributeInternal(SRCDOCDT);
    }

    /**
     * Sets <code>value</code> as attribute value for SRC_DOC_DT using the alias name SrcDocDt.
     * @param value value to set the SRC_DOC_DT
     */
    public void setSrcDocDt(Timestamp value) {
        setAttributeInternal(SRCDOCDT, value);
    }

    /**
     * Gets the attribute value for SRC_DOC_ID using the alias name SrcDocId.
     * @return the SRC_DOC_ID
     */
    public String getSrcDocId() {
        return (String) getAttributeInternal(SRCDOCID);
    }

    /**
     * Sets <code>value</code> as attribute value for SRC_DOC_ID using the alias name SrcDocId.
     * @param value value to set the SRC_DOC_ID
     */
    public void setSrcDocId(String value) {
        setAttributeInternal(SRCDOCID, value);
    }

    /**
     * Gets the attribute value for USR_ID_CREATE using the alias name UsrIdCreate.
     * @return the USR_ID_CREATE
     */
    public Integer getUsrIdCreate() {
        return (Integer) getAttributeInternal(USRIDCREATE);
    }

    /**
     * Sets <code>value</code> as attribute value for USR_ID_CREATE using the alias name UsrIdCreate.
     * @param value value to set the USR_ID_CREATE
     */
    public void setUsrIdCreate(Integer value) {
        setAttributeInternal(USRIDCREATE, value);
    }

    /**
     * Gets the attribute value for USR_ID_CREATE_DT using the alias name UsrIdCreateDt.
     * @return the USR_ID_CREATE_DT
     */
    public oracle.jbo.domain.Timestamp getUsrIdCreateDt() {
        return (oracle.jbo.domain.Timestamp) getAttributeInternal(USRIDCREATEDT);
    }

    /**
     * Sets <code>value</code> as attribute value for USR_ID_CREATE_DT using the alias name UsrIdCreateDt.
     * @param value value to set the USR_ID_CREATE_DT
     */
    public void setUsrIdCreateDt(oracle.jbo.domain.Timestamp value) {
        setAttributeInternal(USRIDCREATEDT, value);
    }

    /**
     * Gets the attribute value for USR_ID_MOD using the alias name UsrIdMod.
     * @return the USR_ID_MOD
     */
    public Integer getUsrIdMod() {
        return (Integer) getAttributeInternal(USRIDMOD);
    }

    /**
     * Sets <code>value</code> as attribute value for USR_ID_MOD using the alias name UsrIdMod.
     * @param value value to set the USR_ID_MOD
     */
    public void setUsrIdMod(Integer value) {
        setAttributeInternal(USRIDMOD, value);
    }

    /**
     * Gets the attribute value for USR_ID_MOD_DT using the alias name UsrIdModDt.
     * @return the USR_ID_MOD_DT
     */
    public oracle.jbo.domain.Timestamp getUsrIdModDt() {
        return (oracle.jbo.domain.Timestamp) getAttributeInternal(USRIDMODDT);
    }

    /**
     * Sets <code>value</code> as attribute value for USR_ID_MOD_DT using the alias name UsrIdModDt.
     * @param value value to set the USR_ID_MOD_DT
     */
    public void setUsrIdModDt(oracle.jbo.domain.Timestamp value) {
        setAttributeInternal(USRIDMODDT, value);
    }

    /**
     * Gets the attribute value for VEHICLE_TYP using the alias name VehicleTyp.
     * @return the VEHICLE_TYP
     */
    public Integer getVehicleTyp() {
        return (Integer) getAttributeInternal(VEHICLETYP);
    }

    /**
     * Sets <code>value</code> as attribute value for VEHICLE_TYP using the alias name VehicleTyp.
     * @param value value to set the VEHICLE_TYP
     */
    public void setVehicleTyp(Integer value) {
        setAttributeInternal(VEHICLETYP, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransSoId.
     * @return the TransSoId
     */
    public String getTransSoId() {
        if (getAttributeInternal(TRANSSOID) == null && this.getSrcDocId() != null) {
            ViewObject hdrVo = getAm().getSlsTrnpBulkVr1();
            Row cR = hdrVo.getCurrentRow();
            Integer typeId = (Integer) cR.getAttribute("DocTypId");
//            System.err.println("docType get vo DocSrc____________" + typeId);
            if (typeId != null && typeId == 2341) {
                ViewObjectImpl vo = this.getAm().getLovSODispIdVO1();
                vo.setNamedWhereClauseParam("bindDocId", this.getSrcDocId());
                vo.setNamedWhereClauseParam("bindCldId", this.getCldId());
                vo.setNamedWhereClauseParam("bindOrgId", this.getOrgId());
                vo.setNamedWhereClauseParam("bindHoOrgId", this.getHoOrgId());
                vo.setNamedWhereClauseParam("bindSlocId", this.getSlocId());
                vo.executeQuery();
                Row[] r = vo.getAllRowsInRange();
                if (r.length > 0) {
                    setTransSoId((String) r[0].getAttribute("SoId"));
                }
            } else if (typeId != null && typeId == 2342) {
                ViewObject rmaVo = this.getAm().getLovRmaVO1();
                rmaVo.setNamedWhereClauseParam("bindDocId", this.getSrcDocId());
                rmaVo.setNamedWhereClauseParam("BindCldId", this.getCldId());
                rmaVo.setNamedWhereClauseParam("BindOrgId", this.getOrgId());
                rmaVo.setNamedWhereClauseParam("BindHoOrgId", this.getHoOrgId());
                rmaVo.setNamedWhereClauseParam("BindSlocId", this.getSlocId());
                rmaVo.executeQuery();
                Row[] r = rmaVo.getAllRowsInRange();
                if (r.length > 0) {
                    setTransSoId((String) r[0].getAttribute("RmaId"));
                }
            }
          /**
                   * Modified by : Manjeet Singh
                   * Modified on : 13-10-2023
                   * Remarks :  This case added to polpualte item for TransferOrder
                   * TMS ID : 128922
                **/
            else  if (typeId != null && typeId == 915) {
                ViewObjectImpl vo = this.getAm().getLovTrfDispIdVO1();
                vo.setNamedWhereClauseParam("Binddocid", this.getSrcDocId());
                vo.setNamedWhereClauseParam("BindCldId", this.getCldId());
                vo.setNamedWhereClauseParam("BindOrgId", this.getOrgId());
                vo.setNamedWhereClauseParam("BindSlocId", this.getSlocId());
                vo.executeQuery();
                Row[] r = vo.getAllRowsInRange();
                
                if (r.length > 0) {
                    setTransSoId((String) r[0].getAttribute("TrfNo"));
                }
        }
          /**
                   Till Here
                **/
        }
        return (String) getAttributeInternal(TRANSSOID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransSoId.
     * @param value value to set the  TransSoId
     */
    public void setTransSoId(String value) {
        setAttributeInternal(TRANSSOID, value);
    }


    /**
     * @return the Application Module
     */
    protected TrnpBulkVhclReqAMImpl getAm() {
        return (TrnpBulkVhclReqAMImpl) this.getDBTransaction().getRootApplicationModule();
    }

    /**
     * Gets the attribute value for the calculated attribute TransEoNm.
     * @return the TransEoNm
     */
    public String getTransEoNm() {
        if (getAttributeInternal(TRANSEONM) == null && this.getEoId() != null) {
            String EoNm = EbizParamsAPPUtils.getEoDescFrmEoId(this.getAm(), this.getEoId());
            setTransEoNm(EoNm);
        }
        return (String) getAttributeInternal(TRANSEONM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransEoNm.
     * @param value value to set the  TransEoNm
     */
    public void setTransEoNm(String value) {

        setAttributeInternal(TRANSEONM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransRoutNm.
     * @return the TransRoutNm
     */
    public String getTransRoutNm() {
//        System.out.println("this.getRouteDocId()" + this.getRouteDocId());
        if (getAttributeInternal(TRANSROUTNM) == null && this.getRouteDocId() != null) {
//            ViewObjectImpl vo = this.getAm().getLOVRoute1();
//            vo.setRangeSize(-1);
//            vo.setNamedWhereClauseParam("cldIdbind", this.getCldId());
//            vo.setNamedWhereClauseParam("orgIdBind", this.getOrgId());
//            vo.setNamedWhereClauseParam("HoOrgIdBind", this.getHoOrgId());
//            vo.setNamedWhereClauseParam("slocIdBind", this.getSlocId());
//            vo.setNamedWhereClauseParam("RouteDocIdBind", this.getRouteDocId());
//            vo.executeQuery();
//            Row[] r = vo.getAllRowsInRange();
//            if (r.length > 0) {
//                //System.out.println("route nm" + r[0].getAttribute("RouteNm"));
//                setTransRoutNm((String) r[0].getAttribute("RouteNm"));
//            }
                        String routeName=null;
           routeName= this.getAm().getRouteName(this.getRouteDocId());
           return routeName;
        }
        return (String) getAttributeInternal(TRANSROUTNM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransRoutNm.
     * @param value value to set the  TransRoutNm
     */
    public void setTransRoutNm(String value) {
        setAttributeInternal(TRANSROUTNM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransVhclTyp.
     * @return the TransVhclTyp
     */
    public String getTransVhclTyp() {

        if (getAttributeInternal(TRANSVHCLTYP) == null && this.getVehicleTyp() != null) {
            ViewObjectImpl vo = this.getAm().getLOVVhclType1();
            vo.setNamedWhereClauseParam("attIdBind", this.getVehicleTyp());
            vo.setNamedWhereClauseParam("cldIdBind", this.getCldId());
            vo.setNamedWhereClauseParam("hoOrgIdBind", this.getHoOrgId());
            vo.setNamedWhereClauseParam("slocIdBind", this.getSlocId());
            vo.executeQuery();
            Row[] r = vo.getAllRowsInRange();
            if (r.length > 0) {
                setTransVhclTyp((String) r[0].getAttribute("AttNm"));
            }
        }
        return (String) getAttributeInternal(TRANSVHCLTYP);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransVhclTyp.
     * @param value value to set the  TransVhclTyp
     */
    public void setTransVhclTyp(String value) {
        setAttributeInternal(TRANSVHCLTYP, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransReqTyp.
     * @return the TransReqTyp
     */
    public String getTransReqTyp() {
        if (getAttributeInternal(TRANSREQTYP) == null && this.getReqTyp() != null) {
            ViewObjectImpl vo = this.getAm().getLOVReqTyp1();
            vo.setNamedWhereClauseParam("BindAttId", this.getReqTyp());
            vo.executeQuery();
            Row[] r = vo.getAllRowsInRange();
            if (r.length > 0) {
                setTransReqTyp((String) r[0].getAttribute("AttNm"));
                /*** ADDED BY Manjeet ***/
              AdfFacesContext.getCurrentInstance().getPageFlowScope().put("REQ_TYPE",(String) r[0].getAttribute("AttNm"));
            }
        }
        return (String) getAttributeInternal(TRANSREQTYP);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransReqTyp.
     * @param value value to set the  TransReqTyp
     */
    public void setTransReqTyp(String value) {
        setAttributeInternal(TRANSREQTYP, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransChkSelectOrd.
     * @return the TransChkSelectOrd
     */
    public String getTransChkSelectOrd() {
        return (String) getAttributeInternal(TRANSCHKSELECTORD);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransChkSelectOrd.
     * @param value value to set the  TransChkSelectOrd
     */
    public void setTransChkSelectOrd(String value) {
        setAttributeInternal(TRANSCHKSELECTORD, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransLocNm.
     * @return the TransLocNm
     */
    public String getTransLocNm() {
        String locNm = null;
        if (getAttributeInternal(TRANSLOCNM) == null && this.getSrcDocId() != null && locNm==null) {
//            ViewObjectImpl vo = getAm().getLovSalesRegnVO1();
//            vo.setNamedWhereClauseParam("BindHoOrgId", null);
//            vo.setNamedWhereClauseParam("BindOrgId", null);
//            vo.setNamedWhereClauseParam("BindSlocId", null);
//            vo.setNamedWhereClauseParam("BindSoDocId", null);
//            vo.executeQuery();
//
//
//            vo.setNamedWhereClauseParam("BindHoOrgId", EbizParams.GLBL_HO_ORG_ID());
//            vo.setNamedWhereClauseParam("BindOrgId", EbizParams.GLBL_APP_USR_ORG());
//            vo.setNamedWhereClauseParam("BindSlocId", EbizParams.GLBL_APP_SERV_LOC());
//            vo.setNamedWhereClauseParam("BindSoDocId", getSrcDocId());
//            vo.executeQuery();
//
//            Row r[] = vo.getAllRowsInRange();
//            if (r.length > 0) {
//                setTransLocNm((String) r[0].getAttribute("AddsLoc"));
//            }
            
            locNm = this.getAm().getLocName(getSrcDocId());
            System.out.println("========= return LOC NM : "+locNm);
            return locNm;
            //setTransLocNm(locNm);
        }
        return (String) getAttributeInternal(TRANSLOCNM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransLocNm.
     * @param value value to set the  TransLocNm
     */
    public void setTransLocNm(String value) {
        System.out.println("value" + value);
        setAttributeInternal(TRANSLOCNM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransLocId.
     * @return the TransLocId
     */
    public String getTransLocId() {
        return (String) getAttributeInternal(TRANSLOCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransLocId.
     * @param value value to set the  TransLocId
     */
    public void setTransLocId(String value) {
        setAttributeInternal(TRANSLOCID, value);
    }

    /**
     * Gets the attribute value for DLV_DT using the alias name DlvDt.
     * @return the DLV_DT
     */
    public oracle.jbo.domain.Timestamp getDlvDt() {
        return (oracle.jbo.domain.Timestamp) getAttributeInternal(DLVDT);
    }

    /**
     * Sets <code>value</code> as attribute value for DLV_DT using the alias name DlvDt.
     * @param value value to set the DLV_DT
     */
    public void setDlvDt(oracle.jbo.domain.Timestamp value) {
        setAttributeInternal(DLVDT, value);
    }

    /**
     * Gets the attribute value for DLV_SCHDL_NO using the alias name DlvSchdlNo.
     * @return the DLV_SCHDL_NO
     */
    public Integer getDlvSchdlNo() {
        return (Integer) getAttributeInternal(DLVSCHDLNO);
    }

    /**
     * Sets <code>value</code> as attribute value for DLV_SCHDL_NO using the alias name DlvSchdlNo.
     * @param value value to set the DLV_SCHDL_NO
     */
    public void setDlvSchdlNo(Integer value) {
        setAttributeInternal(DLVSCHDLNO, value);
    }

    /**
     * Gets the attribute value for WH_ID using the alias name WhId.
     * @return the WH_ID
     */
    public String getWhId() {
        return (String) getAttributeInternal(WHID);
    }

    /**
     * Sets <code>value</code> as attribute value for WH_ID using the alias name WhId.
     * @param value value to set the WH_ID
     */
    public void setWhId(String value) {
        setAttributeInternal(WHID, value);
    }

    /**
     * Gets the attribute value for ARRIVAL_PNT using the alias name ArrivalPnt.
     * @return the ARRIVAL_PNT
     */
    public String getArrivalPnt() {
        return (String) getAttributeInternal(ARRIVALPNT);
    }

    /**
     * Sets <code>value</code> as attribute value for ARRIVAL_PNT using the alias name ArrivalPnt.
     * @param value value to set the ARRIVAL_PNT
     */
    public void setArrivalPnt(String value) {
        setAttributeInternal(ARRIVALPNT, value);
    }

    /**
     * Gets the attribute value for DEPARTURE_PNT using the alias name DeparturePnt.
     * @return the DEPARTURE_PNT
     */
    public String getDeparturePnt() {
        return (String) getAttributeInternal(DEPARTUREPNT);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPARTURE_PNT using the alias name DeparturePnt.
     * @param value value to set the DEPARTURE_PNT
     */
    public void setDeparturePnt(String value) {
        setAttributeInternal(DEPARTUREPNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransShipAdds.
     * @return the TransShipAdds
     */
    public String getTransShipAdds() {
        String shipAdd = null;
        if (getEoId() != null && getAttributeInternal(TRANSSHIPADDS) == null) {
            String res = null;
            try {
                Object ob =
                    ADFModelUtils.callFunction(getAm(),
                                               new StringBuilder("SLS.FN_GET_DFLT_SHIP_ADDS_OF_EO_ID(?,?,?,?)"), new Object[] {
                                               getSlocId(), getCldId(), getHoOrgId(), getEoId()
                }, Types.VARCHAR);
                if (ob != null) {
                    res = (String) ob;
                    try {
                        Object obj =
                            ADFModelUtils.callFunction(getAm(), new StringBuilder("SLS.FN_GET_ADDS_FRM_ADDS_ID(?,?,?)"), new Object[] {
                                                       getSlocId(), getCldId(), res
                        }, Types.VARCHAR);
                        if (obj != null) {
                            shipAdd = (String) obj;
                            setTransShipAdds(shipAdd);
                        }
                    } catch (Exception e) {
                        res = null;
                    }
                }
            } catch (Exception e) {
                res = null;
            }
        }

        return (String) getAttributeInternal(TRANSSHIPADDS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransShipAdds.
     * @param value value to set the  TransShipAdds
     */
    public void setTransShipAdds(String value) {
        setAttributeInternal(TRANSSHIPADDS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransBalanceWt.
     * @return the TransBalanceWt
     */
    public Number getTransBalanceWt() {
        Number w = StaticValue.NUMBER_ZERO;
//        if (getAttributeInternal(TRANSBALANCEWT) == (null)) {
//            ViewObject vw = getAm().getSlsTrnpBulkVr1();
//            Row cr = vw.getCurrentRow();
//            ViewObject soView = getAm().getTrnpBulkSoView1();
//            Row cR = soView.getCurrentRow();
//            System.out.println("tarnsmode get =" + getTransMode());
//            Object object = null;
//            if (getTransMode() == 0) {
//                if(this.getAm().getTrnpBulkSoView1().getCurrentRow()!=null){
//                w = (Number) this.getAm().getTrnpBulkSoView1().getCurrentRow().getAttribute("TransBalanceWt");
//                try {
//                    object =
//                        ADFModelUtils.callFunction(getAm(),
//                                                   new StringBuilder("SLS.FN_TRNP_UPDT_BLNC_WT_VR_SRC(?,?,?,?,?,?,?)"), new Object[] {
//                                                   EbizParams.GLBL_APP_CLD_ID(), EbizParams.GLBL_APP_SERV_LOC(),
//                                                   EbizParams.GLBL_APP_USR_ORG(), EbizParams.GLBL_HO_ORG_ID(),
//                                                   cr.getAttribute("DocId"), w, cR.getAttribute("DocId")
//
//
//
//
//
//
//                    }, Types.VARCHAR);
//                } catch (Exception e) {
//                    e.printStackTrace();
//                }
//                }
//
//            } else if (getTransMode() == 1 && getGrossWt() != null) {
//                w = this.getBlncWt();
//            }
//
            setTransBalanceWt(w);
//
//
//        }
        return (Number) getAttributeInternal(TRANSBALANCEWT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransBalanceWt.
     * @param value value to set the  TransBalanceWt
     */
    public void setTransBalanceWt(Number value) {
        setAttributeInternal(TRANSBALANCEWT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransMode.
     * @return the TransMode
     */
    public Integer getTransMode() {
        if (getAttributeInternal(TRANSMODE) == null) {
            byte entityState = this.getEntity(0).getEntityState();
            Integer state = new Integer(entityState);
            System.out.println("mode state get=" + state);
            return state;
        }
        return (Integer) getAttributeInternal(TRANSMODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransMode.
     * @param value value to set the  TransMode
     */
    public void setTransMode(Integer value) {
        setAttributeInternal(TRANSMODE, value);
    }

    /**
     * Gets the attribute value for BLNC_WT using the alias name BlncWt.
     * @return the BLNC_WT
     */
    public Number getBlncWt() {
        return (Number) getAttributeInternal(BLNCWT);
    }

    /**
     * Sets <code>value</code> as attribute value for BLNC_WT using the alias name BlncWt.
     * @param value value to set the BLNC_WT
     */
    public void setBlncWt(Number value) {
        setAttributeInternal(BLNCWT, value);
    }


    /**
     * Gets the attribute value for TOT_AMT using the alias name TotAmt.
     * @return the TOT_AMT
     */
    public Number getTotAmt() {
        return (Number) getAttributeInternal(TOTAMT);
    }

    /**
     * Sets <code>value</code> as attribute value for TOT_AMT using the alias name TotAmt.
     * @param value value to set the TOT_AMT
     */
    public void setTotAmt(Number value) {
        setAttributeInternal(TOTAMT, value);
    }

    /**
     * Gets the attribute value for TOT_BNDL using the alias name TotBndl.
     * @return the TOT_BNDL
     */
    public Number getTotBndl() {
        return (Number) getAttributeInternal(TOTBNDL);
    }

    /**
     * Sets <code>value</code> as attribute value for TOT_BNDL using the alias name TotBndl.
     * @param value value to set the TOT_BNDL
     */
    public void setTotBndl(Number value) {
        setAttributeInternal(TOTBNDL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransWhName.
     * @return the TransWhName
     */
    public String getTransWhName() {
        if(getWhId()!=null && getAttributeInternal(TRANSWHNAME)==null){
            String WhIDNm = EbizParamsAPPUtils.getWhDescFrmWhId(this.getAm(), this.getWhId());
            return WhIDNm;
        }
        return (String) getAttributeInternal(TRANSWHNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransWhName.
     * @param value value to set the  TransWhName
     */
    public void setTransWhName(String value) {
        setAttributeInternal(TRANSWHNAME, value);
    }

    /**
     * Gets the attribute value for VHCL_NO using the alias name VhclNo.
     * @return the VHCL_NO
     */
    public String getVhclNo() {
        return (String) getAttributeInternal(VHCLNO);
    }

    /**
     * Sets <code>value</code> as attribute value for VHCL_NO using the alias name VhclNo.
     * @param value value to set the VHCL_NO
     */
    public void setVhclNo(String value) {
        setAttributeInternal(VHCLNO, value);
    }

    /**
     * Gets the attribute value for OLD_VHCL_NO using the alias name OldVhclNo.
     * @return the OLD_VHCL_NO
     */
    public String getOldVhclNo() {
        return (String) getAttributeInternal(OLDVHCLNO);
    }

    /**
     * Sets <code>value</code> as attribute value for OLD_VHCL_NO using the alias name OldVhclNo.
     * @param value value to set the OLD_VHCL_NO
     */
    public void setOldVhclNo(String value) {
        setAttributeInternal(OLDVHCLNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransVhclName.
     * @return the TransVhclName
     */
    public String getTransVhclName() {
        System.out.println(" == Vehicle Name :: "+getAttributeInternal(TRANSVHCLNAME));
        if(getAttributeInternal(TRANSVHCLNAME) == null){
          if(getReqTyp().equals("C") || getReqTyp().equals("T"))
          {
              return getOldVhclNo();
          }
              
                else if (getReqTyp().equals("I"))
                {
                    return getVhclNo();
                }
        }
        return (String) getAttributeInternal(TRANSVHCLNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransVhclName.
     * @param value value to set the  TransVhclName
     */
    public void setTransVhclName(String value) {
//        if(getReqTyp().equals("C") || getReqTyp().equals("T") )
//            setOldVhclNo(value);
//        else if (getReqTyp().equals("I"))
//            setVhclNo(value);
        System.out.println(" Setter :: "+value);
        setAttributeInternal(TRANSVHCLNAME, value);
    }

  /**
   * Gets the attribute value for the calculated attribute TransCageName.
   * @return the TransCageName
   */
  public String getTransCageName()
  {
    Connection conn = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    
    /**
                       * Modified by : Manjeet Singh
                       * Modified on : 13-10-2023
                       * Remarks :  This below code is added for showing Cage Name on the page.
                       * TMS ID : 128922
    **/

    ViewObjectImpl vo1 = getAm().getSlsTrnpBulkVr1();
//System.err.println("_______________inside getTransCageName__________________________");
    if (getAttributeInternal(TRANSCAGENAME) == null &&
        (vo1.getCurrentRow() != null && (String) vo1.getCurrentRow().getAttribute("CageId") != null))
    {
//      System.err.println("_______________when cage id is not null__________________________");
      
      ViewObjectImpl vo = this.getAm().getLovCageVO1();
      vo.setNamedWhereClauseParam("BindCageId", (String) vo1.getCurrentRow().getAttribute("CageId"));
      vo.setNamedWhereClauseParam("BindCldId", EbizParams.GLBL_APP_CLD_ID());
      vo.setNamedWhereClauseParam("BindHoOrgId", EbizParams.GLBL_HO_ORG_ID());
      vo.setNamedWhereClauseParam("BindOrgId", EbizParams.GLBL_APP_USR_ORG());
      vo.setNamedWhereClauseParam("BindSlocId", EbizParams.GLBL_APP_SERV_LOC());
      vo.setNamedWhereClauseParam("BindType", "V");
      vo.setRangeSize(-1);
      vo.executeQuery();
      Row[] r = vo.getAllRowsInRange();
//      System.err.println("_______________when r.length__________________________"+r.length);
      if (r.length > 0)
      {
//        System.err.println("_____________r[0].getAttribute(\"CageNm\")________________________"+r[0].getAttribute("CageNm"));
        setTransCageName((String) r[0].getAttribute("CageNm"));
      }
    }
    /** ************************** TILL HERE ********************* **/
    return (String) getAttributeInternal(TRANSCAGENAME);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute TransCageName.
   * @param value value to set the  TransCageName
   */
  public void setTransCageName(String value)
  {
    setAttributeInternal(TRANSCAGENAME, value);
  }

  /**
   * Gets the attribute value for BTO_DOC_ID using the alias name BtoDocId.
   * @return the BTO_DOC_ID
   */
  public String getBtoDocId()
  {
    return (String) getAttributeInternal(BTODOCID);
  }

  /**
   * Sets <code>value</code> as attribute value for BTO_DOC_ID using the alias name BtoDocId.
   * @param value value to set the BTO_DOC_ID
   */
  public void setBtoDocId(String value)
  {
    setAttributeInternal(BTODOCID, value);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link SlsTrnpBulkVrItm.
   */
    public RowIterator getSlsTrnpBulkVrItm() {
        return (RowIterator) getAttributeInternal(SLSTRNPBULKVRITM);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovVhclName1.
     */
    public RowSet getLovVhclName1() {
        return (RowSet) getAttributeInternal(LOVVHCLNAME1);
    }


}

