package trnpbulkvhclreqapp.model.views;

import adf.utils.bean.StaticValue;
import adf.utils.ebiz.EbizParams;
import adf.utils.ebiz.EbizParamsAPPUtils;

import adf.utils.ebiz.EbizParamsMMUtils;

import adf.utils.ebiz.EbizParamsMNFUtils;
import adf.utils.model.ADFModelUtils;

import java.math.BigDecimal;

import java.sql.SQLException;
import java.sql.Timestamp;

import java.sql.Types;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.NClobDomain;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;

import trnpbulkvhclreqapp.model.entities.SlsTrnpBulkVrItmEOImpl;
import trnpbulkvhclreqapp.model.services.TrnpBulkVhclReqAMImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jul 06 12:59:07 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SlsTrnpBulkVrItmVORowImpl extends ViewRowImpl
{


  public static final int ENTITY_SLSTRNPBULKVRITMEO = 0;

  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
    public enum AttributesEnum {
    CldId,
    DlvDt,
    DlvSchdlNo,
    DocId,
    HoOrgId,
    ItmId,
    ItmSrNo,
    ItmUomBs,
    ItmUomSp,
    OrgId,
    SlocId,
    SrcDocId,
    TotQty,
    UsrIdCreate,
    UsrIdCreateDt,
    UsrIdMod,
    UsrIdModDt,
    WhId,
    TransItmNm,
    TransUomNm,
    TransWareHouse,
    TransAvlblStk,
    DlvQty,
    TransSoQty,
    TransCBM,
    TransUnpostedStk,
    TransBalanceStk,
    TransTotalCBM,
    SchdlDt,
    ColorAttGrpId,
    TransColorAttNm,
    TransWipItmStk,
    TransItemSelected,
    TransSelectAll,
    ItmFlag,
    AvlStk,
    UnpstdStk,
    WipStk,
    ItmCbm,
    BtoDocId,
    TransItemSelectChk,
    SlsSoDlvSchdl;
    static AttributesEnum[] vals = null;
    ;
    private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


  public static final int CLDID = AttributesEnum.CldId.index();
  public static final int DLVDT = AttributesEnum.DlvDt.index();
  public static final int DLVSCHDLNO = AttributesEnum.DlvSchdlNo.index();
  public static final int DOCID = AttributesEnum.DocId.index();
  public static final int HOORGID = AttributesEnum.HoOrgId.index();
  public static final int ITMID = AttributesEnum.ItmId.index();
  public static final int ITMSRNO = AttributesEnum.ItmSrNo.index();
  public static final int ITMUOMBS = AttributesEnum.ItmUomBs.index();
  public static final int ITMUOMSP = AttributesEnum.ItmUomSp.index();
  public static final int ORGID = AttributesEnum.OrgId.index();
  public static final int SLOCID = AttributesEnum.SlocId.index();
  public static final int SRCDOCID = AttributesEnum.SrcDocId.index();
  public static final int TOTQTY = AttributesEnum.TotQty.index();
  public static final int USRIDCREATE = AttributesEnum.UsrIdCreate.index();
  public static final int USRIDCREATEDT = AttributesEnum.UsrIdCreateDt.index();
  public static final int USRIDMOD = AttributesEnum.UsrIdMod.index();
  public static final int USRIDMODDT = AttributesEnum.UsrIdModDt.index();
  public static final int WHID = AttributesEnum.WhId.index();
  public static final int TRANSITMNM = AttributesEnum.TransItmNm.index();
  public static final int TRANSUOMNM = AttributesEnum.TransUomNm.index();
  public static final int TRANSWAREHOUSE = AttributesEnum.TransWareHouse.index();
  public static final int TRANSAVLBLSTK = AttributesEnum.TransAvlblStk.index();
  public static final int DLVQTY = AttributesEnum.DlvQty.index();
  public static final int TRANSSOQTY = AttributesEnum.TransSoQty.index();
  public static final int TRANSCBM = AttributesEnum.TransCBM.index();
  public static final int TRANSUNPOSTEDSTK = AttributesEnum.TransUnpostedStk.index();
  public static final int TRANSBALANCESTK = AttributesEnum.TransBalanceStk.index();
  public static final int TRANSTOTALCBM = AttributesEnum.TransTotalCBM.index();
  public static final int SCHDLDT = AttributesEnum.SchdlDt.index();
  public static final int COLORATTGRPID = AttributesEnum.ColorAttGrpId.index();
  public static final int TRANSCOLORATTNM = AttributesEnum.TransColorAttNm.index();
  public static final int TRANSWIPITMSTK = AttributesEnum.TransWipItmStk.index();
  public static final int TRANSITEMSELECTED = AttributesEnum.TransItemSelected.index();
  public static final int TRANSSELECTALL = AttributesEnum.TransSelectAll.index();
  public static final int ITMFLAG = AttributesEnum.ItmFlag.index();
  public static final int AVLSTK = AttributesEnum.AvlStk.index();
  public static final int UNPSTDSTK = AttributesEnum.UnpstdStk.index();
  public static final int WIPSTK = AttributesEnum.WipStk.index();
  public static final int ITMCBM = AttributesEnum.ItmCbm.index();
  public static final int BTODOCID = AttributesEnum.BtoDocId.index();
  public static final int TRANSITEMSELECTCHK = AttributesEnum.TransItemSelectChk.index();
  public static final int SLSSODLVSCHDL = AttributesEnum.SlsSoDlvSchdl.index();

  /**
   * This is the default constructor (do not remove).
   */
    public SlsTrnpBulkVrItmVORowImpl() {
    }

    /**
     * Gets SlsTrnpBulkVrItmEO entity object.
     * @return the SlsTrnpBulkVrItmEO
     */
    public SlsTrnpBulkVrItmEOImpl getSlsTrnpBulkVrItmEO() {
        return (SlsTrnpBulkVrItmEOImpl) getEntity(ENTITY_SLSTRNPBULKVRITMEO);
    }

    /**
     * Gets the attribute value for CLD_ID using the alias name CldId.
     * @return the CLD_ID
     */
    public String getCldId() {
        return (String) getAttributeInternal(CLDID);
    }

    /**
     * Sets <code>value</code> as attribute value for CLD_ID using the alias name CldId.
     * @param value value to set the CLD_ID
     */
    public void setCldId(String value) {
        setAttributeInternal(CLDID, value);
    }

    /**
     * Gets the attribute value for DLV_DT using the alias name DlvDt.
     * @return the DLV_DT
     */
    public Timestamp getDlvDt() {
        return (Timestamp) getAttributeInternal(DLVDT);
    }

    /**
     * Sets <code>value</code> as attribute value for DLV_DT using the alias name DlvDt.
     * @param value value to set the DLV_DT
     */
    public void setDlvDt(Timestamp value) {
        setAttributeInternal(DLVDT, value);
    }

    /**
     * Gets the attribute value for DLV_SCHDL_NO using the alias name DlvSchdlNo.
     * @return the DLV_SCHDL_NO
     */
    public Integer getDlvSchdlNo() {
        return (Integer) getAttributeInternal(DLVSCHDLNO);
    }

    /**
     * Sets <code>value</code> as attribute value for DLV_SCHDL_NO using the alias name DlvSchdlNo.
     * @param value value to set the DLV_SCHDL_NO
     */
    public void setDlvSchdlNo(Integer value) {
        setAttributeInternal(DLVSCHDLNO, value);
    }

    /**
     * Gets the attribute value for DOC_ID using the alias name DocId.
     * @return the DOC_ID
     */
    public String getDocId() {
        return (String) getAttributeInternal(DOCID);
    }

    /**
     * Sets <code>value</code> as attribute value for DOC_ID using the alias name DocId.
     * @param value value to set the DOC_ID
     */
    public void setDocId(String value) {
        setAttributeInternal(DOCID, value);
    }

    /**
     * Gets the attribute value for HO_ORG_ID using the alias name HoOrgId.
     * @return the HO_ORG_ID
     */
    public String getHoOrgId() {
        return (String) getAttributeInternal(HOORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for HO_ORG_ID using the alias name HoOrgId.
     * @param value value to set the HO_ORG_ID
     */
    public void setHoOrgId(String value) {
        setAttributeInternal(HOORGID, value);
    }

    /**
     * Gets the attribute value for ITM_ID using the alias name ItmId.
     * @return the ITM_ID
     */
    public String getItmId() {
        return (String) getAttributeInternal(ITMID);
    }

    /**
     * Sets <code>value</code> as attribute value for ITM_ID using the alias name ItmId.
     * @param value value to set the ITM_ID
     */
    public void setItmId(String value) {
        setAttributeInternal(ITMID, value);
    }

    /**
     * Gets the attribute value for ITM_SR_NO using the alias name ItmSrNo.
     * @return the ITM_SR_NO
     */
    public Integer getItmSrNo() {
        return (Integer) getAttributeInternal(ITMSRNO);
    }

    /**
     * Sets <code>value</code> as attribute value for ITM_SR_NO using the alias name ItmSrNo.
     * @param value value to set the ITM_SR_NO
     */
    public void setItmSrNo(Integer value) {
        setAttributeInternal(ITMSRNO, value);
    }

    /**
     * Gets the attribute value for ITM_UOM_BS using the alias name ItmUomBs.
     * @return the ITM_UOM_BS
     */
    public String getItmUomBs() {
        return (String) getAttributeInternal(ITMUOMBS);
    }

    /**
     * Sets <code>value</code> as attribute value for ITM_UOM_BS using the alias name ItmUomBs.
     * @param value value to set the ITM_UOM_BS
     */
    public void setItmUomBs(String value) {
        setAttributeInternal(ITMUOMBS, value);
    }

    /**
     * Gets the attribute value for ITM_UOM_SP using the alias name ItmUomSp.
     * @return the ITM_UOM_SP
     */
    public String getItmUomSp() {
        return (String) getAttributeInternal(ITMUOMSP);
    }

    /**
     * Sets <code>value</code> as attribute value for ITM_UOM_SP using the alias name ItmUomSp.
     * @param value value to set the ITM_UOM_SP
     */
    public void setItmUomSp(String value) {
        setAttributeInternal(ITMUOMSP, value);
    }

    /**
     * Gets the attribute value for ORG_ID using the alias name OrgId.
     * @return the ORG_ID
     */
    public String getOrgId() {
        return (String) getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_ID using the alias name OrgId.
     * @param value value to set the ORG_ID
     */
    public void setOrgId(String value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for SLOC_ID using the alias name SlocId.
     * @return the SLOC_ID
     */
    public Integer getSlocId() {
        return (Integer) getAttributeInternal(SLOCID);
    }

    /**
     * Sets <code>value</code> as attribute value for SLOC_ID using the alias name SlocId.
     * @param value value to set the SLOC_ID
     */
    public void setSlocId(Integer value) {
        setAttributeInternal(SLOCID, value);
    }

    /**
     * Gets the attribute value for SRC_DOC_ID using the alias name SrcDocId.
     * @return the SRC_DOC_ID
     */
    public String getSrcDocId() {
        return (String) getAttributeInternal(SRCDOCID);
    }

    /**
     * Sets <code>value</code> as attribute value for SRC_DOC_ID using the alias name SrcDocId.
     * @param value value to set the SRC_DOC_ID
     */
    public void setSrcDocId(String value) {
        setAttributeInternal(SRCDOCID, value);
    }

    /**
     * Gets the attribute value for TOT_QTY using the alias name TotQty.
     * @return the TOT_QTY
     */
    public oracle.jbo.domain.Number getTotQty() {
        return (oracle.jbo.domain.Number) getAttributeInternal(TOTQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for TOT_QTY using the alias name TotQty.
     * @param value value to set the TOT_QTY
     */
    public void setTotQty(oracle.jbo.domain.Number value) {
        setAttributeInternal(TOTQTY, value);
        getAm().setGrossStdWt(this.getItmUomBs(), this.getItmUomSp(), this.getItmId());

    }

    /**
     * Gets the attribute value for USR_ID_CREATE using the alias name UsrIdCreate.
     * @return the USR_ID_CREATE
     */
    public Integer getUsrIdCreate() {
        return (Integer) getAttributeInternal(USRIDCREATE);
    }

    /**
     * Sets <code>value</code> as attribute value for USR_ID_CREATE using the alias name UsrIdCreate.
     * @param value value to set the USR_ID_CREATE
     */
    public void setUsrIdCreate(Integer value) {
        setAttributeInternal(USRIDCREATE, value);
    }

    /**
     * Gets the attribute value for USR_ID_CREATE_DT using the alias name UsrIdCreateDt.
     * @return the USR_ID_CREATE_DT
     */
    public Timestamp getUsrIdCreateDt() {
        return (Timestamp) getAttributeInternal(USRIDCREATEDT);
    }

    /**
     * Sets <code>value</code> as attribute value for USR_ID_CREATE_DT using the alias name UsrIdCreateDt.
     * @param value value to set the USR_ID_CREATE_DT
     */
    public void setUsrIdCreateDt(Timestamp value) {
        setAttributeInternal(USRIDCREATEDT, value);
    }

    /**
     * Gets the attribute value for USR_ID_MOD using the alias name UsrIdMod.
     * @return the USR_ID_MOD
     */
    public Integer getUsrIdMod() {
        return (Integer) getAttributeInternal(USRIDMOD);
    }

    /**
     * Sets <code>value</code> as attribute value for USR_ID_MOD using the alias name UsrIdMod.
     * @param value value to set the USR_ID_MOD
     */
    public void setUsrIdMod(Integer value) {
        setAttributeInternal(USRIDMOD, value);
    }

    /**
     * Gets the attribute value for USR_ID_MOD_DT using the alias name UsrIdModDt.
     * @return the USR_ID_MOD_DT
     */
    public Timestamp getUsrIdModDt() {
        return (Timestamp) getAttributeInternal(USRIDMODDT);
    }

    /**
     * Sets <code>value</code> as attribute value for USR_ID_MOD_DT using the alias name UsrIdModDt.
     * @param value value to set the USR_ID_MOD_DT
     */
    public void setUsrIdModDt(Timestamp value) {
        setAttributeInternal(USRIDMODDT, value);
    }

    /**
     * Gets the attribute value for WH_ID using the alias name WhId.
     * @return the WH_ID
     */
    public String getWhId() {
        return (String) getAttributeInternal(WHID);
    }

    /**
     * Sets <code>value</code> as attribute value for WH_ID using the alias name WhId.
     * @param value value to set the WH_ID
     */
    public void setWhId(String value) {
        setAttributeInternal(WHID, value);
    }

    /**
     * @return the Application Module
     */
    protected TrnpBulkVhclReqAMImpl getAm() {
        return (TrnpBulkVhclReqAMImpl) this.getDBTransaction().getRootApplicationModule();
    }

    /**
     * Gets the attribute value for the calculated attribute TransItmNm.
     * @return the TransItmNm
     */
    String itmNm = null;

    public String getTransItmNm() {
        if (itmNm == null && this.getItmId() != null) {
            itmNm = EbizParamsAPPUtils.getItemDescFrmItmId(this.getAm(), this.getItmId());

        }
        return itmNm;
        //        return (String) getAttributeInternal(TRANSITMNM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransItmNm.
     * @param value value to set the  TransItmNm
     */
    public void setTransItmNm(String value) {
        setAttributeInternal(TRANSITMNM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransUomNm.
     * @return the TransUomNm
     */
    String itmUom = null;

    public String getTransUomNm() {
        if (itmUom == null && this.getItmUomSp() != null) {
            itmUom = EbizParamsMMUtils.getUOMDescFrmUOMId(this.getAm(), this.getItmUomSp());
        }
        return itmUom;
        //        return (String) getAttributeInternal(TRANSUOMNM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransUomNm.
     * @param value value to set the  TransUomNm
     */
    public void setTransUomNm(String value) {
        setAttributeInternal(TRANSUOMNM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransWareHouse.
     * @return the TransWareHouse
     */
    String whNm = null;

    public String getTransWareHouse() {

        if (whNm == null && this.getWhId() != null) {
            whNm = EbizParamsAPPUtils.getWhDescFrmWhId(this.getAm(), this.getWhId());
            //            setTransWareHouse(WhIDNm);
        }
        return whNm;
        //        return (String) getAttributeInternal(TRANSWAREHOUSE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransWareHouse.
     * @param value value to set the  TransWareHouse
     */
    public void setTransWareHouse(String value) {
        setAttributeInternal(TRANSWAREHOUSE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransAvlblStk.
     * @return the TransAvlblStk
     */
    public Number getTransAvlblStk() {
        if (getAttributeInternal(TRANSAVLBLSTK) == null && getItmId() != null && getWhId() != null) {
            //            Number n = this.getAm().getAvlBlStock(this.getItmId(),this.getWhId(),getColorAttGrpId(),getItmUomSp(),getItmUomBs());
            //            //            System.out.println("=============== Available Stock = " + n);
            //            setTransAvlblStk(n);

        }
        return (Number) getAttributeInternal(TRANSAVLBLSTK);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransAvlblStk.
     * @param value value to set the  TransAvlblStk
     */
    public void setTransAvlblStk(Number value) {
        setAttributeInternal(TRANSAVLBLSTK, value);
    }

    /**
     * Gets the attribute value for DLV_QTY using the alias name DlvQty.
     * @return the DLV_QTY
     */
    public Number getDlvQty() {
        return (Number) getAttributeInternal(DLVQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for DLV_QTY using the alias name DlvQty.
     * @param value value to set the DLV_QTY
     */
    public void setDlvQty(Number value) {
        setAttributeInternal(DLVQTY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransSoQty.
     * @return the TransSoQty
     */
    public Number getTransSoQty() {

        if (getAttributeInternal(TRANSSOQTY) == null) {
            try {
//                getAm().getDBTransaction().postChanges();
                Object ob =
                    ADFModelUtils.callFunction(getAm(),
                                               new StringBuilder("SLS.FN_SO_QTY_VLDT_FOR_BLK_VS(?,?,?,?,?,?,?,?,?,?)"), new Object[] {
                                               EbizParams.GLBL_APP_CLD_ID(), EbizParams.GLBL_APP_SERV_LOC(),
                                               EbizParams.GLBL_HO_ORG_ID(), EbizParams.GLBL_APP_USR_ORG(),
                                               getSrcDocId(), getWhId(), getItmId(), getItmSrNo(), getDlvSchdlNo(),
                                               getDocId()
                }, Types.INTEGER);

                setTransSoQty(new Number(ob));

            } catch (Exception e) {
                e.printStackTrace();
            }

        }
        return (Number) getAttributeInternal(TRANSSOQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransSoQty.
     * @param value value to set the  TransSoQty
     */
    public void setTransSoQty(Number value) {
        setAttributeInternal(TRANSSOQTY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransCBM.
     * @return the TransCBM
     */
    public Number getTransCBM() {
        //        if (getAttributeInternal(TRANSCBM) == null) {
        //            try {
        //                getAm().getDBTransaction().postChanges();
        //                Object ob = ADFModelUtils.callFunction(getAm(), new StringBuilder("SLS.FN_GET_CBM_FOR_ITM(?,?,?,?,?)"), new Object[] {
        //                                                       EbizParams.GLBL_APP_CLD_ID(), EbizParams.GLBL_APP_SERV_LOC(),
        //                                                       EbizParams.GLBL_APP_USR_ORG(), EbizParams.GLBL_HO_ORG_ID(),
        //                                                       getItmId()
        //                }, Types.NUMERIC);
        //
        //                if (ob != null) {
        //                    //System.out.println(" ===== === ===CBM In Getter :: "+new Number(ob));
        //                    setTransCBM(new Number(ob));
        //                }
        //
        //            } catch (Exception e) {
        //                e.printStackTrace();
        //            }
        //
        //        }
        return (Number) getAttributeInternal(TRANSCBM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransCBM.
     * @param value value to set the  TransCBM
     */
    public void setTransCBM(Number value) {
        setAttributeInternal(TRANSCBM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransUnpostedStk.
     * @return the TransUnpostedStk
     */
    public Number getTransUnpostedStk() {
        if (getAttributeInternal(TRANSUNPOSTEDSTK) == null && getItmId() != null && getWhId() != null) {
            //            Number n =  this.getAm().unpostedItmStk(getItmId(), getWhId(),getColorAttGrpId());
            //            setTransUnpostedStk(n);

        }
        return (Number) getAttributeInternal(TRANSUNPOSTEDSTK);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransUnpostedStk.
     * @param value value to set the  TransUnpostedStk
     */
    public void setTransUnpostedStk(Number value) {
        setAttributeInternal(TRANSUNPOSTEDSTK, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransBalanceStk.
     * @return the TransBalanceStk
     */
    public Number getTransBalanceStk() {
        if (getAttributeInternal(TRANSBALANCESTK) == null && getItmId() != null && getWhId() != null) {
            Number n = getTransAvlblStk().subtract((Number) getTransUnpostedStk());
            setTransBalanceStk(n);
        }
        return (Number) getAttributeInternal(TRANSBALANCESTK);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransBalanceStk.
     * @param value value to set the  TransBalanceStk
     */
    public void setTransBalanceStk(Number value) {
        setAttributeInternal(TRANSBALANCESTK, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransTotalCBM.
     * @return the TransTotalCBM
     */
    public Number getTransTotalCBM() {

        if (getAttributeInternal(TRANSTOTALCBM) == null ||
            (Number) getAttributeInternal(TRANSTOTALCBM) == StaticValue.NUMBER_ZERO) {

            //setTransTotalCBM(this.getAm().getTotalItmCBM());
        }
        return (Number) getAttributeInternal(TRANSTOTALCBM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransTotalCBM.
     * @param value value to set the  TransTotalCBM
     */
    public void setTransTotalCBM(Number value) {
        setAttributeInternal(TRANSTOTALCBM, value);
    }

    /**
     * Gets the attribute value for SCHDL_DT using the alias name SchdlDt.
     * @return the SCHDL_DT
     */
    public Timestamp getSchdlDt() {
        return (Timestamp) getAttributeInternal(SCHDLDT);
    }

    /**
     * Sets <code>value</code> as attribute value for SCHDL_DT using the alias name SchdlDt.
     * @param value value to set the SCHDL_DT
     */
    public void setSchdlDt(Timestamp value) {
        setAttributeInternal(SCHDLDT, value);
    }

    /**
     * Gets the attribute value for COLOR_ATT_GRP_ID using the alias name ColorAttGrpId.
     * @return the COLOR_ATT_GRP_ID
     */
    public String getColorAttGrpId() {
        return (String) getAttributeInternal(COLORATTGRPID);
    }

    /**
     * Sets <code>value</code> as attribute value for COLOR_ATT_GRP_ID using the alias name ColorAttGrpId.
     * @param value value to set the COLOR_ATT_GRP_ID
     */
    public void setColorAttGrpId(String value) {
        setAttributeInternal(COLORATTGRPID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransColorAttNm.
     * @return the TransColorAttNm
     */
    public String getTransColorAttNm() {
        String attdesc = null;
        //        System.out.println("===== ATT ID + " + getColorAttGrpId());
        if (getAttributeInternal(TRANSCOLORATTNM) == null || getColorAttGrpId() != null) {
            attdesc = EbizParamsMNFUtils.getDescFrmId(getAm(), getColorAttGrpId(), "ATTVAL");
            //            System.out.println("====== ATT NAME ++ Return :: " + attdesc);
            return attdesc;
        }
        return (String) getAttributeInternal(TRANSCOLORATTNM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransColorAttNm.
     * @param value value to set the  TransColorAttNm
     */
    public void setTransColorAttNm(String value) {
        setAttributeInternal(TRANSCOLORATTNM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransWipItmStk.
     * @return the TransWipItmStk
     */
    public Number getTransWipItmStk() {
        if (getAttributeInternal(TRANSWIPITMSTK) == null && getItmId() != null && getWhId() != null) {
            //            Number n = (Number) this.getAm().wipItmStk(getItmId(), getWhId(),getColorAttGrpId());
            //
            //            setTransWipItmStk(n);

        }
        return (Number) getAttributeInternal(TRANSWIPITMSTK);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransWipItmStk.
     * @param value value to set the  TransWipItmStk
     */
    public void setTransWipItmStk(Number value) {
        setAttributeInternal(TRANSWIPITMSTK, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransItemSelected.
     * @return the TransItemSelected
     */
    public Boolean getTransItemSelected() {
        // System.out.println("******************** getTransItemSelected " + getAttributeInternal(TRANSITEMSELECTED));
        return (Boolean) getAttributeInternal(TRANSITEMSELECTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransItemSelected.
     * @param value value to set the  TransItemSelected
     */
    public void setTransItemSelected(Boolean value) {
//       System.err.println("_____________________inside setTransItemSelected___________"+value);
//          if(value==false)
//          {
//            setItmFlag("N");
//          }
//          else if(value==true)
//          {
//            setItmFlag("Y");
//          }
      
      
        setAttributeInternal(TRANSITEMSELECTED, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransSelectAll.
     * @return the TransSelectAll
     */
    public String getTransSelectAll() {
        return (String) getAttributeInternal(TRANSSELECTALL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransSelectAll.
     * @param value value to set the  TransSelectAll
     */
    public void setTransSelectAll(String value) {
        setAttributeInternal(TRANSSELECTALL, value);
    }

    /**
   * Gets the attribute value for ITM_FLAG using the alias name ItmFlag.
   * @return the ITM_FLAG
   */
  public String getItmFlag()
  {
//    System.err.println("_______inside getItmFlag____" + (String) getAttributeInternal(ITMFLAG)+"_____ITM NAME____"+this.getTransItmNm());
    return (String) getAttributeInternal(ITMFLAG);
  }

    /**
     * Sets <code>value</code> as attribute value for ITM_FLAG using the alias name ItmFlag.
     * @param value value to set the ITM_FLAG
     */
    public void setItmFlag(String value) {
//      System.err.println("_____________________inside setItmFlag_____________"+value+"_____ITM NAME____"+this.getTransItmNm());

        setAttributeInternal(ITMFLAG, value);
        this.getAm().getTotalItmCBM();
    }

    /**
     * Gets the attribute value for AVL_STK using the alias name AvlStk.
     * @return the AVL_STK
     */
    public Number getAvlStk() {
        return (Number) getAttributeInternal(AVLSTK);
    }

    /**
     * Sets <code>value</code> as attribute value for AVL_STK using the alias name AvlStk.
     * @param value value to set the AVL_STK
     */
    public void setAvlStk(Number value) {
        setAttributeInternal(AVLSTK, value);
    }

    /**
     * Gets the attribute value for UNPSTD_STK using the alias name UnpstdStk.
     * @return the UNPSTD_STK
     */
    public Number getUnpstdStk() {
        return (Number) getAttributeInternal(UNPSTDSTK);
    }

    /**
     * Sets <code>value</code> as attribute value for UNPSTD_STK using the alias name UnpstdStk.
     * @param value value to set the UNPSTD_STK
     */
    public void setUnpstdStk(Number value) {
        setAttributeInternal(UNPSTDSTK, value);
    }

    /**
     * Gets the attribute value for WIP_STK using the alias name WipStk.
     * @return the WIP_STK
     */
    public Number getWipStk() {
        return (Number) getAttributeInternal(WIPSTK);
    }

    /**
     * Sets <code>value</code> as attribute value for WIP_STK using the alias name WipStk.
     * @param value value to set the WIP_STK
     */
    public void setWipStk(Number value) {
        setAttributeInternal(WIPSTK, value);
    }

    /**
     * Gets the attribute value for ITM_CBM using the alias name ItmCbm.
     * @return the ITM_CBM
     */
    public Number getItmCbm() {
        return (Number) getAttributeInternal(ITMCBM);
    }

    /**
     * Sets <code>value</code> as attribute value for ITM_CBM using the alias name ItmCbm.
     * @param value value to set the ITM_CBM
     */
    public void setItmCbm(Number value) {
        setAttributeInternal(ITMCBM, value);
    }

  /**
   * Gets the attribute value for BTO_DOC_ID using the alias name BtoDocId.
   * @return the BTO_DOC_ID
   */
  public String getBtoDocId()
  {
    return (String) getAttributeInternal(BTODOCID);
  }

  /**
   * Sets <code>value</code> as attribute value for BTO_DOC_ID using the alias name BtoDocId.
   * @param value value to set the BTO_DOC_ID
   */
  public void setBtoDocId(String value)
  {
    setAttributeInternal(BTODOCID, value);
  }

  /**
   * Gets the attribute value for the calculated attribute TransItemSelectChk.
   * @return the TransItemSelectChk
   */
  public Boolean getTransItemSelectChk()
  {
    
    return (Boolean) getAttributeInternal(TRANSITEMSELECTCHK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute TransItemSelectChk.
   * @param value value to set the  TransItemSelectChk
   */
  public void setTransItemSelectChk(Boolean value)
  {
//    System.err.println("_____________________inside setTransItemSelectChk___________"+value);
       if(value==false)
       {
         setItmFlag("N");
       }
       else if(value==true)
       {
         setItmFlag("Y");
       }
    
    setAttributeInternal(TRANSITEMSELECTCHK, value);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link SlsSoDlvSchdl.
   */
    public RowIterator getSlsSoDlvSchdl() {
        return (RowIterator) getAttributeInternal(SLSSODLVSCHDL);
    }

}

