package trnpbulkvhclreqapp.model.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 10 14:40:11 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SlsTrnpBulkVrVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SlsTrnpBulkVrVOImpl() {
    }

    /**
     * Returns the variable value for bindCldId.
     * @return variable value for bindCldId
     */
    public String getbindCldId() {
        return (String) ensureVariableManager().getVariableValue("bindCldId");
    }

    /**
     * Sets <code>value</code> for variable bindCldId.
     * @param value value to bind as bindCldId
     */
    public void setbindCldId(String value) {
        ensureVariableManager().setVariableValue("bindCldId", value);
    }

    /**
     * Returns the variable value for bindSlocId.
     * @return variable value for bindSlocId
     */
    public Integer getbindSlocId() {
        return (Integer) ensureVariableManager().getVariableValue("bindSlocId");
    }

    /**
     * Sets <code>value</code> for variable bindSlocId.
     * @param value value to bind as bindSlocId
     */
    public void setbindSlocId(Integer value) {
        ensureVariableManager().setVariableValue("bindSlocId", value);
    }

    /**
     * Returns the variable value for bindOrgId.
     * @return variable value for bindOrgId
     */
    public String getbindOrgId() {
        return (String) ensureVariableManager().getVariableValue("bindOrgId");
    }

    /**
     * Sets <code>value</code> for variable bindOrgId.
     * @param value value to bind as bindOrgId
     */
    public void setbindOrgId(String value) {
        ensureVariableManager().setVariableValue("bindOrgId", value);
    }

    /**
     * Returns the variable value for bindHoOrgId.
     * @return variable value for bindHoOrgId
     */
    public String getbindHoOrgId() {
        return (String) ensureVariableManager().getVariableValue("bindHoOrgId");
    }

    /**
     * Sets <code>value</code> for variable bindHoOrgId.
     * @param value value to bind as bindHoOrgId
     */
    public void setbindHoOrgId(String value) {
        ensureVariableManager().setVariableValue("bindHoOrgId", value);
    }

    /**
     * Returns the variable value for bindDocId.
     * @return variable value for bindDocId
     */
    public String getbindDocId() {
        return (String) ensureVariableManager().getVariableValue("bindDocId");
    }

    /**
     * Sets <code>value</code> for variable bindDocId.
     * @param value value to bind as bindDocId
     */
    public void setbindDocId(String value) {
        ensureVariableManager().setVariableValue("bindDocId", value);
    }
}

