package trnpbulkvhclreqapp.model.views;

import adf.utils.ebiz.EbizParamsAPPUtils;

import java.math.BigDecimal;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.ViewRowImpl;

import trnpbulkvhclreqapp.model.services.TrnpBulkVhclReqAMImpl;
import trnpbulkvhclreqapp.model.views.common.TrnpBulkTrfViewVORow;
//import trnpbulkvhclreqapp.model.views.common.Type;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Oct 13 15:01:03 IST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TrnpBulkTrfViewVORowImpl
  extends ViewRowImpl
  implements TrnpBulkTrfViewVORow
{
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  public enum AttributesEnum
  {
    CldId,
    SlocId,
    OrgId,
    DocId,
    DocDt,
    FyId,
    TrfNo,
    TrfDt,
    TrfSrcType,
    TrfType,
    DocTypeSrc,
    DocIdSrc,
    WhId,
    RqmtAreaId,
    OrgIdSrc,
    WhIdSrc,
    ReqdDt,
    OrgIdDest,
    WhIdDest,
    TrfStat,
    TrfStatDt,
    InvReqd,
    AuthStat,
    FileNo,
    TrfItmQty,
    TransReqType,
    TransReqTypeId,
    TransCageName,
    CageId,
    TransVhclType,
    TransVhclTypeId,
    TransChkSelect,
    TransWhName,
    LOVReqTypVO1,
    LovCageVO1,
    LOVVhclTypeVO1;
    static AttributesEnum[] vals = null;
    ;
    private static final int firstIndex = 0;

    public int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    public static final int firstIndex()
    {
      return firstIndex;
    }

    public static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    public static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }


  public static final int CLDID = AttributesEnum.CldId.index();
  public static final int SLOCID = AttributesEnum.SlocId.index();
  public static final int ORGID = AttributesEnum.OrgId.index();
  public static final int DOCID = AttributesEnum.DocId.index();
  public static final int DOCDT = AttributesEnum.DocDt.index();
  public static final int FYID = AttributesEnum.FyId.index();
  public static final int TRFNO = AttributesEnum.TrfNo.index();
  public static final int TRFDT = AttributesEnum.TrfDt.index();
  public static final int TRFSRCTYPE = AttributesEnum.TrfSrcType.index();
  public static final int TRFTYPE = AttributesEnum.TrfType.index();
  public static final int DOCTYPESRC = AttributesEnum.DocTypeSrc.index();
  public static final int DOCIDSRC = AttributesEnum.DocIdSrc.index();
  public static final int WHID = AttributesEnum.WhId.index();
  public static final int RQMTAREAID = AttributesEnum.RqmtAreaId.index();
  public static final int ORGIDSRC = AttributesEnum.OrgIdSrc.index();
  public static final int WHIDSRC = AttributesEnum.WhIdSrc.index();
  public static final int REQDDT = AttributesEnum.ReqdDt.index();
  public static final int ORGIDDEST = AttributesEnum.OrgIdDest.index();
  public static final int WHIDDEST = AttributesEnum.WhIdDest.index();
  public static final int TRFSTAT = AttributesEnum.TrfStat.index();
  public static final int TRFSTATDT = AttributesEnum.TrfStatDt.index();
  public static final int INVREQD = AttributesEnum.InvReqd.index();
  public static final int AUTHSTAT = AttributesEnum.AuthStat.index();
  public static final int FILENO = AttributesEnum.FileNo.index();
  public static final int TRFITMQTY = AttributesEnum.TrfItmQty.index();
  public static final int TRANSREQTYPE = AttributesEnum.TransReqType.index();
  public static final int TRANSREQTYPEID = AttributesEnum.TransReqTypeId.index();
  public static final int TRANSCAGENAME = AttributesEnum.TransCageName.index();
  public static final int CAGEID = AttributesEnum.CageId.index();
  public static final int TRANSVHCLTYPE = AttributesEnum.TransVhclType.index();
  public static final int TRANSVHCLTYPEID = AttributesEnum.TransVhclTypeId.index();
  public static final int TRANSCHKSELECT = AttributesEnum.TransChkSelect.index();
  public static final int TRANSWHNAME = AttributesEnum.TransWhName.index();
  public static final int LOVREQTYPVO1 = AttributesEnum.LOVReqTypVO1.index();
  public static final int LOVCAGEVO1 = AttributesEnum.LovCageVO1.index();
  public static final int LOVVHCLTYPEVO1 = AttributesEnum.LOVVhclTypeVO1.index();

  /**
   * This is the default constructor (do not remove).
   */
  public TrnpBulkTrfViewVORowImpl()
  {
  }


  /**
   * Gets the attribute value for the calculated attribute CldId.
   * @return the CldId
   */
  public String getCldId()
  {
    return (String) getAttributeInternal(CLDID);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute CldId.
   * @param value value to set the  CldId
   */
  public void setCldId(String value)
  {
    setAttributeInternal(CLDID, value);
  }

  /**
   * Gets the attribute value for the calculated attribute SlocId.
   * @return the SlocId
   */
  public Integer getSlocId()
  {
    return (Integer) getAttributeInternal(SLOCID);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute SlocId.
   * @param value value to set the  SlocId
   */
  public void setSlocId(Integer value)
  {
    setAttributeInternal(SLOCID, value);
  }

  /**
   * Gets the attribute value for the calculated attribute OrgId.
   * @return the OrgId
   */
  public String getOrgId()
  {
    return (String) getAttributeInternal(ORGID);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute OrgId.
   * @param value value to set the  OrgId
   */
  public void setOrgId(String value)
  {
    setAttributeInternal(ORGID, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DocId.
   * @return the DocId
   */
  public String getDocId()
  {
    return (String) getAttributeInternal(DOCID);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DocId.
   * @param value value to set the  DocId
   */
  public void setDocId(String value)
  {
    setAttributeInternal(DOCID, value);
  }

  /**
   * Gets the attribute value for the calculated attribute TrfNo.
   * @return the TrfNo
   */
  public String getTrfNo()
  {
    return (String) getAttributeInternal(TRFNO);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute TrfNo.
   * @param value value to set the  TrfNo
   */
  public void setTrfNo(String value)
  {
    setAttributeInternal(TRFNO, value);
  }

  /**
   * Gets the attribute value for the calculated attribute TrfDt.
   * @return the TrfDt
   */
  public Timestamp getTrfDt()
  {
    return (Timestamp) getAttributeInternal(TRFDT);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute TrfDt.
   * @param value value to set the  TrfDt
   */
  public void setTrfDt(Timestamp value)
  {
    setAttributeInternal(TRFDT, value);
  }

  /**
   * Gets the attribute value for the calculated attribute TrfSrcType.
   * @return the TrfSrcType
   */
  public Integer getTrfSrcType()
  {
    return (Integer) getAttributeInternal(TRFSRCTYPE);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute TrfSrcType.
   * @param value value to set the  TrfSrcType
   */
  public void setTrfSrcType(Integer value)
  {
    setAttributeInternal(TRFSRCTYPE, value);
  }

  /**
   * Gets the attribute value for the calculated attribute TrfType.
   * @return the TrfType
   */
  public Integer getTrfType()
  {
    return (Integer) getAttributeInternal(TRFTYPE);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute TrfType.
   * @param value value to set the  TrfType
   */
  public void setTrfType(Integer value)
  {
    setAttributeInternal(TRFTYPE, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DocTypeSrc.
   * @return the DocTypeSrc
   */
  public Integer getDocTypeSrc()
  {
    return (Integer) getAttributeInternal(DOCTYPESRC);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DocTypeSrc.
   * @param value value to set the  DocTypeSrc
   */
  public void setDocTypeSrc(Integer value)
  {
    setAttributeInternal(DOCTYPESRC, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DocIdSrc.
   * @return the DocIdSrc
   */
  public String getDocIdSrc()
  {
    return (String) getAttributeInternal(DOCIDSRC);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DocIdSrc.
   * @param value value to set the  DocIdSrc
   */
  public void setDocIdSrc(String value)
  {
    setAttributeInternal(DOCIDSRC, value);
  }

  /**
   * Gets the attribute value for the calculated attribute WhId.
   * @return the WhId
   */
  public String getWhId()
  {
    return (String) getAttributeInternal(WHID);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute WhId.
   * @param value value to set the  WhId
   */
  public void setWhId(String value)
  {
    setAttributeInternal(WHID, value);
  }

  /**
   * Gets the attribute value for the calculated attribute RqmtAreaId.
   * @return the RqmtAreaId
   */
  public Integer getRqmtAreaId()
  {
    return (Integer) getAttributeInternal(RQMTAREAID);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute RqmtAreaId.
   * @param value value to set the  RqmtAreaId
   */
  public void setRqmtAreaId(Integer value)
  {
    setAttributeInternal(RQMTAREAID, value);
  }

  /**
   * Gets the attribute value for the calculated attribute OrgIdSrc.
   * @return the OrgIdSrc
   */
  public String getOrgIdSrc()
  {
    return (String) getAttributeInternal(ORGIDSRC);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute OrgIdSrc.
   * @param value value to set the  OrgIdSrc
   */
  public void setOrgIdSrc(String value)
  {
    setAttributeInternal(ORGIDSRC, value);
  }

  /**
   * Gets the attribute value for the calculated attribute WhIdSrc.
   * @return the WhIdSrc
   */
  public String getWhIdSrc()
  {
    return (String) getAttributeInternal(WHIDSRC);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute WhIdSrc.
   * @param value value to set the  WhIdSrc
   */
  public void setWhIdSrc(String value)
  {
    setAttributeInternal(WHIDSRC, value);
  }

  /**
   * Gets the attribute value for the calculated attribute ReqdDt.
   * @return the ReqdDt
   */
  public Timestamp getReqdDt()
  {
    return (Timestamp) getAttributeInternal(REQDDT);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute ReqdDt.
   * @param value value to set the  ReqdDt
   */
  public void setReqdDt(Timestamp value)
  {
    setAttributeInternal(REQDDT, value);
  }

  /**
   * Gets the attribute value for the calculated attribute OrgIdDest.
   * @return the OrgIdDest
   */
  public String getOrgIdDest()
  {
    return (String) getAttributeInternal(ORGIDDEST);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute OrgIdDest.
   * @param value value to set the  OrgIdDest
   */
  public void setOrgIdDest(String value)
  {
    setAttributeInternal(ORGIDDEST, value);
  }

  /**
   * Gets the attribute value for the calculated attribute WhIdDest.
   * @return the WhIdDest
   */
  public String getWhIdDest()
  {
    return (String) getAttributeInternal(WHIDDEST);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute WhIdDest.
   * @param value value to set the  WhIdDest
   */
  public void setWhIdDest(String value)
  {
    setAttributeInternal(WHIDDEST, value);
  }

  /**
   * Gets the attribute value for the calculated attribute TrfStat.
   * @return the TrfStat
   */
  public Integer getTrfStat()
  {
    return (Integer) getAttributeInternal(TRFSTAT);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute TrfStat.
   * @param value value to set the  TrfStat
   */
  public void setTrfStat(Integer value)
  {
    setAttributeInternal(TRFSTAT, value);
  }

  /**
   * Gets the attribute value for the calculated attribute TrfStatDt.
   * @return the TrfStatDt
   */
  public Timestamp getTrfStatDt()
  {
    return (Timestamp) getAttributeInternal(TRFSTATDT);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute TrfStatDt.
   * @param value value to set the  TrfStatDt
   */
  public void setTrfStatDt(Timestamp value)
  {
    setAttributeInternal(TRFSTATDT, value);
  }

  /**
   * Gets the attribute value for the calculated attribute InvReqd.
   * @return the InvReqd
   */
  public String getInvReqd()
  {
    return (String) getAttributeInternal(INVREQD);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute InvReqd.
   * @param value value to set the  InvReqd
   */
  public void setInvReqd(String value)
  {
    setAttributeInternal(INVREQD, value);
  }

  /**
   * Gets the attribute value for the calculated attribute AuthStat.
   * @return the AuthStat
   */
  public String getAuthStat()
  {
    return (String) getAttributeInternal(AUTHSTAT);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute AuthStat.
   * @param value value to set the  AuthStat
   */
  public void setAuthStat(String value)
  {
    setAttributeInternal(AUTHSTAT, value);
  }

  /**
   * Gets the attribute value for the calculated attribute FileNo.
   * @return the FileNo
   */
  public String getFileNo()
  {
    return (String) getAttributeInternal(FILENO);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute FileNo.
   * @param value value to set the  FileNo
   */
  public void setFileNo(String value)
  {
    setAttributeInternal(FILENO, value);
  }

  /**
   * Gets the attribute value for the calculated attribute TrfItmQty.
   * @return the TrfItmQty
   */
  public Number getTrfItmQty()
  {
    return (Number) getAttributeInternal(TRFITMQTY);
  }

  /**
   * Gets the attribute value for the calculated attribute DocDt.
   * @return the DocDt
   */
  public Timestamp getDocDt()
  {
    return (Timestamp) getAttributeInternal(DOCDT);
  }


  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DocDt.
   * @param value value to set the  DocDt
   */
  public void setDocDt(Timestamp value)
  {
    setAttributeInternal(DOCDT, value);
  }

  /**
   * Gets the attribute value for the calculated attribute FyId.
   * @return the FyId
   */
  public Integer getFyId()
  {
    return (Integer) getAttributeInternal(FYID);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute FyId.
   * @param value value to set the  FyId
   */
  public void setFyId(Integer value)
  {
    setAttributeInternal(FYID, value);
  }

  /**
   * Gets the attribute value for the calculated attribute TransReqType.
   * @return the TransReqType
   */
  public String getTransReqType()
  {
    return (String) getAttributeInternal(TRANSREQTYPE);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute TransReqType.
   * @param value value to set the  TransReqType
   */
  public void setTransReqType(String value)
  {
    setAttributeInternal(TRANSREQTYPE, value);
  }

  /**
   * Gets the attribute value for the calculated attribute TransReqTypeId.
   * @return the TransReqTypeId
   */
  public String getTransReqTypeId()
  {
    return (String) getAttributeInternal(TRANSREQTYPEID);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute TransReqTypeId.
   * @param value value to set the  TransReqTypeId
   */
  public void setTransReqTypeId(String value)
  {
    setAttributeInternal(TRANSREQTYPEID, value);
  }

  /**
   * Gets the attribute value for the calculated attribute TransCageName.
   * @return the TransCageName
   */
  public String getTransCageName()
  {
    return (String) getAttributeInternal(TRANSCAGENAME);
  }

  /**
   * Gets the attribute value for the calculated attribute CageId.
   * @return the CageId
   */
  public String getCageId()
  {
    return (String) getAttributeInternal(CAGEID);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute CageId.
   * @param value value to set the  CageId
   */
  public void setCageId(String value)
  {
    setAttributeInternal(CAGEID, value);
  }

  /**
   * Gets the attribute value for the calculated attribute TransVhclType.
   * @return the TransVhclType
   */
  public String getTransVhclType()
  {
    return (String) getAttributeInternal(TRANSVHCLTYPE);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute TransVhclType.
   * @param value value to set the  TransVhclType
   */
  public void setTransVhclType(String value)
  {
    setAttributeInternal(TRANSVHCLTYPE, value);
  }

  /**
   * Gets the attribute value for the calculated attribute TransVhclTypeId.
   * @return the TransVhclTypeId
   */
  public Integer getTransVhclTypeId()
  {
    return (Integer) getAttributeInternal(TRANSVHCLTYPEID);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute TransVhclTypeId.
   * @param value value to set the  TransVhclTypeId
   */
  public void setTransVhclTypeId(Integer value)
  {
    setAttributeInternal(TRANSVHCLTYPEID, value);
  }

  /**
   * Gets the attribute value for the calculated attribute TransChkSelect.
   * @return the TransChkSelect
   */
  public String getTransChkSelect()
  {
    return (String) getAttributeInternal(TRANSCHKSELECT);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute TransChkSelect.
   * @param value value to set the  TransChkSelect
   */
  public void setTransChkSelect(String value)
  {
    setAttributeInternal(TRANSCHKSELECT, value);
  }
  protected TrnpBulkVhclReqAMImpl getAm() {
        return (TrnpBulkVhclReqAMImpl) this.getDBTransaction().getRootApplicationModule();
    }
  /**
   * Gets the attribute value for the calculated attribute TransWhName.
   * @return the TransWhName
   */
  public String getTransWhName()
  {
    if(getWhId()!=null && getAttributeInternal(TRANSWHNAME)==null){
                    String WhIDNm = EbizParamsAPPUtils.getWhDescFrmWhId(this.getAm(), this.getWhId());
                    return WhIDNm;
                }
    return (String) getAttributeInternal(TRANSWHNAME);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute TransWhName.
   * @param value value to set the  TransWhName
   */
  public void setTransWhName(String value)
  {
    setAttributeInternal(TRANSWHNAME, value);
  }

  /**
   * Gets the view accessor <code>RowSet</code> LOVReqTypVO1.
   */
  public RowSet getLOVReqTypVO1()
  {
    return (RowSet) getAttributeInternal(LOVREQTYPVO1);
  }

  /**
   * Gets the view accessor <code>RowSet</code> LovCageVO1.
   */
  public RowSet getLovCageVO1()
  {
    return (RowSet) getAttributeInternal(LOVCAGEVO1);
  }

  /**
   * Gets the view accessor <code>RowSet</code> LOVVhclTypeVO1.
   */
  public RowSet getLOVVhclTypeVO1()
  {
    return (RowSet) getAttributeInternal(LOVVHCLTYPEVO1);
  }
}

